DROP PROCEDURE [dbo].[SQ_CLINICA_VENDA_PROCEDIMENTO_CAD]
GO
CREATE PROCEDURE SP_ORCAMENTO_CLIENTE_STATUS(@SQ_ORCAMENTO_CLIENTE INT)
AS
BEGIN
	UPDATE TB_ORCAMENTO_CLIENTE
	 SET ID_OPT_STATUS = 732 /* Cadastrado */
	 WHERE SQ_ORCAMENTO_CLIENTE = @SQ_ORCAMENTO_CLIENTE

  IF EXISTS(SELECT * FROM TB_ORCAMENTO_CLIENTE_PROCEDIMENTO WHERE ID_ORCAMENTO_CLIENTE = @SQ_ORCAMENTO_CLIENTE
																														  AND ID_OPT_STATUS = 734) AND
		 EXISTS(SELECT * FROM TB_ORCAMENTO_CLIENTE_PROCEDIMENTO WHERE ID_ORCAMENTO_CLIENTE = @SQ_ORCAMENTO_CLIENTE
																														  AND ID_OPT_STATUS <> 734)
	  UPDATE TB_ORCAMENTO_CLIENTE
		 SET ID_OPT_STATUS = 741 /* Em Aberto */
		 WHERE SQ_ORCAMENTO_CLIENTE = @SQ_ORCAMENTO_CLIENTE
	ELSE IF NOT EXISTS(SELECT * FROM TB_ORCAMENTO_CLIENTE_PROCEDIMENTO WHERE ID_ORCAMENTO_CLIENTE = @SQ_ORCAMENTO_CLIENTE
																																			 AND ID_OPT_STATUS IN (734))
	  UPDATE TB_ORCAMENTO_CLIENTE
		 SET ID_OPT_STATUS = 742 /* Fechado */
		 WHERE SQ_ORCAMENTO_CLIENTE = @SQ_ORCAMENTO_CLIENTE
END
GO
CREATE PROCEDURE [dbo].[SP_CLINICA_VENDA_PROCEDIMENTO_CAD]
(
 @SQ_CLINICA_VENDA_PROCEDIMENTO INT,
 @ID_CLINICA_VENDA INT,
 @ID_PROCEDIMENTO INT,
 @ID_PESSOA_PROFISSIONAL INT,
 @ID_ORCAMENTO_CLIENTE_PROCEDIMENTO INT,
 @VL_PROCEDIMENTO MONEY,
 @VL_DESCONTO MONEY,
 @DT_PREVISAO_FATURAMENTO DATE
)
AS
BEGIN
  DECLARE @ID_ORCAMENTO_CLIENTE INT

  IF ISNULL(@SQ_CLINICA_VENDA_PROCEDIMENTO, 0)  = 0
	  INSERT INTO TB_CLINICA_VENDA_PROCEDIMENTO
		(ID_CLINICA_VENDA, ID_PROCEDIMENTO, ID_PESSOA_PROFISSIONAL, ID_OPT_STATUS, VL_PROCEDIMENTO, VL_DESCONTO,DT_PREVISAO_FATURAMENTO)
		VALUES
		(@ID_CLINICA_VENDA, @ID_PROCEDIMENTO, @ID_PESSOA_PROFISSIONAL, 737  /* Lançado */, @VL_PROCEDIMENTO, @VL_DESCONTO,@DT_PREVISAO_FATURAMENTO)
	ELSE
	 UPDATE TB_CLINICA_VENDA_PROCEDIMENTO
	  SET ID_CLINICA_VENDA=@ID_CLINICA_VENDA,
				ID_PROCEDIMENTO=@ID_PROCEDIMENTO,
				ID_PESSOA_PROFISSIONAL=@ID_PESSOA_PROFISSIONAL,
				VL_PROCEDIMENTO=@VL_PROCEDIMENTO,
				VL_DESCONTO=@VL_DESCONTO,
				 DT_PREVISAO_FATURAMENTO=@DT_PREVISAO_FATURAMENTO
	  WHERE SQ_CLINICA_VENDA_PROCEDIMENTO = @SQ_CLINICA_VENDA_PROCEDIMENTO

	UPDATE TB_ORCAMENTO_CLIENTE_PROCEDIMENTO
	 SET ID_OPT_STATUS = 735 /* Vendido */
	 WHERE SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO = @ID_ORCAMENTO_CLIENTE_PROCEDIMENTO

	SELECT @ID_ORCAMENTO_CLIENTE = ID_ORCAMENTO_CLIENTE
	 FROM TB_ORCAMENTO_CLIENTE_PROCEDIMENTO
	 WHERE SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO = @ID_ORCAMENTO_CLIENTE_PROCEDIMENTO

	EXEC SP_ORCAMENTO_CLIENTE_STATUS @ID_ORCAMENTO_CLIENTE
END