INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (793, 120, 'Botão - Seta', 'S')
GO
INSERT INTO TB_CONFIG_TELA (ID_TELA, DS_PATH_IMAGEM_FUNDO) VALUES (793, 'Formulários\Botao\BTN_Seta_##.png')