INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (782, 120, 'Atendimento\Médico - Atendimentos Realizados - Consulta', 'S')
INSERT INTO TB_CONFIG_TELA (ID_TELA, DS_PATH_IMAGEM_FUNDO) VALUES (782, 'Formulários\Médico - Atendimentos Realizados - Consulta.jpg')
GO
UPDATE TB_CONFIG_TELA SET DS_PATH_IMAGEM_FUNDO = 'Formulários\Médico - Atendimento\Médico - Atendimentos Realizados - Consulta.jpg'
 WHERE ID_TELA = 782
GO
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (783, 120, 'Atendimento\Médico - Faturamento', 'S')
INSERT INTO TB_CONFIG_TELA (ID_TELA, DS_PATH_IMAGEM_FUNDO) VALUES (783, 'Formulários\Médico - Atendimento\Médico - Faturamento.jpg')
GO
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (784, 119, 'Repasse Efetuado', 'S')
GO
ALTER TABLE TB_CLINICA_ATENDIMENTO
 DROP CONSTRAINT DF__TB_CLINIC__VL_RE__682D4650
GO
ALTER TABLE TB_CLINICA_ATENDIMENTO
 DROP COLUMN VL_REPASSE
GO
ALTER TABLE TB_AGENDAMENTO
 DROP COLUMN VL_REPASSE
GO
ALTER PROCEDURE [dbo].[SP_AGENDAMENTO_CAD]
(
	@SQ_AGENDAMENTO int OUTPUT,
	@CD_AGENDAMENTO VARCHAR(10) OUTPUT,
	@ID_EMPRESA int,
	@ID_TIPO_CONSULTA int,
	@ID_AGENDAMENTO_ORIGEM int,
	@ID_PESSOA int,
	@ID_PESSOA_PROFISSIONAL int,
	@ID_ESPECIALIDADE int,
	@ID_CONVENIO int,
	@ID_PROCEDIMENTO int,
	@ID_OPT_STATUS int,
	@DH_AGENDAMENTO datetime,
	@DH_CHEGADA datetime,
	@DH_SAIDA datetime,
	@NO_PESSOA varchar(100),
	@CD_TELEFONE varchar(20),
	@CD_CELULAR varchar(20),
	@DS_COMPLEMENTO varchar(MAX),
	@VL_PROCEDIMENTO MONEY
)
AS
BEGIN
   IF (@ID_OPT_STATUS = 38 /* Agendado */ OR @ID_OPT_STATUS =	581 /* Confirmado */) AND @DH_CHEGADA IS NOT NULL
     SET @ID_OPT_STATUS = 569 /* Aguardando */

  IF ISNULL(@SQ_AGENDAMENTO, 0) = 0
    BEGIN
			SELECT @CD_AGENDAMENTO = dbo.FC_EMPRESA_NOVO_CD_AGENDAMENTO(@ID_EMPRESA)

			UPDATE TB_EMPRESA SET CD_AGENDAMENTO = @CD_AGENDAMENTO WHERE ID_EMPRESA = @ID_EMPRESA

			INSERT INTO TB_AGENDAMENTO
			(ID_AGENDAMENTO_ORIGEM, ID_EMPRESA, ID_PESSOA, ID_PESSOA_PROFISSIONAL, ID_ESPECIALIDADE, ID_CONVENIO,
			 ID_PROCEDIMENTO, CD_AGENDAMENTO, DH_AGENDAMENTO, DH_CHEGADA, DH_SAIDA, NO_PESSOA, CD_TELEFONE,
			 CD_CELULAR, DS_COMPLEMENTO, ID_TIPO_CONSULTA, VL_PROCEDIMENTO, ID_OPT_STATUS)
			VALUES
			(@ID_AGENDAMENTO_ORIGEM, @ID_EMPRESA, @ID_PESSOA, @ID_PESSOA_PROFISSIONAL, @ID_ESPECIALIDADE, @ID_CONVENIO,
			 @ID_PROCEDIMENTO, @CD_AGENDAMENTO, @DH_AGENDAMENTO, @DH_CHEGADA, @DH_SAIDA, @NO_PESSOA, @CD_TELEFONE,
			 @CD_CELULAR, @DS_COMPLEMENTO, @ID_TIPO_CONSULTA, @VL_PROCEDIMENTO, @ID_OPT_STATUS)

			SET @SQ_AGENDAMENTO = @@IDENTITY
		END
	ELSE
    UPDATE TB_AGENDAMENTO
		 SET ID_AGENDAMENTO_ORIGEM = @ID_AGENDAMENTO_ORIGEM,
				 ID_EMPRESA = @ID_EMPRESA,
				 ID_PESSOA = @ID_PESSOA,
				 ID_PESSOA_PROFISSIONAL = @ID_PESSOA_PROFISSIONAL,
				 ID_ESPECIALIDADE = @ID_ESPECIALIDADE,
				 ID_CONVENIO = @ID_CONVENIO,
				 ID_PROCEDIMENTO = @ID_PROCEDIMENTO,
				 DH_AGENDAMENTO = @DH_AGENDAMENTO,
			   DH_CHEGADA = @DH_CHEGADA,
				 DH_SAIDA = @DH_SAIDA,
				 NO_PESSOA = @NO_PESSOA,
				 CD_TELEFONE = @CD_TELEFONE,
				 CD_CELULAR = @CD_CELULAR,
				 DS_COMPLEMENTO = @DS_COMPLEMENTO,
				 ID_OPT_STATUS = @ID_OPT_STATUS,
				 ID_TIPO_CONSULTA = @ID_TIPO_CONSULTA,
				 VL_PROCEDIMENTO = @VL_PROCEDIMENTO
		 WHERE SQ_AGENDAMENTO = @SQ_AGENDAMENTO 

  RETURN
END
GO
ALTER PROCEDURE [dbo].[SP_CLINICA_ATENDIMENTO_CAD]
(
 @SQ_CLINICA_ATENDIMENTO INT OUT,
 @ID_EMPRESA INT,
 @ID_PESSOA INT,
 @ID_PESSOA_PROFISSIONAL INT,
 @ID_PROCEDIMENTO INT,
 @ID_AGENDAMENTO INT,
 @ID_CONSULTORIO INT,
 @ID_OPT_STATUS INT,
 @DH_CLINICA_ATENDIMENTO DATETIME,
 @DS_CLINICA_ATENDIMENTO TEXT
)
AS
BEGIN
  IF ISNULL(@SQ_CLINICA_ATENDIMENTO, 0) = 0
	  BEGIN
		  INSERT INTO TB_CLINICA_ATENDIMENTO
			(ID_EMPRESA, ID_PESSOA, ID_PESSOA_PROFISSIONAL, ID_AGENDAMENTO, ID_PROCEDIMENTO, ID_CONSULTORIO, ID_OPT_STATUS, DH_CLINICA_ATENDIMENTO, DS_CLINICA_ATENDIMENTO)
			VALUES
			(@ID_EMPRESA, @ID_PESSOA, @ID_PESSOA_PROFISSIONAL, @ID_AGENDAMENTO, @ID_PROCEDIMENTO, @ID_CONSULTORIO, @ID_OPT_STATUS, @DH_CLINICA_ATENDIMENTO, @DS_CLINICA_ATENDIMENTO)

		  SET @SQ_CLINICA_ATENDIMENTO = @@IDENTITY
		END
	ELSE
		UPDATE TB_CLINICA_ATENDIMENTO
		 SET ID_EMPRESA = @ID_EMPRESA,
				 ID_PESSOA = @ID_PESSOA,
				 ID_PESSOA_PROFISSIONAL = @ID_PESSOA_PROFISSIONAL,
			   ID_AGENDAMENTO = @ID_AGENDAMENTO,
				 ID_PROCEDIMENTO = @ID_PROCEDIMENTO,
				 ID_CONSULTORIO = @ID_CONSULTORIO,
				 ID_OPT_STATUS = @ID_OPT_STATUS,
				 DH_CLINICA_ATENDIMENTO = @DH_CLINICA_ATENDIMENTO,
				 DS_CLINICA_ATENDIMENTO = @DS_CLINICA_ATENDIMENTO
		 WHERE SQ_CLINICA_ATENDIMENTO = @SQ_CLINICA_ATENDIMENTO

	IF @ID_OPT_STATUS = 51 AND ISNULL(@ID_AGENDAMENTO, 0) <> 0
	  UPDATE TB_AGENDAMENTO
		 SET ID_OPT_STATUS = 41
		 WHERE SQ_AGENDAMENTO = @ID_AGENDAMENTO

	RETURN
END
GO
ALTER TABLE TB_CLINICA_ATENDIMENTO
 DROP CONSTRAINT DF__TB_CLINIC__VL_PR__67392217
GO
ALTER TABLE TB_CLINICA_ATENDIMENTO
 DROP COLUMN VL_PROCEDIMENTO
GO
ALTER TABLE TB_CLINICA_VENDA_PROCEDIMENTO
 ADD VL_REPASSE MONEY DEFAULT 0
GO
UPDATE TB_CLINICA_VENDA_PROCEDIMENTO SET VL_REPASSE = 0
GO
ALTER TABLE TB_CLINICA_VENDA_PROCEDIMENTO
 ALTER COLUMN VL_REPASSE MONEY NOT NULL
GO
ALTER PROCEDURE [dbo].[SP_CLINICA_VENDA_PROCEDIMENTO_CAD]
(
 @SQ_CLINICA_VENDA_PROCEDIMENTO INT,
 @ID_CLINICA_VENDA INT,
 @ID_PROCEDIMENTO INT,
 @ID_PESSOA_PROFISSIONAL INT,
 @ID_ORCAMENTO_CLIENTE_PROCEDIMENTO INT,
 @VL_PROCEDIMENTO MONEY,
 @VL_REPASSE MONEY,
 @VL_DESCONTO MONEY,
 @DT_PREVISAO_FATURAMENTO DATE
)
AS
BEGIN
  DECLARE @ID_ORCAMENTO_CLIENTE INT

  IF ISNULL(@SQ_CLINICA_VENDA_PROCEDIMENTO, 0)  = 0
	  INSERT INTO TB_CLINICA_VENDA_PROCEDIMENTO
		(ID_CLINICA_VENDA, ID_PROCEDIMENTO, ID_PESSOA_PROFISSIONAL, ID_OPT_STATUS, VL_PROCEDIMENTO, VL_REPASSE, VL_DESCONTO,DT_PREVISAO_FATURAMENTO)
		VALUES
		(@ID_CLINICA_VENDA, @ID_PROCEDIMENTO, @ID_PESSOA_PROFISSIONAL, 737  /* Lançado */, @VL_PROCEDIMENTO, @VL_REPASSE, @VL_DESCONTO,@DT_PREVISAO_FATURAMENTO)
	ELSE
	 UPDATE TB_CLINICA_VENDA_PROCEDIMENTO
	  SET ID_CLINICA_VENDA=@ID_CLINICA_VENDA,
				ID_PROCEDIMENTO=@ID_PROCEDIMENTO,
				ID_PESSOA_PROFISSIONAL=@ID_PESSOA_PROFISSIONAL,
				VL_PROCEDIMENTO=@VL_PROCEDIMENTO,
				VL_REPASSE = @VL_REPASSE,
				VL_DESCONTO=@VL_DESCONTO,
				DT_PREVISAO_FATURAMENTO=@DT_PREVISAO_FATURAMENTO
	  WHERE SQ_CLINICA_VENDA_PROCEDIMENTO = @SQ_CLINICA_VENDA_PROCEDIMENTO

	IF ISNULL(@ID_ORCAMENTO_CLIENTE_PROCEDIMENTO, 0) <> 0
	  BEGIN
			UPDATE TB_ORCAMENTO_CLIENTE_PROCEDIMENTO
			 SET ID_OPT_STATUS = 735 /* Vendido */
			 WHERE SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO = @ID_ORCAMENTO_CLIENTE_PROCEDIMENTO

			SELECT @ID_ORCAMENTO_CLIENTE = ID_ORCAMENTO_CLIENTE
			 FROM TB_ORCAMENTO_CLIENTE_PROCEDIMENTO
			 WHERE SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO = @ID_ORCAMENTO_CLIENTE_PROCEDIMENTO
		END

	EXEC SP_ORCAMENTO_CLIENTE_STATUS @ID_ORCAMENTO_CLIENTE
END
GO
UPDATE A SET VL_REPASSE = C.VL_REPASSE
 FROM TB_CLINICA_VENDA_PROCEDIMENTO A
  INNER JOIN TB_CLINICA_VENDA B ON B.SQ_CLINICA_VENDA = A.ID_CLINICA_VENDA
  INNER JOIN TB_CONVENIO_PROCEDIMENTO C ON C.ID_CONVENIO = B.ID_CONVENIO
	                                     AND C.ID_PROCEDIMENTO = A.ID_PROCEDIMENTO
																			 AND C.ID_PESSOA_PROFISSIONAL = A.ID_PESSOA_PROFISSIONAL
GO
UPDATE BNC SET CD_CLINICA_VENDA = X.COD
 FROM TB_CLINICA_VENDA BNC
  INNER JOIN (SELECT 'CV' + REPLACE(RIGHT(SPACE(10) + CAST(ROW_NUMBER() OVER(ORDER BY SQ_CLINICA_VENDA) AS VARCHAR(10)), 6), ' ', '0') COD, *
               FROM TB_CLINICA_VENDA) X ON X.SQ_CLINICA_VENDA = BNC.SQ_CLINICA_VENDA
GO
UPDATE TB_EMPRESA SET CD_CLINICA_VENDA = (SELECT MAX(CD_CLINICA_VENDA) FROM TB_CLINICA_VENDA)
GO
ALTER PROCEDURE [dbo].[SP_CLINICA_VENDA_CAD]
(
 @SQ_CLINICA_VENDA INT OUT,
 @CD_CLINICA_VENDA VARCHAR(10) OUT,
 @ID_EMPRESA INT,
 @ID_CONTAFINANCEIRA INT,
 @ID_PESSOA INT,
 @ID_CONVENIO INT,
 @ID_ATENDIMENTO INT,
 @ID_AGENDAMENTO INT,
 @ID_ORCAMENTO_CLIENTE INT,
 @ID_INDICACAO INT,
 @DH_VENDA DATETIME
)
AS
BEGIN
  IF ISNULL(@SQ_CLINICA_VENDA, 0) = 0
		BEGIN
			SELECT @CD_CLINICA_VENDA = dbo.FC_EMPRESA_NOVO_CD_CLINICA_VENDA(@ID_EMPRESA)

			UPDATE TB_EMPRESA SET CD_CLINICA_VENDA = @CD_CLINICA_VENDA WHERE ID_EMPRESA = @ID_EMPRESA

			INSERT INTO TB_CLINICA_VENDA
			(ID_EMPRESA, ID_CONTAFINANCEIRA, ID_PESSOA, ID_CONVENIO, ID_ATENDIMENTO, ID_AGENDAMENTO,
			 ID_ORCAMENTO_CLIENTE, ID_INDICACAO, ID_OPT_STATUS, CD_CLINICA_VENDA, DH_VENDA)
			VALUES
			(@ID_EMPRESA, @ID_CONTAFINANCEIRA, @ID_PESSOA, @ID_CONVENIO, @ID_ATENDIMENTO, @ID_AGENDAMENTO,
			 @ID_ORCAMENTO_CLIENTE, @ID_INDICACAO, 737  /* Lançado */, @CD_CLINICA_VENDA, @DH_VENDA)

			SET @SQ_CLINICA_VENDA = @@IDENTITY
		END
	ELSE
	  UPDATE TB_CLINICA_VENDA
		 SET ID_EMPRESA=@ID_EMPRESA,
				 ID_CONTAFINANCEIRA=@ID_CONTAFINANCEIRA,
				 ID_PESSOA=@ID_PESSOA,
				 ID_CONVENIO=@ID_CONVENIO,
				 ID_ATENDIMENTO=@ID_ATENDIMENTO,
				 ID_AGENDAMENTO=@ID_AGENDAMENTO,
				 ID_ORCAMENTO_CLIENTE=@ID_ORCAMENTO_CLIENTE,
			   ID_INDICACAO=@ID_INDICACAO,
				 DH_VENDA=@DH_VENDA
		 WHERE SQ_CLINICA_VENDA = @SQ_CLINICA_VENDA

	IF ISNULL(@ID_AGENDAMENTO, 0) <> 0
	 UPDATE TB_AGENDAMENTO
	  SET ID_OPT_STATUS = 718 /* Aguardando Atendimento */
	  WHERE SQ_AGENDAMENTO = @ID_AGENDAMENTO

	RETURN
END
GO
CREATE VIEW VW_CLINICA_VENDA_PENDENTE_REPASSE
AS
SELECT CVDPC.SQ_CLINICA_VENDA_PROCEDIMENTO,
       CVDPC.ID_PESSOA_PROFISSIONAL,
			 CLVND.ID_CONVENIO,
       CLVND.CD_CLINICA_VENDA,
			 CLVND.DH_VENDA,
			 PESSO_PROFI.NO_PESSOA NO_PESSOA_PROFISSIONAL,
			 PESSO.NO_PESSOA,
       PROCE.NO_PROCEDIMENTO,
			 CVDPC.VL_PROCEDIMENTO,
			 CVDPC.VL_REPASSE
 FROM TB_CLINICA_VENDA CLVND
  INNER JOIN TB_CLINICA_VENDA_PROCEDIMENTO CVDPC ON CVDPC.ID_CLINICA_VENDA = CLVND.SQ_CLINICA_VENDA
	INNER JOIN TB_PESSOA PESSO_PROFI ON PESSO_PROFI.SQ_PESSOA = CVDPC.ID_PESSOA_PROFISSIONAL
	INNER JOIN TB_PESSOA PESSO ON PESSO.SQ_PESSOA = CLVND.ID_PESSOA
	INNER JOIN TB_PROCEDIMENTO PROCE ON PROCE.SQ_PROCEDIMENTO = CVDPC.ID_PROCEDIMENTO
 WHERE CVDPC.ID_OPT_STATUS = 737
GO
ALTER TABLE TB_CLINICA_VENDA_PROCEDIMENTO
 ADD ID_MOVFINANCEIRA INT
GO
ALTER TABLE TB_CLINICA_VENDA_PROCEDIMENTO WITH CHECK ADD CONSTRAINT FK_CLVCN_MVFNC FOREIGN KEY(ID_MOVFINANCEIRA)
 REFERENCES TB_MOVFINANCEIRA (SQ_MOVFINANCEIRA)
GO
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (784, 120, 'Botão - Faturar', 'S')
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (785, 120, 'Botão - Financeiro', 'S')
GO
INSERT INTO TB_CONFIG_TELA (ID_TELA, DS_PATH_IMAGEM_FUNDO) VALUES (784, 'Formulários\Botao\BTN_Faturar_##.png')
INSERT INTO TB_CONFIG_TELA (ID_TELA, DS_PATH_IMAGEM_FUNDO) VALUES (785, 'Formulários\Botao\BTN_Financeiro_##.png')
GO
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (786, 119, 'Repasse realizado', 'S')