INSERT INTO TB_TIPO_OPCAO (SQ_TIPO_OPCAO, NO_TIPO_OPCAO) VALUES (117, 'Status Orçamento Clínica')
INSERT INTO TB_TIPO_OPCAO (SQ_TIPO_OPCAO, NO_TIPO_OPCAO) VALUES (118, 'Status Item Orçamento Clínica')
GO
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (732, 117, 'Cadastrado', 'S')
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (733, 117, 'Cancelado', 'S')
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (734, 118, 'Cadastrado', 'S')
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (735, 118, 'Aceito', 'S')
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (736, 118, 'Cancelado', 'S')
GO
ALTER TABLE TB_ORCAMENTO_CLIENTE_PROCEDIMENTO
 ADD ID_OPT_STATUS INT NOT NULL DEFAULT  734
GO
ALTER TABLE TB_ORCAMENTO_CLIENTE
 ADD ID_OPT_STATUS INT NOT NULL DEFAULT  732
GO
ALTER TABLE TB_ORCAMENTO_CLIENTE_PROCEDIMENTO  WITH CHECK ADD  CONSTRAINT FK_OCPRC_OPCAO_STATU FOREIGN KEY(ID_OPT_STATUS)
 REFERENCES TB_OPCAO (SQ_OPCAO)
GO
ALTER TABLE TB_ORCAMENTO_CLIENTE  WITH CHECK ADD  CONSTRAINT FK_OCCLI_EMPRE FOREIGN KEY(ID_EMPRESA)
 REFERENCES TB_OPCAO (SQ_OPCAO)
GO
ALTER TABLE TB_ORCAMENTO_CLIENTE
 ADD ID_PESSOA_PROFISSIONAL INT NOT NULL
GO
ALTER TABLE TB_ORCAMENTO_CLIENTE  WITH CHECK ADD  CONSTRAINT FK_OCCLI_PESSO_PROFI FOREIGN KEY(ID_PESSOA_PROFISSIONAL, ID_EMPRESA)
 REFERENCES TB_PESSOA_EMPRESA (ID_PESSOA, ID_EMPRESA)
GO
ALTER PROCEDURE SP_ORCAMENTO_CLIENTE_CAD
(
 @SQ_ORCAMENTO_CLIENTE INT OUTPUT,
 @ID_EMPRESA INT,
 @ID_PESSOA_PROFISSIONAL INT,
 @ID_PESSOA INT,
 @ID_CONVENIO INT,
 @ID_FINANCIAMENTO INT,
 @ID_AGENDAMENTO INT,
 @CD_ORCAMENTO_CLIENTE VARCHAR(10) OUT,
 @DH_ORCAMENTO_CLIENTE DATETIME,
 @DT_VALIDADE DATE
)
AS
BEGIN
  IF ISNULL(@SQ_ORCAMENTO_CLIENTE, 0) = 0
		BEGIN
			SELECT @CD_ORCAMENTO_CLIENTE = dbo.FC_EMPRESA_NOVO_CD_ORCAMENTOCLINICA(@ID_EMPRESA)

			UPDATE TB_EMPRESA SET CD_ORCAMENTOCLINICA = @CD_ORCAMENTO_CLIENTE WHERE ID_EMPRESA = @ID_EMPRESA

			INSERT INTO TB_ORCAMENTO_CLIENTE
			(ID_EMPRESA,ID_PESSOA,ID_PESSOA_PROFISSIONAL,ID_CONVENIO,ID_FINANCIAMENTO,ID_AGENDAMENTO,CD_ORCAMENTO_CLIENTE,DH_ORCAMENTO_CLIENTE,DT_VALIDADE)
			VALUES
			(@ID_EMPRESA,@ID_PESSOA,@ID_PESSOA_PROFISSIONAL,@ID_CONVENIO,@ID_FINANCIAMENTO,@ID_AGENDAMENTO,@CD_ORCAMENTO_CLIENTE,@DH_ORCAMENTO_CLIENTE,@DT_VALIDADE)

			SET @SQ_ORCAMENTO_CLIENTE = @@IDENTITY
		END
	ELSE
	  UPDATE TB_ORCAMENTO_CLIENTE
		 SET ID_EMPRESA=@ID_EMPRESA,
				 ID_PESSOA=@ID_PESSOA,
				 ID_PESSOA_PROFISSIONAL=@ID_PESSOA_PROFISSIONAL,
				 ID_CONVENIO=@ID_CONVENIO,
				 ID_FINANCIAMENTO=@ID_FINANCIAMENTO,
				 ID_AGENDAMENTO=@ID_AGENDAMENTO,
				 CD_ORCAMENTO_CLIENTE=ISNULL(@CD_ORCAMENTO_CLIENTE, CD_ORCAMENTO_CLIENTE),
				 DH_ORCAMENTO_CLIENTE=@DH_ORCAMENTO_CLIENTE,
				 DT_VALIDADE=@DT_VALIDADE
		 WHERE SQ_ORCAMENTO_CLIENTE = @SQ_ORCAMENTO_CLIENTE

	RETURN
END
GO
ALTER PROCEDURE [dbo].[SP_ORCAMENTO_CLIENTE_PROCEDIMENTO_CAD]
(
 @SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO INT,
 @ID_ORCAMENTO_CLIENTE INT,
 @ID_PROCEDIMENTO INT,
 @VL_ORCADO MONEY
)
AS
BEGIN
  IF ISNULL(@SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO, 0) = 0
		INSERT INTO TB_ORCAMENTO_CLIENTE_PROCEDIMENTO
		(ID_ORCAMENTO_CLIENTE,ID_PROCEDIMENTO,VL_ORCADO)
     VALUES
		(@ID_ORCAMENTO_CLIENTE,@ID_PROCEDIMENTO,@VL_ORCADO)
	ELSE
	  UPDATE TB_ORCAMENTO_CLIENTE_PROCEDIMENTO
		 SET ID_ORCAMENTO_CLIENTE=@ID_ORCAMENTO_CLIENTE,
				 ID_PROCEDIMENTO=@ID_PROCEDIMENTO,
				 VL_ORCADO=@VL_ORCADO
		 WHERE SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO = @SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO
END