USE Cli28Julho
GO
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (787, 123, 'Vendido', 'S')
GO
EXEC sp_rename 'TB_CLINICA_PROCEDIMENTO.SQ_CLINICA_EXAME', 'SQ_CLINICA_PROCEDIMENTO', 'COLUMN';
GO
DROP PROCEDURE [dbo].[SP_CLINICA_PROCEDIMENTO]
GO
CREATE PROCEDURE [dbo].[SP_CLINICA_PROCEDIMENTO_CAD]
(
 @SQ_CLINICA_PROCEDIMENTO INT,
 @ID_CLINICA_ATENDIMENTO INT,
 @ID_PROCEDIMENTO INT,
 @CM_PROCEDIMENTO VARCHAR(8000)
)
AS
BEGIN
  IF EXISTS(SELECT * FROM TB_CLINICA_PROCEDIMENTO WHERE ID_CLINICA_ATENDIMENTO = @ID_CLINICA_ATENDIMENTO AND ID_PROCEDIMENTO = @ID_PROCEDIMENTO)
	  UPDATE TB_CLINICA_PROCEDIMENTO
		 SET CM_PROCEDIMENTO = @CM_PROCEDIMENTO
		  WHERE ID_CLINICA_ATENDIMENTO = @ID_CLINICA_ATENDIMENTO
			  AND ID_PROCEDIMENTO = @ID_PROCEDIMENTO
	ELSE
	  INSERT INTO TB_CLINICA_PROCEDIMENTO
		(ID_CLINICA_ATENDIMENTO, ID_PROCEDIMENTO, CM_PROCEDIMENTO)
		VALUES
		(@ID_CLINICA_ATENDIMENTO, @ID_PROCEDIMENTO, @CM_PROCEDIMENTO)
END
GO
ALTER PROCEDURE [dbo].[SP_ORCAMENTO_CLIENTE_PROCEDIMENTO_CAD]
(
 @SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO INT,
 @ID_ORCAMENTO_CLIENTE INT,
 @SQ_CLINICA_PROCEDIMENTO INT,
 @ID_PROCEDIMENTO INT,
 @ID_PESSOA_PROFISSIONAL INT,
 @VL_ORCADO MONEY
)
AS
BEGIN
  IF ISNULL(@SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO, 0) = 0
		INSERT INTO TB_ORCAMENTO_CLIENTE_PROCEDIMENTO
		(ID_ORCAMENTO_CLIENTE,ID_PROCEDIMENTO,ID_PESSOA_PROFISSIONAL,VL_ORCADO)
     VALUES
		(@ID_ORCAMENTO_CLIENTE,@ID_PROCEDIMENTO,@ID_PESSOA_PROFISSIONAL,@VL_ORCADO)
	ELSE
	  UPDATE TB_ORCAMENTO_CLIENTE_PROCEDIMENTO
		 SET ID_ORCAMENTO_CLIENTE=@ID_ORCAMENTO_CLIENTE,
				 ID_PROCEDIMENTO=@ID_PROCEDIMENTO,
				 ID_PESSOA_PROFISSIONAL=@ID_PESSOA_PROFISSIONAL,
				 VL_ORCADO=@VL_ORCADO
		 WHERE SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO = @SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO

	IF ISNULL(@SQ_CLINICA_PROCEDIMENTO, 0) = 0
	  UPDATE TB_CLINICA_PROCEDIMENTO
		 SET ID_OPT_STATUS = 781 /* Orçado */
		 WHERE SQ_CLINICA_PROCEDIMENTO = @SQ_CLINICA_PROCEDIMENTO
END
GO
ALTER TABLE TB_CLINICA_ATENDIMENTO
 ADD CD_CLINICA_ATENDIMENTO VARCHAR(10)
GO
ALTER TABLE TB_EMPRESA
 ADD CD_CLINICA_ATENDIMENTO VARCHAR(10)
GO
UPDATE BNC SET CD_CLINICA_ATENDIMENTO = X.COD
 FROM TB_CLINICA_ATENDIMENTO BNC
  INNER JOIN (SELECT 'CA' + REPLACE(RIGHT(SPACE(10) + CAST(ROW_NUMBER() OVER(ORDER BY SQ_CLINICA_ATENDIMENTO) AS VARCHAR(10)), 6), ' ', '0') COD, *
               FROM TB_CLINICA_ATENDIMENTO) X ON X.SQ_CLINICA_ATENDIMENTO = BNC.SQ_CLINICA_ATENDIMENTO
GO
UPDATE TB_EMPRESA SET CD_CLINICA_ATENDIMENTO = (SELECT MAX(CD_CLINICA_ATENDIMENTO) FROM TB_CLINICA_ATENDIMENTO)
GO
CREATE VIEW VW_CLINICA_PROCEDIMENTO_PENDENTE
AS
SELECT CLPCD.SQ_CLINICA_PROCEDIMENTO,
			 CLPCD.ID_PROCEDIMENTO,
			 CLATD.ID_PESSOA,
			 CLPCD.ID_OPT_STATUS,
			 AGEND.ID_CONVENIO,
			 CLATD.ID_PESSOA_PROFISSIONAL,
			 CLATD.CD_CLINICA_ATENDIMENTO,
			 PESSO_PROFI.NO_PESSOA NO_PESSOA_PROFISSIONAL,
       PROCE.NO_PROCEDIMENTO
 FROM TB_CLINICA_PROCEDIMENTO	CLPCD
  INNER JOIN TB_CLINICA_ATENDIMENTO	CLATD ON CLATD.SQ_CLINICA_ATENDIMENTO = CLPCD.ID_CLINICA_ATENDIMENTO
	 LEFT JOIN TB_AGENDAMENTO AGEND ON AGEND.SQ_AGENDAMENTO = CLATD.ID_AGENDAMENTO
	INNER JOIN TB_PROCEDIMENTO PROCE ON PROCE.SQ_PROCEDIMENTO = CLPCD.ID_PROCEDIMENTO
	INNER JOIN TB_PESSOA PESSO_PROFI ON PESSO_PROFI.SQ_PESSOA = CLATD.ID_PESSOA_PROFISSIONAL
 WHERE CLPCD.ID_OPT_STATUS = 780
GO
CREATE FUNCTION [dbo].[FC_EMPRESA_NOVO_CD_CLINICA_ATENDIMENTO]
(
 @ID_EMPRESA INT
)
RETURNS VARCHAR(10)
AS
BEGIN
  DECLARE @NOVO_CD_CLINICA_ATENDIMENTO VARCHAR(10)

  SELECT @NOVO_CD_CLINICA_ATENDIMENTO = 'CA' + REPLACE(RIGHT(SPACE(10) + CAST(SUBSTRING(MAX(ISNULL(CD_CLINICA_ATENDIMENTO, '00')), 3, 6) + 1 AS VARCHAR(10)), 6), ' ', '0')
   FROM TB_EMPRESA

  RETURN @NOVO_CD_CLINICA_ATENDIMENTO
END
GO
ALTER PROCEDURE [dbo].[SP_CLINICA_ATENDIMENTO_CAD]
(
 @SQ_CLINICA_ATENDIMENTO INT OUT,
 @ID_EMPRESA INT,
 @ID_PESSOA INT,
 @ID_PESSOA_PROFISSIONAL INT,
 @ID_PROCEDIMENTO INT,
 @ID_AGENDAMENTO INT,
 @ID_CONSULTORIO INT,
 @ID_OPT_STATUS INT,
 @DH_CLINICA_ATENDIMENTO DATETIME,
 @DS_CLINICA_ATENDIMENTO TEXT
)
AS
BEGIN
  IF ISNULL(@SQ_CLINICA_ATENDIMENTO, 0) = 0
	  BEGIN
		  DECLARE @CD_CLINICA_ATENDIMENTO VARCHAR(10)

			SELECT @CD_CLINICA_ATENDIMENTO = dbo.FC_EMPRESA_NOVO_CD_CLINICA_ATENDIMENTO(@ID_EMPRESA)

			UPDATE TB_EMPRESA SET CD_CLINICA_ATENDIMENTO = @CD_CLINICA_ATENDIMENTO WHERE ID_EMPRESA = @ID_EMPRESA

		  INSERT INTO TB_CLINICA_ATENDIMENTO
			(ID_EMPRESA, ID_PESSOA, ID_PESSOA_PROFISSIONAL, ID_AGENDAMENTO, ID_PROCEDIMENTO, ID_CONSULTORIO, ID_OPT_STATUS, CD_CLINICA_ATENDIMENTO, DH_CLINICA_ATENDIMENTO, DS_CLINICA_ATENDIMENTO)
			VALUES
			(@ID_EMPRESA, @ID_PESSOA, @ID_PESSOA_PROFISSIONAL, @ID_AGENDAMENTO, @ID_PROCEDIMENTO, @ID_CONSULTORIO, @ID_OPT_STATUS, @CD_CLINICA_ATENDIMENTO, @DH_CLINICA_ATENDIMENTO, @DS_CLINICA_ATENDIMENTO)

		  SET @SQ_CLINICA_ATENDIMENTO = @@IDENTITY
		END
	ELSE
		UPDATE TB_CLINICA_ATENDIMENTO
		 SET ID_EMPRESA = @ID_EMPRESA,
				 ID_PESSOA = @ID_PESSOA,
				 ID_PESSOA_PROFISSIONAL = @ID_PESSOA_PROFISSIONAL,
			   ID_AGENDAMENTO = @ID_AGENDAMENTO,
				 ID_PROCEDIMENTO = @ID_PROCEDIMENTO,
				 ID_CONSULTORIO = @ID_CONSULTORIO,
				 ID_OPT_STATUS = @ID_OPT_STATUS,
				 DH_CLINICA_ATENDIMENTO = @DH_CLINICA_ATENDIMENTO,
				 DS_CLINICA_ATENDIMENTO = @DS_CLINICA_ATENDIMENTO
		 WHERE SQ_CLINICA_ATENDIMENTO = @SQ_CLINICA_ATENDIMENTO

	IF @ID_OPT_STATUS = 51 AND ISNULL(@ID_AGENDAMENTO, 0) <> 0
	  UPDATE TB_AGENDAMENTO
		 SET ID_OPT_STATUS = 41
		 WHERE SQ_AGENDAMENTO = @ID_AGENDAMENTO

	RETURN
END
GO
ALTER TABLE TB_CLINICA_VENDA_PROCEDIMENTO
 ADD ID_ORCAMENTO_CLIENTE_PROCEDIMENTO INT,
     ID_CLINICA_PROCEDIMENTO INT
GO
ALTER TABLE TB_CLINICA_VENDA_PROCEDIMENTO  WITH CHECK ADD  CONSTRAINT FK_CVDPC_OCPRC FOREIGN KEY(ID_ORCAMENTO_CLIENTE_PROCEDIMENTO)
 REFERENCES TB_ORCAMENTO_CLIENTE_PROCEDIMENTO (SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO)
GO
ALTER TABLE TB_CLINICA_VENDA_PROCEDIMENTO  WITH CHECK ADD  CONSTRAINT FK_CVDPC_CLPCD FOREIGN KEY(ID_CLINICA_PROCEDIMENTO)
 REFERENCES TB_CLINICA_PROCEDIMENTO (SQ_CLINICA_PROCEDIMENTO)
GO
ALTER PROCEDURE [dbo].[SP_CLINICA_VENDA_PROCEDIMENTO_CAD]
(
 @SQ_CLINICA_VENDA_PROCEDIMENTO INT,
 @ID_CLINICA_VENDA INT,
 @ID_PROCEDIMENTO INT,
 @ID_PESSOA_PROFISSIONAL INT,
 @ID_ORCAMENTO_CLIENTE_PROCEDIMENTO INT,
 @ID_CLINICA_PROCEDIMENTO INT,
 @VL_PROCEDIMENTO MONEY,
 @VL_REPASSE MONEY,
 @VL_DESCONTO MONEY,
 @DT_PREVISAO_FATURAMENTO DATE
)
AS
BEGIN
  DECLARE @ID_ORCAMENTO_CLIENTE INT

	IF @ID_ORCAMENTO_CLIENTE_PROCEDIMENTO = 0
	 SET @ID_ORCAMENTO_CLIENTE_PROCEDIMENTO = NULL

	IF @ID_CLINICA_PROCEDIMENTO = 0
	 SET @ID_CLINICA_PROCEDIMENTO = NULL
  
	IF ISNULL(@SQ_CLINICA_VENDA_PROCEDIMENTO, 0)  = 0
	  INSERT INTO TB_CLINICA_VENDA_PROCEDIMENTO
		(ID_CLINICA_VENDA, ID_PROCEDIMENTO, ID_PESSOA_PROFISSIONAL, ID_CLINICA_PROCEDIMENTO, ID_ORCAMENTO_CLIENTE_PROCEDIMENTO,
		 ID_OPT_STATUS, VL_PROCEDIMENTO, VL_REPASSE, VL_DESCONTO,DT_PREVISAO_FATURAMENTO)
		VALUES
		(@ID_CLINICA_VENDA, @ID_PROCEDIMENTO, @ID_PESSOA_PROFISSIONAL, @ID_CLINICA_PROCEDIMENTO, @ID_ORCAMENTO_CLIENTE_PROCEDIMENTO,
		 737  /* Lançado */, @VL_PROCEDIMENTO, @VL_REPASSE, @VL_DESCONTO,@DT_PREVISAO_FATURAMENTO)
	ELSE
	 UPDATE TB_CLINICA_VENDA_PROCEDIMENTO
	  SET ID_CLINICA_VENDA=@ID_CLINICA_VENDA,
				ID_PROCEDIMENTO=@ID_PROCEDIMENTO,
				ID_PESSOA_PROFISSIONAL=@ID_PESSOA_PROFISSIONAL,
				VL_PROCEDIMENTO=@VL_PROCEDIMENTO,
				VL_REPASSE = @VL_REPASSE,
				VL_DESCONTO=@VL_DESCONTO,
				DT_PREVISAO_FATURAMENTO=@DT_PREVISAO_FATURAMENTO
	  WHERE SQ_CLINICA_VENDA_PROCEDIMENTO = @SQ_CLINICA_VENDA_PROCEDIMENTO

	IF ISNULL(@ID_ORCAMENTO_CLIENTE_PROCEDIMENTO, 0) <> 0
	  BEGIN
			UPDATE TB_ORCAMENTO_CLIENTE_PROCEDIMENTO
			 SET ID_OPT_STATUS = 735 /* Vendido */
			 WHERE SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO = @ID_ORCAMENTO_CLIENTE_PROCEDIMENTO

			SELECT @ID_ORCAMENTO_CLIENTE = ID_ORCAMENTO_CLIENTE
			 FROM TB_ORCAMENTO_CLIENTE_PROCEDIMENTO
			 WHERE SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO = @ID_ORCAMENTO_CLIENTE_PROCEDIMENTO

			EXEC SP_ORCAMENTO_CLIENTE_STATUS @ID_ORCAMENTO_CLIENTE
		END

	IF ISNULL(@ID_CLINICA_PROCEDIMENTO, 0) > 0
	  UPDATE TB_CLINICA_PROCEDIMENTO
		 SET ID_OPT_STATUS = 787 /* Vendido */
		 WHERE SQ_CLINICA_PROCEDIMENTO = @ID_CLINICA_PROCEDIMENTO
END