SELECT CLVND.SQ_CLINICA_VENDA,IIF(CLVND.ID_ATENDIMENTO IS NULL,IIF(CLVND.ID_AGENDAMENTO IS NULL,IIF(CLVND.ID_ORCAMENTO_CLIENTE IS NULL, 0, 1), 2), -1) NR_ORIGEM_VENDA,
			 CLVND.CD_CLINICA_VENDA,EMPRE.NO_PESSOA,PESSO.NO_PESSOA,INDIC.NO_INDICACAO,ISNULL(ATEND.CD_ATENDIMENTO, 
			 ISNULL(AGEND.CD_AGENDAMENTO, OCCLI.CD_ORCAMENTO_CLIENTE)) CD_ORIGEM_VENDA,CLVND.DH_VENDA,CVDPC.QT_CLINICA_VENDA_PROCEDIMENTO,CVDPC.VL_CLINICA_VENDA_PROCEDIMENTO,
			 CVDPC.VL_DESCONTO,CLVND.DH_CANCELAR,CLVND.CM_OBSERVACAO_CANCELAMENTO,AGEND.ID_OPT_STATUS
 FROM TB_CLINICA_VENDA CLVND
  INNER JOIN TB_PESSOA PESSO ON PESSO.SQ_PESSOA = CLVND.ID_PESSOA
	INNER JOIN TB_PESSOA EMPRE ON EMPRE.SQ_PESSOA = CLVND.ID_EMPRESA
	INNER JOIN (SELECT ID_CLINICA_VENDA,COUNT(*) QT_CLINICA_VENDA_PROCEDIMENTO,SUM(ISNULL(VL_PROCEDIMENTO, 0)) VL_CLINICA_VENDA_PROCEDIMENTO,SUM(ISNULL(VL_DESCONTO, 0)) VL_DESCONTO
	FROM TB_CLINICA_VENDA_PROCEDIMENTO GROUP BY ID_CLINICA_VENDA) CVDPC ON CVDPC.ID_CLINICA_VENDA = CLVND.SQ_CLINICA_VENDA LEFT JOIN TB_INDICACAO INDIC ON INDIC.SQ_INDICACAO 
= CLVND.ID_INDICACAO LEFT JOIN TB_ATENDIMENTO ATEND ON ATEND.SQ_ATENDIMENTO = CLVND.ID_ATENDIMENTO LEFT JOIN TB_AGENDAMENTO AGEND ON AGEND.SQ_AGENDAMENTO = CLVND.ID_AGENDAMENTO
LEFT JOIN TB_ORCAMENTO_CLIENTE OCCLI ON OCCLI.SQ_ORCAMENTO_CLIENTE = CLVND.ID_ORCAMENTO_CLIENTE WHERE CLVND.ID_EMPRESA = 2 AND  CAST(CLVND.DH_VENDA AS DATE) >= '09/11/2020'
AND  CAST(CLVND.DH_VENDA AS DATE) <= '20/11/2020'