Use Cli28Julho
GO
CREATE TABLE TB_VACINA
(
 SQ_VACINA INT IDENTITY(1, 1) NOT NULL,
 NO_VACINA VARCHAR(200) NOT NULL,
 DS_SERVENTIA VARCHAR(2000),
 DS_INICIO VARCHAR(200),
 DS_TERMINO VARCHAR(200),
 DS_APRAZAMENTO VARCHAR(200)
)
GO
ALTER TABLE TB_VACINA ADD CONSTRAINT PK_VACINA
 PRIMARY KEY CLUSTERED (SQ_VACINA)
GO
ALTER TABLE TB_CONSULTORIO
 ADD ID_EMPRESA INT NOT NULL,
		 NO_CONSULTORIO VARCHAR(100) NOT NULL
GO
ALTER TABLE TB_CONSULTORIO
 ADD IC_ATIVO CHAR(1) NOT NULL DEFAULT 'S'
GO
ALTER TABLE TB_CONSULTORIO WITH CHECK ADD CONSTRAINT FK_CSLTR_EMPRE FOREIGN KEY(ID_EMPRESA)
 REFERENCES TB_EMPRESA (ID_EMPRESA)
GO
CREATE TABLE TB_CLINICA_ATENDIMENTO
(
 SQ_CLINICA_ATENDIMENTO INT IDENTITY(1, 1) NOT NULL,
 ID_EMPRESA INT NOT NULL,
 ID_PESSOA INT NOT NULL,
 ID_PESSOA_PROFISSIONAL INT NOT NULL,
 ID_PROCEDIMENTO INT NOT NULL,
 ID_AGENDAMENTO INT,
 ID_CONSULTORIO INT,
 DH_CLINICA_ATENDIMENTO DATETIME NOT NULL,
 DS_CLINICA_ATENDIMENTO TEXT
)
GO
ALTER TABLE TB_CLINICA_ATENDIMENTO ADD CONSTRAINT PK_CLINICA_ATENDIMENTO
 PRIMARY KEY CLUSTERED (SQ_CLINICA_ATENDIMENTO)
GO
ALTER TABLE TB_CLINICA_ATENDIMENTO WITH CHECK ADD CONSTRAINT FK_CLATD_EMPRE FOREIGN KEY(ID_EMPRESA)
 REFERENCES TB_EMPRESA (ID_EMPRESA)
GO
ALTER TABLE TB_CLINICA_ATENDIMENTO WITH CHECK ADD CONSTRAINT FK_CLATD_PESSO FOREIGN KEY(ID_PESSOA)
 REFERENCES TB_PESSOA (SQ_PESSOA)
GO
ALTER TABLE TB_CLINICA_ATENDIMENTO WITH CHECK ADD CONSTRAINT FK_CLATD_PESSO_PROFI FOREIGN KEY(ID_PESSOA_PROFISSIONAL)
 REFERENCES TB_PESSOA (SQ_PESSOA)
GO
ALTER TABLE TB_CLINICA_ATENDIMENTO WITH CHECK ADD CONSTRAINT FK_CLATD_AGEND FOREIGN KEY(ID_AGENDAMENTO)
 REFERENCES TB_AGENDAMENTO (SQ_AGENDAMENTO)
GO
ALTER TABLE TB_CLINICA_ATENDIMENTO WITH CHECK ADD CONSTRAINT FK_CLATD_PROCE FOREIGN KEY(ID_PROCEDIMENTO)
 REFERENCES TB_PROCEDIMENTO (SQ_PROCEDIMENTO)
GO
ALTER TABLE TB_CLINICA_ATENDIMENTO WITH CHECK ADD CONSTRAINT FK_CLATD_CSLTR FOREIGN KEY(ID_CONSULTORIO)
 REFERENCES TB_CONSULTORIO (SQ_CONSULTORIO)
GO
CREATE TABLE TB_PESSOA_ATESTADO
(
 SQ_PESSOA_ATESTADO INT IDENTITY(1, 1) NOT NULL,
 ID_EMPRESA INT NOT NULL,
 ID_PESSOA INT NOT NULL,
 ID_PESSOA_PROFISSIONAL INT NOT NULL,
 ID_OPT_TIPO_ATESTADO INT NOT NULL,
 ID_AGENDAMENTO INT,
 ID_CLINICA_ATENDIMENTO INT,
 DH_PESSOA_ATESTADO DATETIME NOT NULL,
 NR_DIAS_REPOUSO INT NOT NULL,
 CD_CID VARCHAR(10) NOT NULL,
 DS_ACOMPANHANTE VARCHAR(200) NOT NULL,
)
GO
ALTER TABLE TB_PESSOA_ATESTADO ADD CONSTRAINT PK_PESSOA_ATESTADO
 PRIMARY KEY CLUSTERED (SQ_PESSOA_ATESTADO)
GO
ALTER TABLE TB_PESSOA_ATESTADO WITH CHECK ADD CONSTRAINT FK_PSATT_EMPRE FOREIGN KEY(ID_EMPRESA)
 REFERENCES TB_EMPRESA (ID_EMPRESA)
GO
ALTER TABLE TB_PESSOA_ATESTADO WITH CHECK ADD CONSTRAINT FK_PSATT_PESSO FOREIGN KEY(ID_PESSOA)
 REFERENCES TB_PESSOA (SQ_PESSOA)
GO
ALTER TABLE TB_PESSOA_ATESTADO WITH CHECK ADD CONSTRAINT FK_PSATT_PESSO_PROFI FOREIGN KEY(ID_PESSOA_PROFISSIONAL)
 REFERENCES TB_PESSOA (SQ_PESSOA)
GO
ALTER TABLE TB_PESSOA_ATESTADO WITH CHECK ADD CONSTRAINT FK_PSATT_OPCAO_TPATD FOREIGN KEY(ID_OPT_TIPO_ATESTADO)
 REFERENCES TB_OPCAO (SQ_OPCAO)
GO
ALTER TABLE TB_PESSOA_ATESTADO WITH CHECK ADD CONSTRAINT FK_PSATT_AGEND FOREIGN KEY(ID_AGENDAMENTO)
 REFERENCES TB_AGENDAMENTO (SQ_AGENDAMENTO)
GO
ALTER TABLE TB_PESSOA_ATESTADO WITH CHECK ADD CONSTRAINT FK_PSATT_CLATD FOREIGN KEY(ID_CLINICA_ATENDIMENTO)
 REFERENCES TB_CLINICA_ATENDIMENTO (SQ_CLINICA_ATENDIMENTO)
GO
CREATE TABLE TB_PESSOA_ANTECEDENTES
(
 SQ_PESSOA_ANTECEDENTES INT IDENTITY(1, 1) NOT NULL,
 ID_PESSOA INT NOT NULL,
 ID_PESSOA_PROFISSIONAL INT NOT NULL,
 ID_OPT_TIPO_ANTECEDENTES INT NOT NULL,
 DT_LANCAMENTO DATE NOT NULL,
 DS_ANTECEDENTES VARCHAR(8000) NOT NULL
)
GO
ALTER TABLE TB_PESSOA_ANTECEDENTES ADD CONSTRAINT PK_PESSOA_ANTECEDENTES
 PRIMARY KEY CLUSTERED (SQ_PESSOA_ANTECEDENTES)
GO
CREATE UNIQUE INDEX UK_PESSOA_ANTECEDENTES ON TB_PESSOA_ANTECEDENTES (ID_PESSOA, ID_PESSOA_PROFISSIONAL, ID_OPT_TIPO_ANTECEDENTES)
GO
ALTER TABLE TB_PESSOA_ANTECEDENTES WITH CHECK ADD CONSTRAINT FK_PSACD_PESSO FOREIGN KEY(ID_PESSOA)
 REFERENCES TB_PESSOA (SQ_PESSOA)
GO
ALTER TABLE TB_PESSOA_ANTECEDENTES WITH CHECK ADD CONSTRAINT FK_PSACD_PESSO_PROFI FOREIGN KEY(ID_PESSOA_PROFISSIONAL)
 REFERENCES TB_PESSOA (SQ_PESSOA)
GO
ALTER TABLE TB_PESSOA_ANTECEDENTES WITH CHECK ADD CONSTRAINT FK_PSACD_OPCAO_TPATD FOREIGN KEY(ID_OPT_TIPO_ANTECEDENTES)
 REFERENCES TB_OPCAO (SQ_OPCAO)
 GO
CREATE TABLE TB_CLINICA_RECEITUARIO
(
 SQ_CLINICA_RECEITUARIO INT IDENTITY(1, 1) NOT NULL,
 ID_EMPRESA INT NOT NULL,
 ID_PESSOA INT NOT NULL,
 ID_PESSOA_PROFISSIONAL INT NOT NULL,
 ID_CLINICA_ATENDIMENTO INT,
 DT_LANCAMENTO DATE NOT NULL,
 DS_RECEITUARIO TEXT NOT NULL
)
GO
ALTER TABLE TB_CLINICA_RECEITUARIO ADD CONSTRAINT PK_CLINICA_RECEITUARIO
 PRIMARY KEY CLUSTERED (SQ_CLINICA_RECEITUARIO)
GO
ALTER TABLE TB_CLINICA_RECEITUARIO WITH CHECK ADD CONSTRAINT FK_CLRCT_EMPRE FOREIGN KEY(ID_EMPRESA)
 REFERENCES TB_EMPRESA (ID_EMPRESA)
GO
ALTER TABLE TB_CLINICA_RECEITUARIO WITH CHECK ADD CONSTRAINT FK_CLRCT_PESSO FOREIGN KEY(ID_PESSOA)
 REFERENCES TB_PESSOA (SQ_PESSOA)
GO
ALTER TABLE TB_CLINICA_RECEITUARIO WITH CHECK ADD CONSTRAINT FK_CLRCT_PESSO_PROFI FOREIGN KEY(ID_PESSOA_PROFISSIONAL)
 REFERENCES TB_PESSOA (SQ_PESSOA)
GO
ALTER TABLE TB_CLINICA_RECEITUARIO WITH CHECK ADD CONSTRAINT FK_CLRCT_CLATD FOREIGN KEY(ID_CLINICA_ATENDIMENTO)
 REFERENCES TB_CLINICA_ATENDIMENTO (SQ_CLINICA_ATENDIMENTO)
GO
CREATE TABLE TB_CLINICA_RELATORIO
(
 SQ_CLINICA_RELATORIO INT IDENTITY(1, 1) NOT NULL,
 ID_EMPRESA INT NOT NULL,
 ID_PESSOA INT NOT NULL,
 ID_PESSOA_PROFISSIONAL INT NOT NULL,
 ID_CLINICA_ATENDIMENTO INT,
 DH_LANCAMENTO DATETIME NOT NULL,
 DS_RELATORIO TEXT NOT NULL
)
GO
ALTER TABLE TB_CLINICA_RELATORIO ADD CONSTRAINT PK_CLINICA_RELATORIO
 PRIMARY KEY CLUSTERED (SQ_CLINICA_RELATORIO)
GO
ALTER TABLE TB_CLINICA_RELATORIO WITH CHECK ADD CONSTRAINT FK_CLREL_EMPRE FOREIGN KEY(ID_EMPRESA)
 REFERENCES TB_EMPRESA (ID_EMPRESA)
GO
ALTER TABLE TB_CLINICA_RELATORIO WITH CHECK ADD CONSTRAINT FK_CLREL_PESSO FOREIGN KEY(ID_PESSOA)
 REFERENCES TB_PESSOA (SQ_PESSOA)
GO
ALTER TABLE TB_CLINICA_RELATORIO WITH CHECK ADD CONSTRAINT FK_CLREL_PESSO_PROFI FOREIGN KEY(ID_PESSOA_PROFISSIONAL)
 REFERENCES TB_PESSOA (SQ_PESSOA)
GO
ALTER TABLE TB_CLINICA_RELATORIO WITH CHECK ADD CONSTRAINT FK_CLREL_CLATD FOREIGN KEY(ID_CLINICA_ATENDIMENTO)
 REFERENCES TB_CLINICA_ATENDIMENTO (SQ_CLINICA_ATENDIMENTO)
GO
CREATE TABLE TB_CLINICA_EXAME_CITOLOGICO
(
 SQ_CLINICA_EXAME_CITOLOGICO INT IDENTITY(1, 1) NOT NULL,
 ID_CLINICA_ATENDIMENTO INT NOT NULL,
 DS_TIPO VARCHAR(200),
 DS_MEDICO_EXTERNO VARCHAR(200),
 DS_COLETA VARCHAR(100),
 DS_UM VARCHAR(100),
 DS_FILHOS VARCHAR(100),
 DS_ABORTO VARCHAR(100),
 DS_PARA VARCHAR(100),
 DS_LOCAL_COLETA VARCHAR(100),
 DS_ACHADOS_COLPOSCOPICOS VARCHAR(100)
)
GO
ALTER TABLE TB_CLINICA_EXAME_CITOLOGICO ADD CONSTRAINT PK_CLINICA_EXAME_CITOLOGICO
 PRIMARY KEY CLUSTERED (SQ_CLINICA_EXAME_CITOLOGICO)
GO
ALTER TABLE TB_CLINICA_EXAME_CITOLOGICO WITH CHECK ADD CONSTRAINT FK_CLEXC_CLATD FOREIGN KEY(ID_CLINICA_ATENDIMENTO)
 REFERENCES TB_CLINICA_ATENDIMENTO (SQ_CLINICA_ATENDIMENTO)
GO
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (763, 120, 'Botão - Atestados', 'S')
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (764, 120, 'Botão - Exames', 'S')
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (765, 120, 'Botão - Imprimir', 'S')
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (766, 120, 'Botão - Listar', 'S')
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (767, 120, 'Botão - Outras Consultas', 'S')
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (768, 120, 'Botão - Paciente - Cadastro', 'S')
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (769, 120, 'Botão - Receituário', 'S')
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (770, 120, 'Botão - Relatórios', 'S')
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (771, 120, 'Botão - Salvar', 'S')
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (772, 120, 'Botão - Vacinas', 'S')
GO
INSERT INTO TB_CONFIG_TELA (ID_TELA, DS_PATH_IMAGEM_FUNDO) VALUES (763, 'Formulários\Botao\BTN_Atestados_##.png')
INSERT INTO TB_CONFIG_TELA (ID_TELA, DS_PATH_IMAGEM_FUNDO) VALUES (764, 'Formulários\Botao\BTN_Exames_##.png')
INSERT INTO TB_CONFIG_TELA (ID_TELA, DS_PATH_IMAGEM_FUNDO) VALUES (765, 'Formulários\Botao\BTN_Imprimir_##.png')
INSERT INTO TB_CONFIG_TELA (ID_TELA, DS_PATH_IMAGEM_FUNDO) VALUES (766, 'Formulários\Botao\BTN_Listar_##.png')
INSERT INTO TB_CONFIG_TELA (ID_TELA, DS_PATH_IMAGEM_FUNDO) VALUES (767, 'Formulários\Botao\BTN_OutrasConsultas_##.png')
INSERT INTO TB_CONFIG_TELA (ID_TELA, DS_PATH_IMAGEM_FUNDO) VALUES (768, 'Formulários\Botao\BTN_PacienteCadastro_##.png')
INSERT INTO TB_CONFIG_TELA (ID_TELA, DS_PATH_IMAGEM_FUNDO) VALUES (769, 'Formulários\Botao\BTN_Receituario_##.png')
INSERT INTO TB_CONFIG_TELA (ID_TELA, DS_PATH_IMAGEM_FUNDO) VALUES (770, 'Formulários\Botao\BTN_Relatorios_##.png')
INSERT INTO TB_CONFIG_TELA (ID_TELA, DS_PATH_IMAGEM_FUNDO) VALUES (771, 'Formulários\Botao\BTN_Salvar_##.png')
INSERT INTO TB_CONFIG_TELA (ID_TELA, DS_PATH_IMAGEM_FUNDO) VALUES (772, 'Formulários\Botao\BTN_Vacinas_##.png')
GO
 ALTER TABLE TB_CLINICA_ATENDIMENTO
  ADD ID_STATUS INT NOT NULL
GO
ALTER TABLE TB_CLINICA_ATENDIMENTO WITH CHECK ADD CONSTRAINT FK_CLATD_OPCAO_STATU FOREIGN KEY(ID_STATUS)
 REFERENCES TB_OPCAO (SQ_OPCAO)
GO
CREATE PROCEDURE SP_CLINICA_ATENDIMENTO_CAD
(
 @SQ_CLINICA_ATENDIMENTO INT OUT,
 @ID_EMPRESA INT,
 @ID_PESSOA INT,
 @ID_PESSOA_PROFISSIONAL INT,
 @ID_PROCEDIMENTO INT,
 @ID_AGENDAMENTO INT,
 @ID_CONSULTORIO INT,
 @ID_STATUS INT,
 @DH_CLINICA_ATENDIMENTO DATETIME,
 @DS_CLINICA_ATENDIMENTO TEXT
)
AS
BEGIN
  IF ISNULL(@SQ_CLINICA_ATENDIMENTO, 0) = 0
	  BEGIN
		  INSERT INTO TB_CLINICA_ATENDIMENTO
			(ID_EMPRESA, ID_PESSOA, ID_PESSOA_PROFISSIONAL, ID_AGENDAMENTO, ID_PROCEDIMENTO, ID_CONSULTORIO, ID_STATUS, DH_CLINICA_ATENDIMENTO, DS_CLINICA_ATENDIMENTO)
			VALUES
			(@ID_EMPRESA, @ID_PESSOA, @ID_PESSOA_PROFISSIONAL, @ID_AGENDAMENTO, @ID_PROCEDIMENTO, @ID_CONSULTORIO, @ID_STATUS, @DH_CLINICA_ATENDIMENTO, @DS_CLINICA_ATENDIMENTO)

		  SET @SQ_CLINICA_ATENDIMENTO = @@IDENTITY
		END
	ELSE
		UPDATE TB_CLINICA_ATENDIMENTO
		 SET ID_EMPRESA = @ID_EMPRESA,
				 ID_PESSOA = @ID_PESSOA,
				 ID_PESSOA_PROFISSIONAL = @ID_PESSOA_PROFISSIONAL,
			   ID_AGENDAMENTO = @ID_AGENDAMENTO,
				 ID_PROCEDIMENTO = @ID_PROCEDIMENTO,
				 ID_CONSULTORIO = @ID_CONSULTORIO,
				 ID_STATUS = @ID_STATUS,
				 DH_CLINICA_ATENDIMENTO = @DH_CLINICA_ATENDIMENTO,
				 DS_CLINICA_ATENDIMENTO = @DS_CLINICA_ATENDIMENTO
		 WHERE SQ_CLINICA_ATENDIMENTO = @SQ_CLINICA_ATENDIMENTO

	RETURN
END
GO
ALTER TABLE TB_PESSOA_ATESTADO
 ADD DS_ATESTADO TEXT NOT NULL
GO
CREATE PROCEDURE SP_PESSOA_ATESTADO_CAD
(
 @SQ_PESSOA_ATESTADO INT OUT,
 @ID_EMPRESA INT,
 @ID_PESSOA INT,
 @ID_PESSOA_PROFISSIONAL INT,
 @ID_OPT_TIPO_ATESTADO INT,
 @ID_AGENDAMENTO INT,
 @ID_CLINICA_ATENDIMENTO INT,
 @DH_PESSOA_ATESTADO DATETIME ,
 @NR_DIAS_REPOUSO INT,
 @CD_CID VARCHAR(10),
 @DS_ACOMPANHANTE VARCHAR(200),
 @DS_ATESTADO TEXT
)
AS
BEGIN
  IF @ID_AGENDAMENTO = 0
	  SET @ID_AGENDAMENTO = NULL

  IF @ID_CLINICA_ATENDIMENTO = 0
	  SET @ID_CLINICA_ATENDIMENTO = NULL

  IF ISNULL(@SQ_PESSOA_ATESTADO, 0) = 0
		BEGIN
			INSERT INTO TB_PESSOA_ATESTADO
			(ID_EMPRESA, ID_PESSOA, ID_PESSOA_PROFISSIONAL, ID_OPT_TIPO_ATESTADO, ID_AGENDAMENTO, ID_CLINICA_ATENDIMENTO, DH_PESSOA_ATESTADO,
			 NR_DIAS_REPOUSO, CD_CID, DS_ACOMPANHANTE, DS_ATESTADO)
			VALUES
			(@ID_EMPRESA, @ID_PESSOA, @ID_PESSOA_PROFISSIONAL, @ID_OPT_TIPO_ATESTADO, @ID_AGENDAMENTO, @ID_CLINICA_ATENDIMENTO, @DH_PESSOA_ATESTADO,
			 @NR_DIAS_REPOUSO, @CD_CID, @DS_ACOMPANHANTE, @DS_ATESTADO)

			SET @SQ_PESSOA_ATESTADO = @@IDENTITY
		END
	ELSE
	  UPDATE TB_PESSOA_ATESTADO
		 SET ID_EMPRESA = @ID_EMPRESA,
				 ID_PESSOA = @ID_PESSOA,
				 ID_PESSOA_PROFISSIONAL = @ID_PESSOA_PROFISSIONAL,
				 ID_OPT_TIPO_ATESTADO = @ID_OPT_TIPO_ATESTADO,
				 ID_AGENDAMENTO = @ID_AGENDAMENTO,
				 ID_CLINICA_ATENDIMENTO = @ID_CLINICA_ATENDIMENTO,
				 DH_PESSOA_ATESTADO = @DH_PESSOA_ATESTADO,
			   NR_DIAS_REPOUSO = @NR_DIAS_REPOUSO,
				 CD_CID = @CD_CID,
				 DS_ACOMPANHANTE = @DS_ACOMPANHANTE,
				 DS_ATESTADO = @DS_ATESTADO
	 WHERE SQ_PESSOA_ATESTADO = @SQ_PESSOA_ATESTADO
END
GO
INSERT INTO TB_TIPO_OPCAO (SQ_TIPO_OPCAO, NO_TIPO_OPCAO) VALUES (121, 'Tipo de Atestado')
GO
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (773, 121, 'Médico', 'S')
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (774, 121, 'Comparecimento', 'S')
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (775, 121, 'Acomapanhante', 'S')
 GO
CREATE PROCEDURE SP_CLINICA_RECEITUARIO_CAD
(
 @SQ_CLINICA_RECEITUARIO INT OUT,
 @ID_EMPRESA INT,
 @ID_PESSOA INT,
 @ID_PESSOA_PROFISSIONAL INT,
 @ID_CLINICA_ATENDIMENTO INT,
 @DT_LANCAMENTO DATE,
 @DS_RECEITUARIO TEXT
)
AS
BEGIN
  IF @ID_CLINICA_ATENDIMENTO = 0
	  SET @ID_CLINICA_ATENDIMENTO = NULL

	IF ISNULL(@SQ_CLINICA_RECEITUARIO, 0) = 0
		BEGIN
			INSERT INTO TB_CLINICA_RECEITUARIO
			(ID_EMPRESA, ID_PESSOA, ID_PESSOA_PROFISSIONAL, ID_CLINICA_ATENDIMENTO, DT_LANCAMENTO, DS_RECEITUARIO)
			VALUES
			(@ID_EMPRESA, @ID_PESSOA, @ID_PESSOA_PROFISSIONAL, @ID_CLINICA_ATENDIMENTO, @DT_LANCAMENTO, @DS_RECEITUARIO)

			SET @SQ_CLINICA_RECEITUARIO = @@IDENTITY
		END
	ELSE
		UPDATE TB_CLINICA_RECEITUARIO
		 SET ID_EMPRESA = @ID_EMPRESA,
			   ID_PESSOA = @ID_PESSOA,
				 ID_PESSOA_PROFISSIONAL = @ID_PESSOA_PROFISSIONAL,
				 ID_CLINICA_ATENDIMENTO = @ID_CLINICA_ATENDIMENTO,
				 DT_LANCAMENTO = @DT_LANCAMENTO,
				 DS_RECEITUARIO = @DS_RECEITUARIO
		 WHERE SQ_CLINICA_RECEITUARIO = @SQ_CLINICA_RECEITUARIO

	RETURN
END
GO
CREATE PROCEDURE SP_PESSOA_ANTECEDENTES_CAD
(
 @SQ_PESSOA_ANTECEDENTES INT OUT,
 @ID_PESSOA INT,
 @ID_PESSOA_PROFISSIONAL INT,
 @ID_OPT_TIPO_ANTECEDENTES INT,
 @DT_LANCAMENTO DATE,
 @DS_ANTECEDENTES VARCHAR(8000)
)
AS
BEGIN
	IF ISNULL(@SQ_PESSOA_ANTECEDENTES, 0) = 0
		BEGIN
			INSERT INTO TB_PESSOA_ANTECEDENTES
			(ID_PESSOA, ID_PESSOA_PROFISSIONAL, ID_OPT_TIPO_ANTECEDENTES, DT_LANCAMENTO, DS_ANTECEDENTES)
			VALUES
			(@ID_PESSOA, @ID_PESSOA_PROFISSIONAL, @ID_OPT_TIPO_ANTECEDENTES, @DT_LANCAMENTO, @DS_ANTECEDENTES)

			SET @SQ_PESSOA_ANTECEDENTES = @@IDENTITY
		END
	ELSE
		UPDATE TB_PESSOA_ANTECEDENTES
		 SET ID_PESSOA = @ID_PESSOA,
				 ID_PESSOA_PROFISSIONAL = @ID_PESSOA_PROFISSIONAL,
				 ID_OPT_TIPO_ANTECEDENTES = @ID_OPT_TIPO_ANTECEDENTES,
				 DT_LANCAMENTO = @DT_LANCAMENTO,
				 DS_ANTECEDENTES = @DS_ANTECEDENTES
		 WHERE SQ_PESSOA_ANTECEDENTES = @SQ_PESSOA_ANTECEDENTES

	RETURN
END
GO
INSERT INTO TB_TIPO_OPCAO (SQ_TIPO_OPCAO, NO_TIPO_OPCAO) VALUES (122, 'Tipo de Atecedentes')
GO
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (776, 122, 'Pessoal', 'S')
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (777, 122, 'Familiar', 'S')
GO
ALTER TABLE TB_VACINA
 ADD IC_ATIVO CHAR(1) NOT NULL DEFAULT 'S'
GO
CREATE PROCEDURE SP_CLINICA_RELATORIO_CAD
(
 @SQ_CLINICA_RELATORIO INT OUT,
 @ID_EMPRESA INT,
 @ID_PESSOA INT,
 @ID_PESSOA_PROFISSIONAL INT,
 @ID_CLINICA_ATENDIMENTO INT,
 @DH_LANCAMENTO DATE,
 @DS_RELATORIO TEXT
)
AS
BEGIN
  IF ISNULL(@SQ_CLINICA_RELATORIO, 0) = 0
		BEGIN
			INSERT INTO TB_CLINICA_RELATORIO
			(ID_EMPRESA, ID_PESSOA, ID_PESSOA_PROFISSIONAL, ID_CLINICA_ATENDIMENTO, DH_LANCAMENTO, DS_RELATORIO)
			VALUES
			(@ID_EMPRESA, @ID_PESSOA, @ID_PESSOA_PROFISSIONAL, @ID_CLINICA_ATENDIMENTO, @DH_LANCAMENTO, @DS_RELATORIO)

			SET @SQ_CLINICA_RELATORIO = @@IDENTITY
		END
	ELSE
	  UPDATE TB_CLINICA_RELATORIO
		 SET ID_EMPRESA = @ID_EMPRESA,
			   ID_PESSOA = @ID_PESSOA,
				 ID_PESSOA_PROFISSIONAL = @ID_PESSOA_PROFISSIONAL,
				 ID_CLINICA_ATENDIMENTO = @ID_CLINICA_ATENDIMENTO,
				 DH_LANCAMENTO = @DH_LANCAMENTO,
				 DS_RELATORIO = @DS_RELATORIO
		 WHERE SQ_CLINICA_RELATORIO = @SQ_CLINICA_RELATORIO
END