ALTER TABLE TB_CONTAFINANCEIRA
 ADD DS_LOCALIZACAO VARCHAR(50)
GO
CREATE TABLE TB_CLINICA_SENHA
(
 SQ_CLINICA_SENHA INT NOT NULL IDENTITY(1, 1),
 ID_EMPRESA INT NOT NULL,
 DH_CLINICA_SENHA DATETIME NOT NULL DEFAULT GETDATE(),
 NR_CLINICA_SENHA INT NOT NULL,
 ID_CONTAFINANCEIRA INT,
 DH_CHAMADA DATETIME,
 ID_USUARIO INT
)
GO
CREATE TABLE TB_CLINICA_SENHA_CHAMADA
(
 SQ_CLINICA_SENHA_CHAMADA INT NOT NULL IDENTITY(1, 1),
 ID_CLINICA_SENHA INT NOT NULL,
 ID_CONTAFINANCEIRA INT NOT NULL,
 DH_CLINICA_SENHA_CHAMADA DATETIME NOT NULL DEFAULT GETDATE(),
 ID_USUARIO INT
)
GO
CREATE VIEW VW_CLINICA_SENHA_ULTIMA_SENHA_GERADA
AS
SELECT ID_EMPRESA, CAST(DH_CLINICA_SENHA AS DATE) DT_CLINICA_SENHA, ISNULL(MAX(NR_CLINICA_SENHA), 0) NR_CLINICA_SENHA
 FROM TB_CLINICA_SENHA
 GROUP BY ID_EMPRESA, CAST(DH_CLINICA_SENHA AS DATE)
GO
ALTER TABLE TB_CLINICA_SENHA
 ADD ID_EMPRESA_ESTACAO INT
GO
CREATE PROCEDURE SP_CLINICA_SENHA_INS
(
 @ID_EMPRESA INT
)
AS
BEGIN
  DECLARE @NR_CLINICA_SENHA INT

  SELECT @NR_CLINICA_SENHA = ISNULL(MAX(NR_CLINICA_SENHA), 0) + 1
   FROM TB_CLINICA_SENHA
   WHERE ID_EMPRESA = @ID_EMPRESA
	 AND CAST(DH_CLINICA_SENHA AS DATE) = CAST(GETDATE() AS DATE)

  INSERT INTO TB_CLINICA_SENHA
  (ID_EMPRESA, NR_CLINICA_SENHA)
  VALUES
  (@ID_EMPRESA, @NR_CLINICA_SENHA)

  RETURN @NR_CLINICA_SENHA
END
GO
ALTER TABLE TB_EMPRESA_ESTACAO
 ADD SQ_EMPRESA_ESTACAO INT NOT NULL IDENTITY(1,1)
GO
ALTER TABLE TB_EMPRESA_ESTACAO
 ADD ID_OPT_TIPOESTACAO INT NOT NULL
GO
INSERT INTO TB_TIPO_OPCAO (SQ_TIPO_OPCAO, NO_TIPO_OPCAO) VALUES (125, 'Tipo de Estação')
INSERT INTO TB_OPCAO(SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (816, 125, 'Estação de trabalho', 'S')
INSERT INTO TB_OPCAO(SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (817, 125, 'Estação de Geração de Senha', 'S')
GO
UPDATE TB_EMPRESA_ESTACAO SET ID_OPT_TIPOESTACAO = 816
GO
CREATE VIEW VW_EMPRESA_ESTACAO_GERACAO_SENHA
AS
SELECT SQ_EMPRESA_ESTACAO, NO_ESTACAO
 FROM TB_EMPRESA_ESTACAO
 WHERE ID_OPT_TIPOESTACAO = 817
GO
CREATE VIEW VW_CLINICA_SENHA_ULTIMA_SENHA_GERADA_HOJE
AS
SELECT ID_EMPRESA, NR_CLINICA_SENHA
 FROM VW_CLINICA_SENHA_ULTIMA_SENHA_GERADA
 WHERE DT_CLINICA_SENHA = CAST(GETDATE() AS DATE)
GO
CREATE FUNCTION [dbo].[FNC_STRZERO]
(
 -- Add the parameters for the function here
 @NUMERO int, @DIGITOS tinyint
)
RETURNS varchar(100)
AS
BEGIN
   RETURN REPLICATE('0',@DIGITOS-LEN(@NUMERO))+cast(@NUMERO as varchar(100));
END
GO
ALTER TABLE TB_CLINICA_SENHA
 ADD IC_IMPRESSA CHAR(1) DEFAULT 'N'
GO
CREATE PROCEDURE SP_CLINICA_SENHA_IMPRESSA_UPD
(
 @SQ_CLINICA_SENHA INT
)
AS
BEGIN
  UPDATE TB_CLINICA_SENHA
   SET IC_IMPRESSA = 'S'
   WHERE SQ_CLINICA_SENHA = @SQ_CLINICA_SENHA
END
GO
CREATE VIEW VW_CLINICA_SENHA_IMPRESSA_PENDENTE
AS
SELECT SQ_CLINICA_SENHA,
       ID_EMPRESA,
	   NR_CLINICA_SENHA
 FROM TB_CLINICA_SENHA CLSNH
 WHERE IC_IMPRESSA = 'N'
   AND CAST(DH_CLINICA_SENHA AS DATE) = CAST(GETDATE() AS DATE)
GO
ALTER TABLE TB_PESSOA_EMPRESA
 ADD IC_FUNCIONARIO_ACESSO_SISTEMACHAMADA CHAR(1) DEFAULT 'N'
GO
UPDATE TB_PESSOA_EMPRESA SET IC_FUNCIONARIO_ACESSO_SISTEMACHAMADA = 'N'
GO
ALTER PROCEDURE [dbo].[SP_PESSOA_EMPRESA_CAD]
(
 @ID_PESSOA INT,
 @ID_EMPRESA INT,
 @IC_CLIENTE CHAR(1),
 @IC_FABRICANTE CHAR(1),
 @IC_FORNECEDOR CHAR(1),
 @IC_FUNCIONARIO CHAR(1),
 @IC_PACIENTE CHAR(1),
 @IC_PROFISSIONAL CHAR(1),
 @IC_TRANSPORTADORA CHAR(1),
 @IC_VENDEDOR CHAR(1),
 @ID_CLIENTE_TABELAPRECO_PADRAO INT,
 @IC_CLIENTE_BLOQUEAR_VENDA CHAR(1),
 @IC_CLIENTE_ATIVO CHAR(1),
 @DS_CLIENTE_COMENTARIO VARCHAR(MAX),
 @IC_FABRICANTE_ATIVO CHAR(1),
 @IC_FORNECEDOR_ATIVO CHAR(1),
 @IC_FORNECEDOR_PRESTADORSERVICOMEDICO CHAR(1),
 @CM_FORNECEDOR_OBSERVACAO VARCHAR(MAX),
 @ID_FUNCIONARIO_TIPO_CARGO INT,
 @DT_FUNCIONARIO_ADMISSAO DATE,
 @DT_FUNCIONARIO_DESLIGAMENTO DATE,
 @IC_FUNCIONARIO_ATIVO CHAR(1),
 @IC_FUNCIONARIO_ACESSO_SISTEMACHAMADA CHAR(1),
 @DS_PACIENTE_COMENTARIO VARCHAR(MAX),
 @DS_PACIENTE_PENDENCIAS VARCHAR(MAX),
 @ID_PACIENTE_TIPO_PACIENTE INT,
 @IC_PACIENTE_ATIVO CHAR(1),
 @ID_PROFISSIONAL_CONSELHOPROFISSIONAL INT,
 @NR_PROFISSIONAL_CONSELHOPROFISSIONAL VARCHAR(20),
 @IC_PROFISSIONAL_ATIVO CHAR(1),
 @IC_PROFISSIONAL_SERVICO_INTERNO CHAR(1),
 @IC_PROFISSIONAL_RETEMIMPOSTO CHAR(1),
 @PC_PROFISSIONAL_RETEMIMPOSTO DECIMAL(18, 5),
 @IC_TRANSPORTADORA_ATIVO CHAR(1),
 @IC_VENDEDOR_ATIVO CHAR(1),
 @IC_INDICADOR CHAR(1),
 @IC_INDICADOR_ATIVO CHAR(1),
 @ID_INDICADOR_TIPOINDICADOR INT,
 @DT_INDICADOR_CADASTRO DATE
)
AS
BEGIN
  IF @IC_CLIENTE = 'N'
    BEGIN
      UPDATE TB_PESSOA_LIMITECREDITO
			 SET IC_BLOQUEADO = 'S'
       WHERE ID_PESSOA = @ID_PESSOA
         AND ID_EMPRESA = @ID_EMPRESA

			SET @IC_CLIENTE_BLOQUEAR_VENDA = 'S'
			SET @IC_CLIENTE_ATIVO = 'N'
    END

  IF @IC_FABRICANTE = 'N'
    SET @IC_FABRICANTE_ATIVO = 'N'

  IF @IC_FORNECEDOR = 'N'
    SET @IC_FORNECEDOR_ATIVO = 'N'

  IF @IC_FUNCIONARIO = 'N'
    BEGIN
			SET @IC_FUNCIONARIO_ATIVO = 'N'
		END

  IF @IC_PACIENTE = 'N'
    SET @IC_PACIENTE_ATIVO = 'N'

  IF @IC_PROFISSIONAL = 'N'
    SET @IC_PROFISSIONAL_ATIVO = 'N'

  IF @IC_TRANSPORTADORA = 'N'
    SET @IC_TRANSPORTADORA_ATIVO = 'N'

  IF @IC_VENDEDOR = 'N'
    SET @IC_VENDEDOR_ATIVO = 'N'
  
  UPDATE TB_PESSOA_EMPRESA
   SET IC_CLIENTE = @IC_CLIENTE,
			 IC_FABRICANTE = @IC_FABRICANTE,
			 IC_FORNECEDOR = @IC_FORNECEDOR,
			 IC_FUNCIONARIO = @IC_FUNCIONARIO,
			 IC_PACIENTE = @IC_PACIENTE,
			 IC_PROFISSIONAL = @IC_PROFISSIONAL,
			 IC_TRANSPORTADORA = @IC_TRANSPORTADORA,
			 IC_VENDEDOR = @IC_VENDEDOR,
			 ID_CLIENTE_TABELAPRECO_PADRAO = @ID_CLIENTE_TABELAPRECO_PADRAO,
			 IC_CLIENTE_BLOQUEAR_VENDA = @IC_CLIENTE_BLOQUEAR_VENDA,
			 IC_CLIENTE_ATIVO = @IC_CLIENTE_ATIVO,
			 DS_CLIENTE_COMENTARIO = @DS_CLIENTE_COMENTARIO,
			 IC_FABRICANTE_ATIVO = @IC_FABRICANTE_ATIVO,
			 IC_FORNECEDOR_ATIVO = @IC_FORNECEDOR_ATIVO,
			 IC_FORNECEDOR_PRESTADORSERVICOMEDICO = @IC_FORNECEDOR_PRESTADORSERVICOMEDICO,
			 CM_FORNECEDOR_OBSERVACAO = @CM_FORNECEDOR_OBSERVACAO,
			 ID_FUNCIONARIO_TIPO_CARGO = @ID_FUNCIONARIO_TIPO_CARGO,
			 DT_FUNCIONARIO_ADMISSAO = @DT_FUNCIONARIO_ADMISSAO,
			 DT_FUNCIONARIO_DESLIGAMENTO = @DT_FUNCIONARIO_DESLIGAMENTO,
			 IC_FUNCIONARIO_ATIVO = @IC_FUNCIONARIO_ATIVO,
			 IC_FUNCIONARIO_ACESSO_SISTEMACHAMADA = @IC_FUNCIONARIO_ACESSO_SISTEMACHAMADA,
			 DS_PACIENTE_COMENTARIO = @DS_PACIENTE_COMENTARIO,
			 DS_PACIENTE_PENDENCIAS = @DS_PACIENTE_PENDENCIAS,
			 ID_PACIENTE_TIPO_PACIENTE = @ID_PACIENTE_TIPO_PACIENTE,
			 IC_PACIENTE_ATIVO = @IC_PACIENTE_ATIVO,
			 ID_PROFISSIONAL_CONSELHOPROFISSIONAL = @ID_PROFISSIONAL_CONSELHOPROFISSIONAL,
			 NR_PROFISSIONAL_CONSELHOPROFISSIONAL = @NR_PROFISSIONAL_CONSELHOPROFISSIONAL,
			 IC_PROFISSIONAL_ATIVO = @IC_PROFISSIONAL_ATIVO,
			 IC_PROFISSIONAL_SERVICO_INTERNO = @IC_PROFISSIONAL_SERVICO_INTERNO,
			 IC_PROFISSIONAL_RETEMIMPOSTO = @IC_PROFISSIONAL_RETEMIMPOSTO,
			 PC_PROFISSIONAL_RETEMIMPOSTO = @PC_PROFISSIONAL_RETEMIMPOSTO,
			 IC_TRANSPORTADORA_ATIVO = @IC_TRANSPORTADORA_ATIVO,
			 IC_VENDEDOR_ATIVO = @IC_VENDEDOR_ATIVO,
			 IC_INDICADOR = @IC_INDICADOR,
		     DT_INDICADOR_CADASTRO = @DT_INDICADOR_CADASTRO,
			 IC_INDICADOR_ATIVO = @IC_INDICADOR_ATIVO,
			 ID_INDICADOR_TIPOINDICADOR = @ID_INDICADOR_TIPOINDICADOR
   WHERE ID_PESSOA = @ID_PESSOA
     AND ID_EMPRESA = @ID_EMPRESA
END
GO
DELETE FROM TB_SEG_USUARIO_GRID_CONFIGURAR WHERE NO_TELA = 'frmListaGeral_CadastroContaCaixa'
GO
ALTER PROCEDURE [dbo].[SP_CONTACAIXA_CAD]
(
 @SQ_CONTAFINANCEIRA INT OUT,
 @ID_DEPARTAMENTO_RESPONSAVEL INT,
 @ID_PESSOA_SUPERVISAO INT,
 @NO_CONTAFINANCEIRA VARCHAR(100),
 @DS_LOCALIZACAO VARCHAR(50),
 @IC_ATIVO CHAR(1),
 @IC_CONTROLASALDO CHAR(1)
)
AS
BEGIN
  IF ISNULL(@SQ_CONTAFINANCEIRA, 0)  = 0
    BEGIN
      INSERT INTO TB_CONTAFINANCEIRA (ID_DEPARTAMENTO_RESPONSAVEL, ID_PESSOA_SUPERVISAO, NO_CONTAFINANCEIRA, DS_LOCALIZACAO,
									  IC_ATIVO, IC_CONTROLASALDO)
	   VALUES (@ID_DEPARTAMENTO_RESPONSAVEL, @ID_PESSOA_SUPERVISAO, @NO_CONTAFINANCEIRA, @DS_LOCALIZACAO,
	           @IC_ATIVO, @IC_CONTROLASALDO)

	  SET @SQ_CONTAFINANCEIRA = @@IDENTITY
	END
  ELSE
    UPDATE TB_CONTAFINANCEIRA
	 SET ID_DEPARTAMENTO_RESPONSAVEL = @ID_DEPARTAMENTO_RESPONSAVEL,
	     ID_PESSOA_SUPERVISAO = @ID_PESSOA_SUPERVISAO,
		 NO_CONTAFINANCEIRA = @NO_CONTAFINANCEIRA,
		 DS_LOCALIZACAO = @DS_LOCALIZACAO,
		 IC_ATIVO = @IC_ATIVO,
		 IC_CONTROLASALDO = @IC_CONTROLASALDO
     WHERE SQ_CONTAFINANCEIRA = @SQ_CONTAFINANCEIRA

  RETURN
END
GO
ALTER TABLE TB_SISTEMA
 ADD DS_LINK_CHAMAR_SENHA VARCHAR(255)
GO
UPDATE TB_SISTEMA SET DS_LINK_CHAMAR_SENHA = 'http://server.clinica28dejulho.com.br:21253/api/chamadas28/senha?unidade=[Unidade]&senha=[Senha]&caixa=[Caixa]&andar=[Andar]'
GO
CREATE TABLE TB_CAIXA_ATENDIMENTO
(
 SQ_CAIXA_ATENDIMENTO INT NOT NULL IDENTITY(1, 1),
 ID_EMPRESA INT NOT NULL,
 NO_CAIXA_ATENDIMENTO VARCHAR(100) NOT NULL,
 IC_USA_SISTEMACHAMADA CHAR(1) NOT NULL DEFAULT 'S',
 DS_LOCALIZACAO VARCHAR(50),
 IC_ATIVO CHAR(1)
)
GO
EXEC sp_RENAME 'dbo.TB_CLINICA_SENHA.ID_CONTAFINANCEIRA', 'ID_CAIXA_ATENDIMENTO', 'COLUMN';
GO
EXEC sp_RENAME 'dbo.TB_CLINICA_SENHA_CHAMADA.ID_CONTAFINANCEIRA', 'ID_CAIXA_ATENDIMENTO', 'COLUMN';
GO
CREATE VIEW VW_CLINICA_SENHA_ULTIMA_SENHA_CHAMADA
AS
SELECT CLSNH.ID_EMPRESA, CAST(CSCMD.DH_CLINICA_SENHA_CHAMADA AS DATE) DT_CLINICA_SENHA, CLSNH.NR_CLINICA_SENHA, CLSNH.SQ_CLINICA_SENHA, CSCMD.ID_CAIXA_ATENDIMENTO,        CSCMD.ID_USUARIO
 FROM (SELECT T2.ID_EMPRESA,
			  CAST(T1.DH_CLINICA_SENHA_CHAMADA AS DATE) DT_CLINICA_SENHA_CHAMADA,
			  MAX(T1.DH_CLINICA_SENHA_CHAMADA) DH_CLINICA_SENHA_CHAMADA
        FROM TB_CLINICA_SENHA_CHAMADA T1
		 INNER JOIN TB_CLINICA_SENHA T2 ON T2.SQ_CLINICA_SENHA = T1.ID_CLINICA_SENHA
        GROUP BY T2.ID_EMPRESA, CAST(T1.DH_CLINICA_SENHA_CHAMADA AS DATE)) CSCMX
  INNER JOIN TB_CLINICA_SENHA_CHAMADA CSCMD ON CSCMD.DH_CLINICA_SENHA_CHAMADA = CSCMX.DH_CLINICA_SENHA_CHAMADA
  INNER JOIN TB_CLINICA_SENHA CLSNH ON CLSNH.SQ_CLINICA_SENHA = CSCMD.ID_CLINICA_SENHA
                                   AND CLSNH.ID_EMPRESA = CSCMX.ID_EMPRESA
GO
CREATE PROCEDURE SP_CLINICA_SENHA_CHAMADA_UPD
(
 @ID_CLINICA_SENHA INT,
 @ID_CAIXA_ATENDIMENTO INT,
 @ID_USUARIO INT
)
AS
BEGIN
  DECLARE @DH_CLINICA_SENHA_CHAMADA DATETIME

  SET @DH_CLINICA_SENHA_CHAMADA = GETDATE()

  INSERT INTO TB_CLINICA_SENHA_CHAMADA
  (ID_CLINICA_SENHA, ID_CAIXA_ATENDIMENTO, ID_USUARIO, DH_CLINICA_SENHA_CHAMADA)
  VALUES
  (@ID_CLINICA_SENHA, @ID_CAIXA_ATENDIMENTO, @ID_USUARIO, @DH_CLINICA_SENHA_CHAMADA)

  UPDATE TB_CLINICA_SENHA 
   SET DH_CHAMADA = @DH_CLINICA_SENHA_CHAMADA,
       ID_USUARIO = @ID_USUARIO,
	   ID_CAIXA_ATENDIMENTO = @ID_CAIXA_ATENDIMENTO
   WHERE SQ_CLINICA_SENHA = @ID_CLINICA_SENHA
END
GO
CREATE VIEW VW_CLINICA_SENHA_ULTIMA_SENHA_CHAMADA_HOJE
AS
SELECT USCHM.*, CXATD.NO_CAIXA_ATENDIMENTO, CXATD.SQ_CAIXA_ATENDIMENTO, PESSO.NO_PESSOA, PESSO.NO_FANTASIA_REDUZIDO, CXATD.DS_LOCALIZACAO
 FROM VW_CLINICA_SENHA_ULTIMA_SENHA_CHAMADA USCHM
  INNER JOIN TB_CAIXA_ATENDIMENTO CXATD ON CXATD.SQ_CAIXA_ATENDIMENTO = USCHM.ID_CAIXA_ATENDIMENTO
  INNER JOIN TB_PESSOA PESSO ON PESSO.SQ_PESSOA = USCHM.ID_USUARIO
 WHERE USCHM.DT_CLINICA_SENHA = CAST(GETDATE() AS DATE)
GO
ALTER TABLE TB_PROCEDIMENTO
 ADD ID_PESSOA_EXECUTOU_PADRAO INT
GO
ALTER PROCEDURE [dbo].[SP_PROCEDIMENTO_CAD]
(
 @SQ_PROCEDIMENTO INT OUTPUT,
 @ID_TABELAPROCEDIMENTO INT,
 @ID_OPT_TIPOPROCEDIMENTO INT,
 @ID_OPT_TIPOEXAME INT,
 @ID_GRUPOPROCEDIMENTO INT,
 @ID_PLANOCONTAS INT,
 @ID_TIPO_CONSULTA_PREFERENCIAL INT,
 @ID_CLASSIFICACAO_EXAME INT,
 @ID_ESPECIALIDADE_PADRAO INT,
 @ID_PESSOA_EXECUTOU_PADRAO INT,
 @CD_PROCEDIMENTO CHAR(11),
 @NO_PROCEDIMENTO VARCHAR(100),
 @IC_GERA_CLINICA_EXAME_CITOLOGICO CHAR(1),
 @IC_ATIVO CHAR(1)
)
AS
BEGIN
  IF ISNULL(@SQ_PROCEDIMENTO, 0) = 0
    BEGIN
      INSERT INTO TB_PROCEDIMENTO
	  (ID_TABELAPROCEDIMENTO, ID_OPT_TIPOPROCEDIMENTO, ID_OPT_TIPOEXAME, ID_GRUPOPROCEDIMENTO, ID_TIPO_CONSULTA_PREFERENCIAL,
	   ID_CLASSIFICACAO_EXAME, ID_PLANOCONTAS, ID_ESPECIALIDADE_PADRAO, ID_PESSOA_EXECUTOU_PADRAO, CD_PROCEDIMENTO, NO_PROCEDIMENTO,
	   IC_GERA_CLINICA_EXAME_CITOLOGICO, IC_ATIVO)
	  VALUES
	  (@ID_TABELAPROCEDIMENTO, @ID_OPT_TIPOPROCEDIMENTO, @ID_OPT_TIPOEXAME, @ID_GRUPOPROCEDIMENTO, @ID_TIPO_CONSULTA_PREFERENCIAL,
	   @ID_CLASSIFICACAO_EXAME, @ID_PLANOCONTAS, @ID_ESPECIALIDADE_PADRAO, @ID_PESSOA_EXECUTOU_PADRAO, @CD_PROCEDIMENTO, @NO_PROCEDIMENTO,
	   @IC_GERA_CLINICA_EXAME_CITOLOGICO, @IC_ATIVO)
	  
	  SELECT @SQ_PROCEDIMENTO = @@IDENTITY
	END
  ELSE
    UPDATE TB_PROCEDIMENTO
     SET ID_TABELAPROCEDIMENTO = @ID_TABELAPROCEDIMENTO,
		 ID_OPT_TIPOPROCEDIMENTO = @ID_OPT_TIPOPROCEDIMENTO,
		 ID_OPT_TIPOEXAME = @ID_OPT_TIPOEXAME,
		 ID_GRUPOPROCEDIMENTO = @ID_GRUPOPROCEDIMENTO,
		 ID_PLANOCONTAS = @ID_PLANOCONTAS,
		 ID_CLASSIFICACAO_EXAME = @ID_CLASSIFICACAO_EXAME,
		 ID_TIPO_CONSULTA_PREFERENCIAL = @ID_TIPO_CONSULTA_PREFERENCIAL,
		 ID_ESPECIALIDADE_PADRAO = @ID_ESPECIALIDADE_PADRAO,
		 ID_PESSOA_EXECUTOU_PADRAO = @ID_PESSOA_EXECUTOU_PADRAO, 
		 CD_PROCEDIMENTO = @CD_PROCEDIMENTO,
		 NO_PROCEDIMENTO = @NO_PROCEDIMENTO,
		 IC_GERA_CLINICA_EXAME_CITOLOGICO = @IC_GERA_CLINICA_EXAME_CITOLOGICO,
		 IC_ATIVO = @IC_ATIVO
     WHERE SQ_PROCEDIMENTO = @SQ_PROCEDIMENTO

  RETURN
END
GO
ALTER PROCEDURE [dbo].[SP_AGENDAMENTO_CAD]
(
	@SQ_AGENDAMENTO INT OUTPUT,
	@CD_AGENDAMENTO VARCHAR(10) OUTPUT,
	@ID_EMPRESA int,
	@ID_TIPO_CONSULTA int,
	@ID_AGENDAMENTO_ORIGEM int,
	@ID_PESSOA int,
	@ID_PESSOA_PROFISSIONAL int,
	@ID_PESSOA_EXECUTOR int,
	@ID_ESPECIALIDADE int,
	@ID_CONVENIO int,
	@ID_PROCEDIMENTO int,
	@ID_INDICACAO INT,
	@ID_PESSOAINDICADOR INT,
	@ID_OPT_STATUS int,
	@ID_CANALMARCACAO int,
	@DH_AGENDAMENTO datetime,
	@DH_CHEGADA datetime,
	@DH_SAIDA datetime,
	@NO_PESSOA varchar(100),
	@CD_TELEFONE varchar(20),
	@CD_CELULAR varchar(20),
	@DS_COMPLEMENTO varchar(MAX),
	@VL_PROCEDIMENTO MONEY = NULL
)
AS
BEGIN
 	DECLARE @IC_CONTROLACREDITO CHAR(1)
	DECLARE @VL_CREDITO MONEY
	DECLARE @VL_AUX MONEY

	SET @VL_PROCEDIMENTO = ISNULL(@VL_PROCEDIMENTO, 0)

	SELECT @VL_CREDITO = ISNULL(VL_CREDITO, 0),
	       @IC_CONTROLACREDITO = ISNULL(IC_CONTROLACREDITO, 'N')
	 FROM TB_CONVENIO
	 WHERE SQ_CONVENIO = @ID_CONVENIO

	IF @IC_CONTROLACREDITO = 'S' AND @VL_CREDITO < @VL_PROCEDIMENTO
	  BEGIN
		  RAISERROR('Esse convênio tem controle de créito, e o saldo é menor do que o valor do procedimento', 16, 1)

		  RETURN
		END

   IF @ID_PESSOA_EXECUTOR IS NULL
     BEGIN
      IF EXISTS(SELECT * FROM TB_PROCEDIMENTO WHERE SQ_PROCEDIMENTO = @ID_PROCEDIMENTO AND ID_PESSOA_EXECUTOU_PADRAO IS NOT NULL)
	    SELECT @ID_PESSOA_EXECUTOR = ID_PESSOA_EXECUTOU_PADRAO FROM TB_PROCEDIMENTO WHERE SQ_PROCEDIMENTO = @ID_PROCEDIMENTO
     END
   
	
  IF (@ID_OPT_STATUS = 38 /* Agendado */ OR @ID_OPT_STATUS =	581 /* Confirmado */) AND @DH_CHEGADA IS NOT NULL
    SET @ID_OPT_STATUS = 569 /* Aguardando */

  IF ISNULL(@SQ_AGENDAMENTO, 0) = 0
    BEGIN
			SELECT @CD_AGENDAMENTO = dbo.FC_EMPRESA_NOVO_CD_AGENDAMENTO(@ID_EMPRESA)

			UPDATE TB_EMPRESA SET CD_AGENDAMENTO = @CD_AGENDAMENTO WHERE ID_EMPRESA = @ID_EMPRESA

			INSERT INTO TB_AGENDAMENTO
			(ID_AGENDAMENTO_ORIGEM, ID_EMPRESA, ID_PESSOA, ID_PESSOA_PROFISSIONAL, ID_PESSOA_EXECUTOR, ID_ESPECIALIDADE, ID_PESSOAINDICADOR,
			 ID_CONVENIO, ID_PROCEDIMENTO, ID_INDICACAO, ID_CANALMARCACAO, CD_AGENDAMENTO, DH_AGENDAMENTO, DH_CHEGADA, DH_SAIDA, NO_PESSOA, CD_TELEFONE,
			 CD_CELULAR, DS_COMPLEMENTO, ID_TIPO_CONSULTA, VL_PROCEDIMENTO, ID_OPT_STATUS)
			VALUES
			(@ID_AGENDAMENTO_ORIGEM, @ID_EMPRESA, @ID_PESSOA, @ID_PESSOA_PROFISSIONAL, @ID_PESSOA_EXECUTOR, @ID_ESPECIALIDADE, @ID_PESSOAINDICADOR,
			 @ID_CONVENIO, @ID_PROCEDIMENTO, @ID_INDICACAO, @ID_CANALMARCACAO, @CD_AGENDAMENTO, @DH_AGENDAMENTO, @DH_CHEGADA, @DH_SAIDA, @NO_PESSOA, @CD_TELEFONE,
			 @CD_CELULAR, @DS_COMPLEMENTO, @ID_TIPO_CONSULTA, @VL_PROCEDIMENTO, @ID_OPT_STATUS)

			SET @SQ_AGENDAMENTO = @@IDENTITY
		END
	ELSE
    UPDATE TB_AGENDAMENTO
		 SET ID_AGENDAMENTO_ORIGEM = @ID_AGENDAMENTO_ORIGEM,
				 ID_EMPRESA = @ID_EMPRESA,
				 ID_PESSOA = @ID_PESSOA,
				 ID_PESSOA_PROFISSIONAL = @ID_PESSOA_PROFISSIONAL,
				 ID_PESSOA_EXECUTOR = @ID_PESSOA_EXECUTOR,
				 ID_ESPECIALIDADE = @ID_ESPECIALIDADE,
				 ID_CONVENIO = @ID_CONVENIO,
				 ID_PROCEDIMENTO = @ID_PROCEDIMENTO,
				 ID_INDICACAO = @ID_INDICACAO,
				 ID_PESSOAINDICADOR = @ID_PESSOAINDICADOR,
				 ID_CANALMARCACAO = @ID_CANALMARCACAO,
				 DH_AGENDAMENTO = @DH_AGENDAMENTO,
			     DH_CHEGADA = @DH_CHEGADA,
				 DH_SAIDA = @DH_SAIDA,
				 NO_PESSOA = @NO_PESSOA,
				 CD_TELEFONE = @CD_TELEFONE,
				 CD_CELULAR = @CD_CELULAR,
				 DS_COMPLEMENTO = @DS_COMPLEMENTO,
				 ID_OPT_STATUS = @ID_OPT_STATUS,
				 ID_TIPO_CONSULTA = @ID_TIPO_CONSULTA,
				 VL_PROCEDIMENTO = ISNULL(@VL_PROCEDIMENTO, VL_PROCEDIMENTO)
		 WHERE SQ_AGENDAMENTO = @SQ_AGENDAMENTO 

	EXEC SP_AGENDAMENTO_CONVENIO_UPD @SQ_AGENDAMENTO, 'S'

  RETURN
END
GO
ALTER TABLE TB_CONDICAOPAGAMENTO
 ADD PC_TAXA_COMPENSACAO DECIMAL(18, 5)
GO
ALTER PROCEDURE [dbo].[SP_CONDICAOPAGAMENTO_CAD]
(
 @SQ_CONDICAOPAGAMENTO INT OUTPUT,
 @ID_EMPRESA INT,
 @ID_TIPO_DOCUMENTO_ENTRADA_PADRAO INT,
 @ID_TIPO_DOCUMENTO_PARCELA_PADRAO INT,
 @ID_FORMAPAGAMENTO_ENTRADA_PADRAO INT,
 @ID_FORMAPAGAMENTO_PARCELA_PADRAO INT,
 @ID_OPT_PERIODOCALCULOFINANCEIRO_JUROS INT,
 @CD_CONDICAOPAGAMENTO VARCHAR(10),
 @NO_CONDICAOPAGAMENTO VARCHAR(100),
 @QT_PARCELA INT,
 @QT_PARCELA_DIASPRIMEIRAPARCELA INT,
 @QT_PARCELA_DIASINTERVALO INT,
 @PC_ACRESCIMO DECIMAL(18, 5),
 @PC_ENTRADA DECIMAL(18, 5),
 @PC_JUROS DECIMAL(18, 5),
 @PC_TAXA_COMPENSACAO DECIMAL(18, 5),
 @IC_GERAR_AVISTA CHAR(1),
 @IC_USAR_RECEBIMENTO CHAR(1),
 @IC_USAR_VENDA CHAR(1),
 @IC_ATIVO CHAR(1)
)
AS
BEGIN
  IF ISNULL(@SQ_CONDICAOPAGAMENTO, 0) = 0
		BEGIN
			INSERT INTO TB_CONDICAOPAGAMENTO
			(ID_EMPRESA, ID_OPT_PERIODOCALCULOFINANCEIRO_JUROS, ID_FORMAPAGAMENTO_ENTRADA_PADRAO, ID_FORMAPAGAMENTO_PARCELA_PADRAO,
			 ID_TIPO_DOCUMENTO_ENTRADA_PADRAO, ID_TIPO_DOCUMENTO_PARCELA_PADRAO, CD_CONDICAOPAGAMENTO, NO_CONDICAOPAGAMENTO, QT_PARCELA,
			 QT_PARCELA_DIASPRIMEIRAPARCELA, QT_PARCELA_DIASINTERVALO, PC_ACRESCIMO, PC_ENTRADA, PC_JUROS, PC_TAXA_COMPENSACAO,
			 IC_GERAR_AVISTA, IC_USAR_RECEBIMENTO, IC_USAR_VENDA, IC_ATIVO)
			VALUES
			(@ID_EMPRESA, @ID_OPT_PERIODOCALCULOFINANCEIRO_JUROS, @ID_FORMAPAGAMENTO_ENTRADA_PADRAO, @ID_FORMAPAGAMENTO_PARCELA_PADRAO,
			 @ID_TIPO_DOCUMENTO_ENTRADA_PADRAO, @ID_TIPO_DOCUMENTO_PARCELA_PADRAO, @CD_CONDICAOPAGAMENTO, @NO_CONDICAOPAGAMENTO, @QT_PARCELA,
			 @QT_PARCELA_DIASPRIMEIRAPARCELA, @QT_PARCELA_DIASINTERVALO, @PC_ACRESCIMO, @PC_ENTRADA, @PC_JUROS, @PC_TAXA_COMPENSACAO,
			 @IC_GERAR_AVISTA, @IC_USAR_RECEBIMENTO, @IC_USAR_VENDA, @IC_ATIVO)

			SET @SQ_CONDICAOPAGAMENTO = @@IDENTITY
		END
	ELSE
	  UPDATE TB_CONDICAOPAGAMENTO
		 SET ID_EMPRESA = @ID_EMPRESA,
		     ID_OPT_PERIODOCALCULOFINANCEIRO_JUROS = @ID_OPT_PERIODOCALCULOFINANCEIRO_JUROS,
				 ID_TIPO_DOCUMENTO_ENTRADA_PADRAO = @ID_TIPO_DOCUMENTO_ENTRADA_PADRAO,
				 ID_TIPO_DOCUMENTO_PARCELA_PADRAO = @ID_TIPO_DOCUMENTO_PARCELA_PADRAO,
				 ID_FORMAPAGAMENTO_ENTRADA_PADRAO = @ID_FORMAPAGAMENTO_ENTRADA_PADRAO,
				 ID_FORMAPAGAMENTO_PARCELA_PADRAO = @ID_FORMAPAGAMENTO_PARCELA_PADRAO,
				 CD_CONDICAOPAGAMENTO = @CD_CONDICAOPAGAMENTO,
				 NO_CONDICAOPAGAMENTO = @NO_CONDICAOPAGAMENTO,
				 QT_PARCELA = @QT_PARCELA,
				 QT_PARCELA_DIASPRIMEIRAPARCELA = @QT_PARCELA_DIASPRIMEIRAPARCELA,
			   QT_PARCELA_DIASINTERVALO = @QT_PARCELA_DIASINTERVALO,
				 PC_ACRESCIMO = @PC_ACRESCIMO,
				 PC_ENTRADA = @PC_ENTRADA,
				 PC_JUROS = @PC_JUROS,
				 PC_TAXA_COMPENSACAO = @PC_TAXA_COMPENSACAO,
				 IC_GERAR_AVISTA = @IC_GERAR_AVISTA,
				 IC_USAR_RECEBIMENTO = @IC_USAR_RECEBIMENTO,
				 IC_USAR_VENDA = @IC_USAR_VENDA,
				 IC_ATIVO = @IC_ATIVO
		 WHERE SQ_CONDICAOPAGAMENTO = @SQ_CONDICAOPAGAMENTO

  RETURN
END
GO
ALTER TABLE TB_MOVFINANCEIRAPARCELA
 ADD PC_TAXA_COMPENSACAO DECIMAL(18, 5)
GO
ALTER TABLE TB_MOVFINANCEIRAPARCELA
 ADD VL_TAXA_COMPENSACAO MONEY
GO
ALTER TABLE TB_MOVFINANCEIRAPARCELA
 ADD ID_CONDICAOPAGAMENTO INT
GO
ALTER PROCEDURE [dbo].[SP_MOVFINANCEIRAPARCELA_CAD]
(
	@SQ_MOVFINANCEIRAPARCELA int OUTPUT,
	@ID_MOVFINANCEIRA int,
	@ID_OPT_STATUS int,
	@ID_TIPO_DOCUMENTO int,
	@ID_MOVFINANCEIRAPARCELAORIGEM int,
	@ID_DOCUMENTOFINANCEIRO int,
	@ID_FORMAPAGAMENTO_PREFERENCIAL int,
	@ID_CONDICAOPAGAMENTO int,
	@CD_PARCELA varchar(10),
	@CD_DOCUMENTO varchar(60),
	@CM_DOCUMENTO varchar(MAX),
	@DS_EMITENTE varchar(100),
	@DT_VENCIMENTO date,
	@DT_QUITACAO date,
	@VL_PARCELA money,
	@VL_JUROS money,
	@VL_DESCONTO money,
	@VL_QUITADO money,
	@VL_PROVISAO money,
	@PC_TAXA_COMPENSACAO DECIMAL(18, 5)
)
AS
BEGIN
  IF ISNULL(@SQ_MOVFINANCEIRAPARCELA, 0) = 0
		BEGIN
      INSERT INTO TB_MOVFINANCEIRAPARCELA
			(ID_MOVFINANCEIRA, ID_OPT_STATUS, ID_TIPO_DOCUMENTO, ID_MOVFINANCEIRAPARCELAORIGEM,
			 ID_DOCUMENTOFINANCEIRO, ID_FORMAPAGAMENTO_PREFERENCIAL, ID_CONDICAOPAGAMENTO, CD_PARCELA,
			 CD_DOCUMENTO, CM_DOCUMENTO, DS_EMITENTE, DT_VENCIMENTO, DT_QUITACAO, VL_PARCELA, VL_JUROS,
			 VL_DESCONTO, VL_QUITADO, VL_PROVISAO, PC_TAXA_COMPENSACAO)
			VALUES
			(@ID_MOVFINANCEIRA, @ID_OPT_STATUS, @ID_TIPO_DOCUMENTO, @ID_MOVFINANCEIRAPARCELAORIGEM,
			 @ID_DOCUMENTOFINANCEIRO, @ID_FORMAPAGAMENTO_PREFERENCIAL, @ID_CONDICAOPAGAMENTO, @CD_PARCELA,
			 @CD_DOCUMENTO, @CM_DOCUMENTO, @DS_EMITENTE, @DT_VENCIMENTO, @DT_QUITACAO, @VL_PARCELA, @VL_JUROS,
			 @VL_DESCONTO, @VL_QUITADO, @VL_PROVISAO, @PC_TAXA_COMPENSACAO)

      SET @SQ_MOVFINANCEIRAPARCELA = @@IDENTITY
		END
  ELSE
    UPDATE TB_MOVFINANCEIRAPARCELA
		 SET ID_MOVFINANCEIRA = @ID_MOVFINANCEIRA,
         ID_OPT_STATUS = @ID_OPT_STATUS,
         ID_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO,
         ID_MOVFINANCEIRAPARCELAORIGEM = @ID_MOVFINANCEIRAPARCELAORIGEM,
         ID_DOCUMENTOFINANCEIRO = @ID_DOCUMENTOFINANCEIRO,
         ID_FORMAPAGAMENTO_PREFERENCIAL = @ID_FORMAPAGAMENTO_PREFERENCIAL,
		 ID_CONDICAOPAGAMENTO = @ID_CONDICAOPAGAMENTO,
         CD_PARCELA = @CD_PARCELA,
         CD_DOCUMENTO = @CD_DOCUMENTO,
         CM_DOCUMENTO = @CM_DOCUMENTO,
         DS_EMITENTE = @DS_EMITENTE,
         DT_VENCIMENTO = @DT_VENCIMENTO,
         DT_QUITACAO = @DT_QUITACAO,
         VL_PARCELA = @VL_PARCELA,
         VL_JUROS = @VL_JUROS,
         VL_DESCONTO = @VL_DESCONTO,
         VL_QUITADO = @VL_QUITADO,
         VL_PROVISAO = ISNULL(@VL_PROVISAO, VL_PROVISAO),
		 PC_TAXA_COMPENSACAO = @PC_TAXA_COMPENSACAO
		 WHERE SQ_MOVFINANCEIRAPARCELA = @SQ_MOVFINANCEIRAPARCELA

	RETURN
END
GO
ALTER VIEW [dbo].[VW_MOVFINANCEIRAPARCELA]
AS
SELECT MFP.ID_MOVFINANCEIRA, MFN.ID_SEGMENTO, MFN.ID_EMPRESA, MFN.ID_OPT_PERIODOCALCULOFINANCEIRO_JUROS,
       MFN.ID_OPT_PERIODOCALCULOFINANCEIRO_DESCONTO, MFP.SQ_MOVFINANCEIRAPARCELA, CONCAT(MFN.CD_MOVFINANCEIRA, '-', MFP.CD_PARCELA) CD_MOVFINANCEIRA_PARCELA,
	   MFP.CD_PARCELA, MFP.CD_DOCUMENTO,
	   MFN.ID_CONTAFINANCEIRA_CREDITO, MFN.ID_CONTAFINANCEIRA_DEBITO, MFP.ID_FORMAPAGAMENTO_PREFERENCIAL, STS.SQ_OPCAO ID_OPT_STATUS,
	   STS.NO_OPCAO NO_OPT_STATUS, STS.CD_OPCAO CD_OPT_STATUS, OPCAO_PCFJR.NO_OPCAO NO_OPT_PERIODOCALCULOFINANCEIRO_JUROS,
	   OPCAO_PCFJR.NO_OPCAO_ABREVIADO NO_OPT_PERIODOCALCULOFINANCEIRO_JUROS_ABREVIADO,
	   OPCAO_PCFDC.NO_OPCAO NO_OPT_PERIODOCALCULOFINANCEIRO_DESCONTO, OPCAO_PCFDC.NO_OPCAO_ABREVIADO NO_OPT_PERIODOCALCULOFINANCEIRO_DESCONTO_ABREVIADO,
	   CCC.NO_CONTAFINANCEIRA NO_CONTAFINANCEIRA_CREDITO, CCD.NO_CONTAFINANCEIRA NO_CONTAFINANCEIRA_DEBITO,  MFN.ID_PESSOA, PES.NO_PESSOA, PES.NO_PESSOA_RELATORIO,
	   MFN.CD_MOVFINANCEIRA, MFN.DS_MOVFINANCEIRA, MFP.ID_TIPO_DOCUMENTO, MFP.ID_DOCUMENTOFINANCEIRO, TDC.NO_TIPO_DOCUMENTO, MFN.DT_MOVIMENTACAO, MFP.DT_VENCIMENTO,
	   MFP.DT_QUITACAO, MFP.VL_PARCELA, MFP.VL_QUITADO, MFN.PC_JUROS, MFN.PC_MULTA, MFP.VL_JUROS, MFP.VL_ACRESCIMO_PAGTO, MFP.VL_DESCONTO_PAGTO, MFP.VL_DESCONTO,
	   ISNULL(DEVOL.VL_DEVOLUCAO, 0) VL_DEVOLUCAO, MFN.VL_MULTA, MFN.PC_DESCONTO,
	   dbo.FC_CalculoPorcentagem(IIF(STS.CD_OPCAO = 'F', 0, IIF(MFP.VL_QUITADO > dbo.FC_MovFinanceiraParcela_Valor(MFP.SQ_MOVFINANCEIRAPARCELA), 0,
	   dbo.FC_MovFinanceiraParcela_Valor(MFP.SQ_MOVFINANCEIRAPARCELA) - MFP.VL_QUITADO)), ISNULL(PSEMP.PC_PROFISSIONAL_RETEMIMPOSTO, 0)) VL_CALC_IMPOSTO_RETIDO,
	   dbo.FC_CalculoFinanceiro_Calcular(MFN.ID_OPT_PERIODOCALCULOFINANCEIRO_DESCONTO,MFN.PC_DESCONTO, (MFP.VL_PARCELA - MFP.VL_QUITADO - ISNULL(MFP.VL_DESCONTO, 0)), MFP.DT_VENCIMENTO, GETDATE(), 'D') VL_CALC_DESCONTO,
	   IIF(STS.CD_OPCAO = 'F', 0, IIF(MFP.VL_QUITADO > dbo.FC_MovFinanceiraParcela_Valor(MFP.SQ_MOVFINANCEIRAPARCELA), 0, dbo.FC_MovFinanceiraParcela_Valor(MFP.SQ_MOVFINANCEIRAPARCELA) - MFP.VL_QUITADO)) VL_DEBITO,
	   IIF(MFP.ID_OPT_STATUS IN (60), 0, dbo.FC_ValorPositivo(DATEDIFF(DAY, MFP.DT_VENCIMENTO, ISNULL(ISNULL(MFG.DT_MOVIMENTACAO, MFP.DT_QUITACAO), GETDATE())), 0)) QT_DIAS_ATRASO,
	   IIF(STS.CD_OPCAO = 'F', 0, dbo.FC_CalculoFinanceiro_Calcular(MFN.ID_OPT_PERIODOCALCULOFINANCEIRO_JUROS, MFN.PC_JUROS, dbo.FC_MovFinanceiraParcela_Valor(MFP.SQ_MOVFINANCEIRAPARCELA) - MFP.VL_QUITADO, MFP.DT_VENCIMENTO, GETDATE(), 'J')) VL_CALC_JUROS,
	   IIF(STS.CD_OPCAO = 'F', 0, IIF(DATEDIFF(DAY, MFP.DT_VENCIMENTO, GETDATE()) <= 0, 0, MFN.VL_MULTA - MFP.VL_MULTA)) VL_CALC_MULTA,
	   MFP.DS_EMITENTE, MFP.DT_COMPENSACAO, MFP.IC_COMPENSADO, MFN.ID_OPT_TIPOMOVFINANCEIRA, TMV.CD_OPCAO CD_OPT_TIPOMOVFINANCEIRA,
	   TMV.NO_OPCAO NO_OPT_TIPOMOVFINANCEIRA, TMV.ID_TIPO_OPCAO ID_OPT_TIPOMOVFINANCEIRA_GRUPO, MFP.ID_APROVADOR_DESCONTO,
	   IIF(MFP.ID_OPT_STATUS = 57, '#1E90FF',
	       IIF(MFP.ID_OPT_STATUS = 58, '#00BFFF',
  		       IIF(MFP.ID_OPT_STATUS = 59, '#87CEEB',
			       IIF(MFP.ID_OPT_STATUS = 60, '#800080',
					   IIF(MFP.ID_OPT_STATUS = 61, '#FFA500',
						   IIF(MFP.ID_OPT_STATUS = 65, '#1E90FF',
							   IIF(MFP.ID_OPT_STATUS = 381, '#A0522D', '#FFFFFF'))))))) CD_STATUS_COR,
	   MFG.CD_MOVFINANCEIRA CD_MOVFINANCEIRAGERADA,
	   MFP.ID_MOVFINANCEIRAGERADA,
	   MFP.PC_TAXA_COMPENSACAO,
	   ISNULL(MFP.VL_TAXA_COMPENSACAO, dbo.FC_CalculoPorcentagem(MFP.VL_PARCELA, ISNULL(MFP.PC_TAXA_COMPENSACAO, 0))) VL_TAXA_COMPENSACAO
 FROM TB_MOVFINANCEIRAPARCELA MFP
  INNER JOIN TB_MOVFINANCEIRA MFN ON MFN.SQ_MOVFINANCEIRA = MFP.ID_MOVFINANCEIRA
  INNER JOIN TB_TIPO_DOCUMENTO TDC ON TDC.SQ_TIPO_DOCUMENTO = MFP.ID_TIPO_DOCUMENTO
  INNER JOIN TB_OPCAO STS ON STS.SQ_OPCAO = MFP.ID_OPT_STATUS
  INNER JOIN TB_OPCAO TMV ON TMV.SQ_OPCAO = MFN.ID_OPT_TIPOMOVFINANCEIRA
  LEFT JOIN TB_PESSOA_EMPRESA PSEMP ON PSEMP.ID_PESSOA = MFN.ID_PESSOA
                                    AND PSEMP.ID_EMPRESA = 2
   LEFT JOIN TB_OPCAO OPCAO_PCFJR ON OPCAO_PCFJR.SQ_OPCAO = MFN.ID_OPT_PERIODOCALCULOFINANCEIRO_JUROS
   LEFT JOIN TB_OPCAO OPCAO_PCFDC ON OPCAO_PCFDC.SQ_OPCAO = MFN.ID_OPT_PERIODOCALCULOFINANCEIRO_DESCONTO
   LEFT JOIN VW_PESSOA_NOME_RELATORIO PES ON PES.SQ_PESSOA = MFN.ID_PESSOA
					                     AND PES.ID_EMPRESA = MFN.ID_EMPRESA
   LEFT JOIN TB_CONTAFINANCEIRA CCC ON CCC.SQ_CONTAFINANCEIRA = MFN.ID_CONTAFINANCEIRA_CREDITO
   LEFT JOIN TB_CONTAFINANCEIRA CCD ON CCD.SQ_CONTAFINANCEIRA = MFN.ID_CONTAFINANCEIRA_DEBITO
   LEFT JOIN TB_MOVFINANCEIRA MFG ON MFG.SQ_MOVFINANCEIRA = MFP.ID_MOVFINANCEIRAGERADA
   LEFT JOIN (SELECT ID_MOVFINANCEIRAPARCELA,
                     SUM(VL_PAGAMENTO) VL_DEVOLUCAO
               FROM TB_MOVFINANCEIRAPAGTO PIMF
			    INNER JOIN TB_PAGAMENTO PAGT ON PAGT.SQ_PAGAMENTO = PIMF.ID_PAGAMENTO
				                            AND PAGT.DT_EXCLUSAO IS NULL
											AND PAGT.ID_OPT_TIPOPAGAMENTO = 815 /* Devolução a Cliente */
			   GROUP BY ID_MOVFINANCEIRAPARCELA) DEVOL ON DEVOL.ID_MOVFINANCEIRAPARCELA = MFP.SQ_MOVFINANCEIRAPARCELA
GO
ALTER TABLE TB_EMPRESA
 ADD ID_PLANOCONTAS_PADRAO_TAXA_COMPENSACAO INT
GO
ALTER PROCEDURE [dbo].[SP_CLINICA_VENDA_MOVFINANCEIRA_PAGAR_CAD]
(
 @ID_CLINICAVENDA INT,
 @DS_MOVFINANCEIRA VARCHAR(200)
)
AS
BEGIN
  DECLARE @NR_DIA_PAGTO_PRESTADORSERVICOMEDICO INT
	DECLARE @ID_EMPRESA INT
	DECLARE @ID_PESSOA_PROFISSIONAL INT
	DECLARE @ID_PLANOCONTAS_CONTASPAGAR INT
	DECLARE @ID_CONTAFINANCEIRA INT
	DECLARE @IC_FORNECEDOR_PRESTADORSERVICOMEDICO CHAR(1)
	DECLARE @ID_OPT_TIPOPROCEDIMENTO INT
	DECLARE @VL_REPASSE MONEY
	DECLARE @VL_MOVFINANCEIRA MONEY
	DECLARE @DH_AGENDAMENTO DATETIME
	DECLARE @DH_VENDA DATETIME

	DECLARE @SQ_MOVFINANCEIRA INT
	DECLARE @DT_VENCIMENTO DATETIME

	DECLARE @ID_FORMAPAGAMENTO_PADRAO INT
	DECLARE @ID_TIPODOCUMENTO_PADRAO INT

	DECLARE @DATA DATETIME

	SET @DATA = CAST(GETDATE() AS DATE)
	
	SELECT @ID_EMPRESA = ID_EMPRESA,
	       @ID_FORMAPAGAMENTO_PADRAO = ID_FORMAPAGAMENTO_PADRAO,
				 @ID_TIPODOCUMENTO_PADRAO = ID_TIPODOCUMENTO_PADRAO
	 FROM TB_EMPRESA
	 WHERE ID_EMPRESA_MATRIZ = ID_EMPRESA
	
	DECLARE csrSP_CLINICA_VENDA_MOVFINANCEIRA_PLNCONTAS_CAD
	 CURSOR FOR      
    SELECT CVDPC.ID_PESSOA_PROFISSIONAL,
					 GPPCD.ID_PLANOCONTAS_CONTASPAGAR,
					 PSEMP.IC_FORNECEDOR_PRESTADORSERVICOMEDICO,
					 SUM(VL_REPASSE) VL_REPASSE,
					 PROCE.ID_OPT_TIPOPROCEDIMENTO,
					 ISNULL(AGEND.DH_AGENDAMENTO,GETDATE()),
					 CLVND.DH_VENDA
		 FROM TB_CLINICA_VENDA_PROCEDIMENTO	CVDPC
			INNER JOIN TB_PROCEDIMENTO PROCE ON PROCE.SQ_PROCEDIMENTO = CVDPC.ID_PROCEDIMENTO
			INNER JOIN TB_GRUPOPROCEDIMENTO	GPPCD ON GPPCD.SQ_GRUPOPROCEDIMENTO = PROCE.ID_GRUPOPROCEDIMENTO
			INNER JOIN TB_CLINICA_VENDA CLVND ON CLVND.SQ_CLINICA_VENDA = CVDPC.ID_CLINICA_VENDA
			 LEFT JOIN TB_AGENDAMENTO AGEND ON AGEND.SQ_AGENDAMENTO = CVDPC.ID_AGENDAMENTO
			 LEFT JOIN TB_PESSOA_EMPRESA PSEMP ON PSEMP.ID_PESSOA = CVDPC.ID_PESSOA_PROFISSIONAL
		                                    AND PSEMP.ID_EMPRESA = @ID_EMPRESA
		 WHERE CVDPC.ID_CLINICA_VENDA =  @ID_CLINICAVENDA
		   AND GPPCD.ID_PLANOCONTAS_CONTASPAGAR IS NOT NULL
		 GROUP BY CVDPC.ID_PESSOA_PROFISSIONAL,
						  GPPCD.ID_PLANOCONTAS_CONTASPAGAR,
							PSEMP.IC_FORNECEDOR_PRESTADORSERVICOMEDICO,
							PROCE.ID_OPT_TIPOPROCEDIMENTO,
							AGEND.DH_AGENDAMENTO,
							CLVND.DH_VENDA

  SELECT @ID_CONTAFINANCEIRA = MVFNC.ID_CONTAFINANCEIRA_CREDITO,
				 @NR_DIA_PAGTO_PRESTADORSERVICOMEDICO = EMPRE.NR_DIA_PAGTO_PRESTADORSERVICOMEDICO,
				 @VL_MOVFINANCEIRA = SUM(CVDPC.VL_REPASSE)
	 FROM TB_CLINICA_VENDA CLVND
	  INNER JOIN TB_EMPRESA EMPRE ON EMPRE.ID_EMPRESA = CLVND.ID_EMPRESA
		INNER JOIN TB_CLINICA_VENDA_PROCEDIMENTO CVDPC ON CVDPC.ID_CLINICA_VENDA = CLVND.SQ_CLINICA_VENDA
		INNER JOIN TB_MOVFINANCEIRA MVFNC ON MVFNC.ID_CLINICA_VENDA = CLVND.SQ_CLINICA_VENDA
	 WHERE CLVND.SQ_CLINICA_VENDA = @ID_CLINICAVENDA
	 GROUP BY EMPRE.ID_EMPRESA, MVFNC.ID_CONTAFINANCEIRA_CREDITO, EMPRE.NR_DIA_PAGTO_PRESTADORSERVICOMEDICO
 
  OPEN csrSP_CLINICA_VENDA_MOVFINANCEIRA_PLNCONTAS_CAD

  FETCH NEXT FROM csrSP_CLINICA_VENDA_MOVFINANCEIRA_PLNCONTAS_CAD
	 INTO @ID_PESSOA_PROFISSIONAL, @ID_PLANOCONTAS_CONTASPAGAR, @IC_FORNECEDOR_PRESTADORSERVICOMEDICO, @VL_REPASSE, @ID_OPT_TIPOPROCEDIMENTO, @DH_AGENDAMENTO, @DH_VENDA

	WHILE @@FETCH_STATUS = 0
		BEGIN
		  SET @SQ_MOVFINANCEIRA = 0

		  EXEC SP_MOVFINANCEIRA_CAD @SQ_MOVFINANCEIRA OUT,
			                          @ID_EMPRESA,
                                46 /* Contas a Pagar */,
                                56 /* Aberto */,
                                667	/* ao Mês */,
                                669	/* Único */,
                                @ID_PESSOA_PROFISSIONAL,
                                NULL, @ID_CONTAFINANCEIRA, NULL, NULL, NULL, NULL, NULL ,
																@ID_CLINICAVENDA, NULL,
                                @DS_MOVFINANCEIRA,
                                @VL_MOVFINANCEIRA,
                                @VL_MOVFINANCEIRA,
                                0,
															  @DATA,
                                @DATA,
                                0, 0, 0, 0, 0, NULL

		  UPDATE CVDPC SET ID_MOVFINANCEIRA = @SQ_MOVFINANCEIRA
		 	 FROM TB_CLINICA_VENDA_PROCEDIMENTO	CVDPC
				INNER JOIN TB_PROCEDIMENTO PROCE ON PROCE.SQ_PROCEDIMENTO = CVDPC.ID_PROCEDIMENTO
				INNER JOIN TB_GRUPOPROCEDIMENTO	GPPCD ON GPPCD.SQ_GRUPOPROCEDIMENTO = PROCE.ID_GRUPOPROCEDIMENTO
				INNER JOIN TB_CLINICA_VENDA CLVND ON CLVND.SQ_CLINICA_VENDA = CVDPC.ID_CLINICA_VENDA
			 	 LEFT JOIN TB_AGENDAMENTO AGEND ON AGEND.SQ_AGENDAMENTO = CVDPC.ID_AGENDAMENTO
			 	 LEFT JOIN TB_PESSOA_EMPRESA PSEMP ON PSEMP.ID_PESSOA = CVDPC.ID_PESSOA_PROFISSIONAL
		                                    	AND PSEMP.ID_EMPRESA = @ID_EMPRESA
		 	 WHERE CVDPC.ID_CLINICA_VENDA =  @ID_CLINICAVENDA
		 	   AND GPPCD.ID_PLANOCONTAS_CONTASPAGAR IS NOT NULL
		 	   AND CVDPC.ID_PESSOA_PROFISSIONAL = @ID_PESSOA_PROFISSIONAL
				 AND GPPCD.ID_PLANOCONTAS_CONTASPAGAR = @ID_PLANOCONTAS_CONTASPAGAR
				 AND PSEMP.IC_FORNECEDOR_PRESTADORSERVICOMEDICO = @IC_FORNECEDOR_PRESTADORSERVICOMEDICO
				 AND PROCE.ID_OPT_TIPOPROCEDIMENTO = @ID_OPT_TIPOPROCEDIMENTO

			IF @ID_OPT_TIPOPROCEDIMENTO = 726	/* Procedimento */
			  SET @DT_VENCIMENTO = CAST(@DH_AGENDAMENTO AS DATE)
			ELSE
				BEGIN
					IF ISNULL(@IC_FORNECEDOR_PRESTADORSERVICOMEDICO, 'N') = 'S'
						SET @DT_VENCIMENTO = CAST(@DH_VENDA AS DATE)
					ELSE
						SET @DT_VENCIMENTO = CAST(@DH_AGENDAMENTO AS DATE)

					IF DATEPART(DAY, @DT_VENCIMENTO) < 15
						SET @DT_VENCIMENTO = DATEADD(MONTH, 1, DATEADD(DAY, 15, DATEADD(DAY, DATEPART(DAY, @DT_VENCIMENTO) * -1, @DT_VENCIMENTO)))
					ELSE
						BEGIN
							SET @DT_VENCIMENTO = DATEADD(MONTH, 2, DATEADD(DAY, DATEPART(DAY, @DT_VENCIMENTO) * -1, @DT_VENCIMENTO))

							IF DATEPART(DAY, @DT_VENCIMENTO) = 31
								SET @DT_VENCIMENTO = DATEADD(DAY, -1, @DT_VENCIMENTO)
						END
				END

		  EXEC SP_MOVFINANCEIRAPARCELA_CAD NULL,
                                       @SQ_MOVFINANCEIRA,
                                       61 /* Estimado */,
                                       @ID_TIPODOCUMENTO_PADRAO	/* Transferência/depósito */,
                                       NULL,
                                       NULL,
                                       @ID_FORMAPAGAMENTO_PADRAO /* Transferência/depósito */,
                                       '01/01',
                                       '00000',
                                       'REPASSE',
                                       NULL,
                                       @DT_VENCIMENTO,
                                       NULL,
                                       @VL_REPASSE,
                                       0,
                                       0,
                                       0,
                                       0,
									   0

				INSERT INTO TB_MOVFINANCEIRA_PLANOCONTAS (ID_MOVFINANCEIRA, ID_OPT_CREDITODEBITO, ID_PLANOCONTAS, PC_PARTICIPACAO)
				 VALUES (@SQ_MOVFINANCEIRA, 2, @ID_PLANOCONTAS_CONTASPAGAR, 100)

		  FETCH NEXT FROM csrSP_CLINICA_VENDA_MOVFINANCEIRA_PLNCONTAS_CAD 
	 		 INTO @ID_PESSOA_PROFISSIONAL, @ID_PLANOCONTAS_CONTASPAGAR, @IC_FORNECEDOR_PRESTADORSERVICOMEDICO, @VL_REPASSE, @ID_OPT_TIPOPROCEDIMENTO, @DH_AGENDAMENTO, @DH_VENDA
		END             

  CLOSE csrSP_CLINICA_VENDA_MOVFINANCEIRA_PLNCONTAS_CAD
	DEALLOCATE csrSP_CLINICA_VENDA_MOVFINANCEIRA_PLNCONTAS_CAD
END
GO
ALTER PROCEDURE [dbo].[SP_CLINICA_VENDA_DEVOLVER_UPD]
( 
 @SQ_CLINICA_VENDA INT,
 @SQ_CLINICA_VENDA_DEVOLUCAO INT OUTPUT,
 @SQ_MOVFINANCEIRA INT OUTPUT,
 @ID_EMPRESA INT,
 @ID_CONTAFINANCEIRA_DEBITO INT,
 @CM_JUSTIFICATIVA VARCHAR(150),
 @VL_DEVOLUCAO MONEY
)
AS
BEGIN
  DECLARE @ID_PESSOA INT
  DECLARE @ID_SEGMENTO INT
  DECLARE @ID_CONDICAOPAGAMENTO INT
  DECLARE @ID_CONVENIO INT
  DECLARE @DS_MOVFINANCEIRA VARCHAR(200)
  DECLARE @DT_MOVIMENTACAO DATE
  DECLARE @ID_TIPO_DOCUMENTO INT

  SET @DS_MOVFINANCEIRA = 'Devolução: ' + @CM_JUSTIFICATIVA
  SET @DT_MOVIMENTACAO = CAST(GETDATE() AS DATE)

  SELECT @ID_PESSOA = CLVND.ID_PESSOA,
		 @ID_SEGMENTO = MVFNC.ID_SEGMENTO,
		 @ID_CONDICAOPAGAMENTO = MVFNC.ID_CONDICAOPAGAMENTO,
		 @ID_CONVENIO = CLVND.ID_CONVENIO,
		 @ID_TIPO_DOCUMENTO = MFPCL.ID_TIPO_DOCUMENTO
   FROM TB_CLINICA_VENDA CLVND
    INNER JOIN TB_MOVFINANCEIRA MVFNC ON MVFNC.ID_CLINICA_VENDA = CLVND.SQ_CLINICA_VENDA
	                                 AND MVFNC.ID_OPT_TIPOMOVFINANCEIRA = 45 /* Contas a Receber */
	INNER JOIN TB_MOVFINANCEIRAPARCELA MFPCL ON MFPCL.ID_MOVFINANCEIRA = MVFNC.SQ_MOVFINANCEIRA
   WHERE CLVND.SQ_CLINICA_VENDA = @SQ_CLINICA_VENDA

  INSERT INTO TB_CLINICA_VENDA_DEVOLUCAO
  (ID_CLINICA_VENDA, DH_DEVOLUCAO, CM_CLINICA_VENDA_DEVOLUCAO)
  VALUES
  (@SQ_CLINICA_VENDA, GETDATE(), @CM_JUSTIFICATIVA)

  SET @SQ_CLINICA_VENDA_DEVOLUCAO = @@IDENTITY

  EXEC SP_MOVFINANCEIRA_CAD @SQ_MOVFINANCEIRA OUTPUT,
							@ID_EMPRESA,
							46 /* Contas a Pagar */,
							57 /* Quitada */,
							669 /* Único */,
							669 /* Único */,
							@ID_PESSOA,
							NULL,
							@ID_CONTAFINANCEIRA_DEBITO,
							NULL, NULL, NULL,
							@ID_SEGMENTO,
							@ID_CONDICAOPAGAMENTO,
							@SQ_CLINICA_VENDA,
							@ID_CONVENIO,
							@DS_MOVFINANCEIRA,
							@VL_DEVOLUCAO,
							@VL_DEVOLUCAO,
							0,
							@DT_MOVIMENTACAO,
							@DT_MOVIMENTACAO,
							0, 0, 0, 0, 0, NULL

  UPDATE TB_MOVFINANCEIRA
   SET ID_CLINICA_VENDA_DEVOLUCAO = @SQ_CLINICA_VENDA_DEVOLUCAO
   WHERE SQ_MOVFINANCEIRA = @SQ_MOVFINANCEIRA

  EXEC SP_MOVFINANCEIRAPARCELA_CAD NULL, @SQ_MOVFINANCEIRA, 57 /* Quitada */, @ID_TIPO_DOCUMENTO, NULL, NULL, NULL, '001/001', NULL, NULL, NULL, @DT_MOVIMENTACAO, @DT_MOVIMENTACAO, @VL_DEVOLUCAO, 0, 0, @VL_DEVOLUCAO, 0, 0

  INSERT INTO TB_MOVFINANCEIRA_PLANOCONTAS (ID_MOVFINANCEIRA, ID_PLANOCONTAS, ID_OPT_CREDITODEBITO, PC_PARTICIPACAO)
  SELECT @SQ_MOVFINANCEIRA, SQ_PLANOCONTAS, ID_OPT_CREDITODEBITO, 100
   FROM TB_PLANOCONTAS
   WHERE IC_USAR_DEVOLUCAO = 'S'

  RETURN
END
GO
ALTER VIEW [dbo].[VW_CONDICAOPAGAMENTO]
AS
SELECT CNDPG.SQ_CONDICAOPAGAMENTO,
			 CNDPG.ID_EMPRESA,
			 CNDPG.ID_TIPO_DOCUMENTO_ENTRADA_PADRAO,
			 CNDPG.ID_TIPO_DOCUMENTO_PARCELA_PADRAO,
			 CNDPG.ID_FORMAPAGAMENTO_ENTRADA_PADRAO,
			 CNDPG.ID_FORMAPAGAMENTO_PARCELA_PADRAO,
			 FPGTO_ENTPD.ID_TIPO_DOCUMENTO ID_TIPO_DOCUMENTO_FORMAPAGAMENTO_ENTRADA_PADRAO,
			 FPGTO_PCLPD.ID_TIPO_DOCUMENTO ID_TIPO_DOCUMENTO_FORMAPAGAMENTO_PARCELA_PADRAO,
			 CNDPG.ID_OPT_PERIODOCALCULOFINANCEIRO_JUROS,
			 CNDPG.CD_CONDICAOPAGAMENTO,
			 CNDPG.NO_CONDICAOPAGAMENTO,
			 TPDOC_ENTPD.NO_TIPO_DOCUMENTO NO_TIPO_DOCUMENTO_ENTRADA_PADRAO,
			 TPDOC_PCLPD.NO_TIPO_DOCUMENTO NO_TIPO_DOCUMENTO_PARCELA_PADRAO,
			 FPGTO_ENTPD.NO_FORMAPAGAMENTO NO_FORMAPAGAMENTO_ENTRADA_PADRAO,
			 FPGTO_PCLPD.NO_FORMAPAGAMENTO NO_FORMAPAGAMENTO_PARCELA_PADRAO,
			 OPCAO_PCFJR.NO_OPCAO NO_OPT_PERIODOCALCULOFINANCEIRO_JUROS,
			 CNDPG.QT_PARCELA,
			 CNDPG.QT_PARCELA_DIASPRIMEIRAPARCELA,
			 CNDPG.QT_PARCELA_DIASINTERVALO,
			 CNDPG.PC_ACRESCIMO,
			 CNDPG.PC_ENTRADA,
			 CNDPG.PC_JUROS,
			 CNDPG.PC_TAXA_COMPENSACAO,
			 CNDPG.IC_GERAR_AVISTA,
			 CNDPG.IC_USAR_RECEBIMENTO,
			 CNDPG.IC_USAR_VENDA,
			 CNDPG.IC_ATIVO
 FROM TB_CONDICAOPAGAMENTO CNDPG
  LEFT JOIN TB_FORMAPAGAMENTO FPGTO_ENTPD ON FPGTO_ENTPD.SQ_FORMAPAGAMENTO = CNDPG.ID_FORMAPAGAMENTO_ENTRADA_PADRAO
  LEFT JOIN TB_FORMAPAGAMENTO FPGTO_PCLPD ON FPGTO_PCLPD.SQ_FORMAPAGAMENTO = CNDPG.ID_FORMAPAGAMENTO_PARCELA_PADRAO
  LEFT JOIN TB_TIPO_DOCUMENTO TPDOC_ENTPD ON TPDOC_ENTPD.SQ_TIPO_DOCUMENTO = CNDPG.ID_TIPO_DOCUMENTO_ENTRADA_PADRAO
  LEFT JOIN TB_TIPO_DOCUMENTO TPDOC_PCLPD ON TPDOC_PCLPD.SQ_TIPO_DOCUMENTO = CNDPG.ID_TIPO_DOCUMENTO_PARCELA_PADRAO
  LEFT JOIN TB_OPCAO OPCAO_PCFJR ON OPCAO_PCFJR.SQ_OPCAO = CNDPG.ID_OPT_PERIODOCALCULOFINANCEIRO_JUROS
GO
ALTER PROCEDURE [dbo].[SP_MOVFINANCEIRA_QUITAR_CAD]
(
 @SQ_MOVFINANCEIRA INT
)
AS
BEGIN
  IF EXISTS(SELECT *
	           FROM TB_MOVFINANCEIRAPARCELA MFP
			        INNER JOIN TB_TIPO_DOCUMENTO TDC ON TDC.SQ_TIPO_DOCUMENTO = MFP.ID_TIPO_DOCUMENTO 
			       WHERE MFP.ID_MOVFINANCEIRA = @SQ_MOVFINANCEIRA
			         AND TDC.IC_COMPENSAR = 'N')
    BEGIN
			DECLARE @ID_EMPRESA INT
			DECLARE @ID_CONTAFINANCEIRA INT
			DECLARE @SQ_MOVFINANCEIRAPARCELA INT
			DECLARE @DT_PAGAMENTO DATE
			DECLARE @DT_LANCAMENTO DATETIME
			DECLARE @VL_PARCELA MONEY
			DECLARE @VL_PAGAMENTO MONEY

			DECLARE @SQ_PAGAMENTO INT
			DECLARE @SQ_PAGAMENTOITEM INT

			SET @DT_LANCAMENTO = GETDATE()

			SELECT @ID_EMPRESA = ID_EMPRESA,
						 @ID_CONTAFINANCEIRA = ISNULL(ID_CONTAFINANCEIRA_CREDITO, ID_CONTAFINANCEIRA_DEBITO),
			       @DT_PAGAMENTO = DT_MOVIMENTACAO
			 FROM TB_MOVFINANCEIRA
			 WHERE SQ_MOVFINANCEIRA = @SQ_MOVFINANCEIRA

		  EXEC SP_PAGAMENTO_CAD @SQ_PAGAMENTO OUT,
														@ID_EMPRESA,
														64,		/* Pagamento */
														@DT_LANCAMENTO,
														@DT_PAGAMENTO

			-- Relaciona as parcelas ao pagamento
		  DECLARE csrParcela CURSOR FOR
	     SELECT MFP.SQ_MOVFINANCEIRAPARCELA, MFP.VL_PARCELA
			  FROM TB_MOVFINANCEIRAPARCELA MFP
				WHERE MFP.ID_MOVFINANCEIRA = @SQ_MOVFINANCEIRA
				  AND MFP.ID_TIPO_DOCUMENTO = 1		/* Dinheiro */

		  OPEN csrParcela

		  IF @@FETCH_STATUS <> 0
		    FETCH NEXT FROM csrParcela INTO @SQ_MOVFINANCEIRAPARCELA, @VL_PARCELA

		  WHILE @@FETCH_STATUS = 0  
		    BEGIN
				  IF @SQ_MOVFINANCEIRAPARCELA IS NOT NULL
						EXEC SP_MOVFINANCEIRAPARCELA_PGT @SQ_MOVFINANCEIRAPARCELA, @SQ_PAGAMENTO, NULL, @VL_PARCELA, 0, 0, 0, 0, 0, 0, NULL, @DT_PAGAMENTO

		      FETCH NEXT FROM csrParcela INTO @SQ_MOVFINANCEIRAPARCELA, @VL_PARCELA
		    END

		  CLOSE csrParcela
		  DEALLOCATE csrParcela

			-- Inseri os itens do pagamento
	    SELECT @VL_PAGAMENTO = ISNULL(SUM(MFP.VL_PARCELA), 0)
			FROM TB_MOVFINANCEIRAPARCELA MFP
			 INNER JOIN TB_TIPO_DOCUMENTO TDC ON TDC.SQ_TIPO_DOCUMENTO = MFP.ID_TIPO_DOCUMENTO
			WHERE MFP.ID_MOVFINANCEIRA = @SQ_MOVFINANCEIRA
				AND TDC.IC_COMPENSAR = 'N'

			EXEC SP_PAGAMENTOITEM_CAD @SQ_PAGAMENTOITEM OUT,
																@SQ_PAGAMENTO,
																384,	-- Quitado
																NULL,
																1,		-- Dinheiro
																@ID_CONTAFINANCEIRA,
																NULL,
																NULL,
																NULL,
																@VL_PAGAMENTO

			EXEC SP_PAGAMENTO_COMPENSACAO_CAD @SQ_PAGAMENTOITEM,
			                                  @ID_CONTAFINANCEIRA,
                                        384,	-- Quitado
                                        @DT_PAGAMENTO,
                                        @DT_PAGAMENTO,
                                        @VL_PAGAMENTO,
                                        NULL

			EXEC SP_PAGAMENTOITEM_MOVFINANCEIRA_CAD @SQ_PAGAMENTOITEM

			EXEC SP_MOVFINANCEIRA_STATUS @SQ_MOVFINANCEIRA
		END
END
GO
ALTER TABLE TB_MOVFINANCEIRAPARCELA
 ADD ID_CONTAFINANCEIRA_COMPENSACAO INT
GO
ALTER PROCEDURE [dbo].[SP_MOVFINANCEIRAPARCELA_COMPENSACAO_CAD]
(
 @SQ_MOVFINANCEIRAPARCELA INT,
 @ID_CONTAFINANCEIRA INT,
 @DT_LANCAMENTO DATE,
 @DT_COMPENSACAO DATE,
 @VL_COMPENSACAO MONEY,
 @CM_COMPENSACAO VARCHAR(MAX)
)
AS
BEGIN
  DECLARE @ID_CONTAFINANCEIRA_CREDITO INT
  DECLARE @ID_CONTAFINANCEIRA_DEBITO INT
  DECLARE @VL_AUX MONEY
  DECLARE @ID_EMPRESA INT
  DECLARE @ID_OPT_TIPOMOVFINANCEIRA INT

	SELECT @ID_EMPRESA = MVF.ID_EMPRESA,
	       @ID_OPT_TIPOMOVFINANCEIRA = ID_OPT_TIPOMOVFINANCEIRA
	 FROM TB_MOVFINANCEIRAPARCELA MFP
	  INNER JOIN TB_MOVFINANCEIRA MVF ON MVF.SQ_MOVFINANCEIRA = MFP.ID_MOVFINANCEIRA
	 WHERE MFP.SQ_MOVFINANCEIRAPARCELA = @SQ_MOVFINANCEIRAPARCELA

	SELECT @DT_LANCAMENTO = ISNULL(@DT_LANCAMENTO, dbo.FC_DataContabil(@ID_EMPRESA))

  IF EXISTS(SELECT * FROM TB_MOVFINANCEIRAPARCELA
             WHERE SQ_MOVFINANCEIRAPARCELA = @SQ_MOVFINANCEIRAPARCELA
							AND ISNULL(IC_COMPENSADO, 'N') = 'N')
		BEGIN
			EXEC SP_MOVFINANCEIRA_FLUXOCAIXA_CAD @SQ_MOVFINANCEIRAPARCELA, 379, NULL, @DT_LANCAMENTO, @CM_COMPENSACAO, @VL_COMPENSACAO

			UPDATE TB_MOVFINANCEIRAPARCELA
			 SET ID_OPT_STATUS = 57,			
					 IC_COMPENSADO = 'S',
					 DT_COMPENSACAO = @DT_COMPENSACAO,
					 DT_QUITACAO = ISNULL(DT_QUITACAO, @DT_COMPENSACAO),
					 VL_QUITADO = ISNULL(VL_QUITADO, @VL_COMPENSACAO),
					 ID_CONTAFINANCEIRA_COMPENSACAO = @ID_CONTAFINANCEIRA
			 WHERE SQ_MOVFINANCEIRAPARCELA = @SQ_MOVFINANCEIRAPARCELA

			UPDATE DOF
			 SET ID_OPT_STATUS = 377
			 FROM TB_MOVFINANCEIRAPARCELA MFP
				INNER JOIN TB_DOCUMENTOFINANCEIRO DOF ON DOF.SQ_DOCUMENTOFINANCEIRO = MFP.ID_DOCUMENTOFINANCEIRO
			 WHERE MFP.SQ_MOVFINANCEIRAPARCELA = @SQ_MOVFINANCEIRAPARCELA

			SELECT @ID_CONTAFINANCEIRA_CREDITO = MVF.ID_CONTAFINANCEIRA_CREDITO,
             @ID_CONTAFINANCEIRA_DEBITO = MVF.ID_CONTAFINANCEIRA_DEBITO
       FROM TB_MOVFINANCEIRAPARCELA MFP
        INNER JOIN TB_MOVFINANCEIRA MVF ON MVF.SQ_MOVFINANCEIRA = MFP.ID_MOVFINANCEIRA
       WHERE MFP.SQ_MOVFINANCEIRAPARCELA = @SQ_MOVFINANCEIRAPARCELA
  
   	  IF @ID_CONTAFINANCEIRA_DEBITO IS NOT NULL
				BEGIN
					SET @VL_AUX = (0 - @VL_COMPENSACAO)

					EXEC SP_CONTAFINANCEIRA_SALDO_UPD @ID_CONTAFINANCEIRA_DEBITO, @VL_AUX
				END
			IF @ID_CONTAFINANCEIRA_CREDITO IS NOT NULL
				EXEC SP_CONTAFINANCEIRA_SALDO_UPD @ID_CONTAFINANCEIRA_CREDITO, @VL_COMPENSACAO
		END
  ELSE
    BEGIN
      RAISERROR('Já foi realizada a compensação dessa parcela', 16, 1)
	  RETURN
	END
END
GO
INSERT INTO TB_SEG_PERMISSAO_TIPOPERMISSAO (SQ_PERMISSAO_TIPOPERMISSAO, ID_PERMISSAO, ID_TIPOPERMISSAO) VALUES (238, 38, 1)
INSERT INTO TB_SEG_PERMISSAO_TIPOPERMISSAO (SQ_PERMISSAO_TIPOPERMISSAO, ID_PERMISSAO, ID_TIPOPERMISSAO) VALUES (239, 38, 2)
INSERT INTO TB_SEG_PERMISSAO_TIPOPERMISSAO (SQ_PERMISSAO_TIPOPERMISSAO, ID_PERMISSAO, ID_TIPOPERMISSAO) VALUES (240, 38, 3)
GO
ALTER VIEW [dbo].[VW_MOVFINANCEIRAPARCELA]
AS
SELECT MFP.ID_MOVFINANCEIRA, MFN.ID_SEGMENTO, MFN.ID_EMPRESA, MFN.ID_OPT_PERIODOCALCULOFINANCEIRO_JUROS,
       MFN.ID_OPT_PERIODOCALCULOFINANCEIRO_DESCONTO, MFP.SQ_MOVFINANCEIRAPARCELA, CONCAT(MFN.CD_MOVFINANCEIRA, '-', MFP.CD_PARCELA) CD_MOVFINANCEIRA_PARCELA,
	   MFP.CD_PARCELA, MFP.CD_DOCUMENTO,
	   MFN.ID_CONTAFINANCEIRA_CREDITO, MFN.ID_CONTAFINANCEIRA_DEBITO, MFP.ID_FORMAPAGAMENTO_PREFERENCIAL, STS.SQ_OPCAO ID_OPT_STATUS,
	   STS.NO_OPCAO NO_OPT_STATUS, STS.CD_OPCAO CD_OPT_STATUS, OPCAO_PCFJR.NO_OPCAO NO_OPT_PERIODOCALCULOFINANCEIRO_JUROS,
	   OPCAO_PCFJR.NO_OPCAO_ABREVIADO NO_OPT_PERIODOCALCULOFINANCEIRO_JUROS_ABREVIADO,
	   OPCAO_PCFDC.NO_OPCAO NO_OPT_PERIODOCALCULOFINANCEIRO_DESCONTO, OPCAO_PCFDC.NO_OPCAO_ABREVIADO NO_OPT_PERIODOCALCULOFINANCEIRO_DESCONTO_ABREVIADO,
	   CCC.NO_CONTAFINANCEIRA NO_CONTAFINANCEIRA_CREDITO, CCD.NO_CONTAFINANCEIRA NO_CONTAFINANCEIRA_DEBITO,  MFN.ID_PESSOA, PES.NO_PESSOA, PES.NO_PESSOA_RELATORIO,
	   MFN.CD_MOVFINANCEIRA, MFN.DS_MOVFINANCEIRA, MFP.ID_TIPO_DOCUMENTO, MFP.ID_DOCUMENTOFINANCEIRO, TDC.NO_TIPO_DOCUMENTO, MFN.DT_MOVIMENTACAO, MFP.DT_VENCIMENTO,
	   MFP.DT_QUITACAO, MFP.VL_PARCELA, MFP.VL_QUITADO, MFN.PC_JUROS, MFN.PC_MULTA, MFP.VL_JUROS, MFP.VL_ACRESCIMO_PAGTO, MFP.VL_DESCONTO_PAGTO, MFP.VL_DESCONTO,
	   ISNULL(DEVOL.VL_DEVOLUCAO, 0) VL_DEVOLUCAO, MFN.VL_MULTA, MFN.PC_DESCONTO,
	   dbo.FC_CalculoPorcentagem(IIF(STS.CD_OPCAO = 'F', 0, IIF(MFP.VL_QUITADO > dbo.FC_MovFinanceiraParcela_Valor(MFP.SQ_MOVFINANCEIRAPARCELA), 0,
	   dbo.FC_MovFinanceiraParcela_Valor(MFP.SQ_MOVFINANCEIRAPARCELA) - MFP.VL_QUITADO)), ISNULL(PSEMP.PC_PROFISSIONAL_RETEMIMPOSTO, 0)) VL_CALC_IMPOSTO_RETIDO,
	   dbo.FC_CalculoFinanceiro_Calcular(MFN.ID_OPT_PERIODOCALCULOFINANCEIRO_DESCONTO,MFN.PC_DESCONTO, (MFP.VL_PARCELA - MFP.VL_QUITADO - ISNULL(MFP.VL_DESCONTO, 0)), MFP.DT_VENCIMENTO, GETDATE(), 'D') VL_CALC_DESCONTO,
	   IIF(STS.CD_OPCAO = 'F', 0, IIF(MFP.VL_QUITADO > dbo.FC_MovFinanceiraParcela_Valor(MFP.SQ_MOVFINANCEIRAPARCELA), 0, dbo.FC_MovFinanceiraParcela_Valor(MFP.SQ_MOVFINANCEIRAPARCELA) - MFP.VL_QUITADO)) VL_DEBITO,
	   IIF(MFP.ID_OPT_STATUS IN (60), 0, dbo.FC_ValorPositivo(DATEDIFF(DAY, MFP.DT_VENCIMENTO, ISNULL(ISNULL(MFG.DT_MOVIMENTACAO, MFP.DT_QUITACAO), GETDATE())), 0)) QT_DIAS_ATRASO,
	   IIF(STS.CD_OPCAO = 'F', 0, dbo.FC_CalculoFinanceiro_Calcular(MFN.ID_OPT_PERIODOCALCULOFINANCEIRO_JUROS, MFN.PC_JUROS, dbo.FC_MovFinanceiraParcela_Valor(MFP.SQ_MOVFINANCEIRAPARCELA) - MFP.VL_QUITADO, MFP.DT_VENCIMENTO, GETDATE(), 'J')) VL_CALC_JUROS,
	   IIF(STS.CD_OPCAO = 'F', 0, IIF(DATEDIFF(DAY, MFP.DT_VENCIMENTO, GETDATE()) <= 0, 0, MFN.VL_MULTA - MFP.VL_MULTA)) VL_CALC_MULTA,
	   MFP.DS_EMITENTE, MFP.DT_COMPENSACAO, MFP.IC_COMPENSADO, MFN.ID_OPT_TIPOMOVFINANCEIRA, TMV.CD_OPCAO CD_OPT_TIPOMOVFINANCEIRA,
	   TMV.NO_OPCAO NO_OPT_TIPOMOVFINANCEIRA, TMV.ID_TIPO_OPCAO ID_OPT_TIPOMOVFINANCEIRA_GRUPO, MFP.ID_APROVADOR_DESCONTO,
	   IIF(MFP.ID_OPT_STATUS = 57, '#1E90FF',
	       IIF(MFP.ID_OPT_STATUS = 58, '#00BFFF',
  		       IIF(MFP.ID_OPT_STATUS = 59, '#87CEEB',
			       IIF(MFP.ID_OPT_STATUS = 60, '#800080',
					   IIF(MFP.ID_OPT_STATUS = 61, '#FFA500',
						   IIF(MFP.ID_OPT_STATUS = 65, '#1E90FF',
							   IIF(MFP.ID_OPT_STATUS = 381, '#A0522D', '#FFFFFF'))))))) CD_STATUS_COR,
	   MFG.CD_MOVFINANCEIRA CD_MOVFINANCEIRAGERADA,
	   MFP.ID_MOVFINANCEIRAGERADA,
	   MFP.PC_TAXA_COMPENSACAO,
	   ISNULL(MFP.VL_TAXA_COMPENSACAO, dbo.FC_CalculoPorcentagem(MFP.VL_PARCELA, ISNULL(MFP.PC_TAXA_COMPENSACAO, 0))) VL_TAXA_COMPENSACAO,
	   MFP.ID_CONTAFINANCEIRA_COMPENSACAO,
	   CFC.NO_CONTAFINANCEIRA NO_CONTAFINANCEIRA_COMPENSACAO
 FROM TB_MOVFINANCEIRAPARCELA MFP
  INNER JOIN TB_MOVFINANCEIRA MFN ON MFN.SQ_MOVFINANCEIRA = MFP.ID_MOVFINANCEIRA
  INNER JOIN TB_TIPO_DOCUMENTO TDC ON TDC.SQ_TIPO_DOCUMENTO = MFP.ID_TIPO_DOCUMENTO
  INNER JOIN TB_OPCAO STS ON STS.SQ_OPCAO = MFP.ID_OPT_STATUS
  INNER JOIN TB_OPCAO TMV ON TMV.SQ_OPCAO = MFN.ID_OPT_TIPOMOVFINANCEIRA
  LEFT JOIN TB_PESSOA_EMPRESA PSEMP ON PSEMP.ID_PESSOA = MFN.ID_PESSOA
                                    AND PSEMP.ID_EMPRESA = 2
   LEFT JOIN TB_OPCAO OPCAO_PCFJR ON OPCAO_PCFJR.SQ_OPCAO = MFN.ID_OPT_PERIODOCALCULOFINANCEIRO_JUROS
   LEFT JOIN TB_OPCAO OPCAO_PCFDC ON OPCAO_PCFDC.SQ_OPCAO = MFN.ID_OPT_PERIODOCALCULOFINANCEIRO_DESCONTO
   LEFT JOIN VW_PESSOA_NOME_RELATORIO PES ON PES.SQ_PESSOA = MFN.ID_PESSOA
					                     AND PES.ID_EMPRESA = MFN.ID_EMPRESA
   LEFT JOIN TB_CONTAFINANCEIRA CCC ON CCC.SQ_CONTAFINANCEIRA = MFN.ID_CONTAFINANCEIRA_CREDITO
   LEFT JOIN TB_CONTAFINANCEIRA CCD ON CCD.SQ_CONTAFINANCEIRA = MFN.ID_CONTAFINANCEIRA_DEBITO
   LEFT JOIN TB_CONTAFINANCEIRA CFC ON CFC.SQ_CONTAFINANCEIRA = MFP.ID_CONTAFINANCEIRA_COMPENSACAO
   LEFT JOIN TB_MOVFINANCEIRA MFG ON MFG.SQ_MOVFINANCEIRA = MFP.ID_MOVFINANCEIRAGERADA
   LEFT JOIN (SELECT ID_MOVFINANCEIRAPARCELA,
                     SUM(VL_PAGAMENTO) VL_DEVOLUCAO
               FROM TB_MOVFINANCEIRAPAGTO PIMF
			    INNER JOIN TB_PAGAMENTO PAGT ON PAGT.SQ_PAGAMENTO = PIMF.ID_PAGAMENTO
				                            AND PAGT.DT_EXCLUSAO IS NULL
											AND PAGT.ID_OPT_TIPOPAGAMENTO = 815 /* Devolução a Cliente */
			   GROUP BY ID_MOVFINANCEIRAPARCELA) DEVOL ON DEVOL.ID_MOVFINANCEIRAPARCELA = MFP.SQ_MOVFINANCEIRAPARCELA
GO
ALTER TABLE TB_EMPRESA
 ADD DS_MENSAGEM_IMPRESSAO_SENHA VARCHAR(200)
GO
ALTER VIEW [dbo].[VW_EMPRESA]
AS
SELECT EMP.ID_EMPRESA,
			 EMP.ID_TABELAPRECO_PADRAO,
			 EMP.ID_EMPRESA_MATRIZ,
			 EMP.ID_MOEDA_PADRAO,
			 EMP.ID_OPT_TIPOCONTROLECONTABIL,
			 EMP.ID_NATUREZAOPERACAO_VENDA,
			 EMP.ID_OPT_METODOCALCULOPRECO,
			 EMP.ID_OPT_CRT,
 			 EMP.ID_OPT_CRT_ISSQN,
			 EMP.ID_OPT_RATEIO_ISSQN,
			 EMP.ID_TRANSACAOESTOQUE_PADRAO_COMPRAS,
			 EMP.ID_TRANSACAOESTOQUE_PADRAO_VENDAS,
			 EMP.ID_PLANOCONTAS_PADRAO_RECEBIMENTO,
			 EMP.ID_MODELODOCUMENTO_RECEITA_PADRAO,
			 EMP.ID_MODELODOCUMENTO_ANAMNESE_PADRAO,
			 EMP.ID_MODELODOCUMENTO_EVOLUCAO_PADRAO,
			 EMP.ID_MODELODOCUMENTO_RECIBO_PADRAO,
			 EMP.ID_QUESTIONARIO_ANAMNESE_PADRAO,
			 EMP.ID_TIPO_CONSULTA_RETORNO,
			 EMP.ID_TIPO_CONSULTA_VENDA,
			 PES.ID_TIPO_PESSOA,
			 EMP.ID_TABELAPROCEDIMENTO_PADRAO,
			 EMP.ID_EQUIPAMENTO_PROCESSAMENTO_FISCAL,
			 EMP.ID_ORDEMSERVICO_OPT_TIPO_ORDEMSERVICO_PADRAO,
			 EMP.ID_ORDEMSERVICO_TABELAPRECO_PADRAO,
			 EMP.ID_SEGMENTO_CRCP_PADRAO,
			 EMP.ID_CANALNEGOCIO_PADRAO_VENDA,
			 EMP.ID_CONDICAOPAGAMENTO_RECEBIMENTO_PADRAO,
			 EMP.ID_CONDICAOPAGAMENTO_VENDA_PADRAO,
			 EMP.ID_CONTAFINANCEIRA_PADRAO_VENDA,
			 EMP.ID_CONTAFINANCEIRA_TESOURARIA,
			 EMP.ID_TIPO_DOCUMENTO_PADRAO_VENDA,
			 EMP.ID_PESSOA_RESPONSAVEL,
			 EMP.ID_PESSOA_RESPONSAVELTECNICO,
			 EMP.ID_PESSOA_RESPONSAVELCONTABIL,
			 EMP.ID_PLANOCONTAS_PADRAO_TAXA_COMPENSACAO,
			 EMP.ID_CONVENIO_PADRAO,
			 EDR.ID_CIDADE,
			 EDR.ID_UF,
			 EDR.ID_PAIS,
			 PES.ID_OPT_PJ_CONTRIBUICAO_ICMS,
			 EDR.CD_UF,
			 PES.NO_PESSOA AS NO_EMPRESA,
			 TPP.NO_TIPO_PESSOA, 
			 NOV.NO_NATUREZAOPERACAO NO_NATUREZAOPERACAO_VENDA,
			 CNG.NO_CANALNEGOCIO NO_CANALNEGOCIO_PADRAO_VENDA,
			 TBP.NO_TABELAPRECO NO_TABELAPRECO_PADRAO,
			 MDP.NO_MOEDA NO_MOEDA_PADRAO,
			 OPCAO_MCLPC.NO_OPCAO NO_OPT_METODOCALCULOPRECO,
			 OPCAO_TPOCTC.NO_OPCAO NO_OPT_TIPOCONTROLECONTABIL,
			 OPCAO_CRTBT.NO_OPCAO NO_OPT_CRT,
			 TPC.NO_TRANSACAOESTOQUE NO_TRANSACAOESTOQUE_PADRAO_COMPRAS,
			 PPR.NO_PLANOCONTAS NO_PLANOCONTAS_PADRAO_RECEBIMENTO,
			 RPS.NO_PESSOA NO_PESSOA_RESPONSAVEL,
			 PES.DT_NASC_ABERTURA AS DT_ABERTURA,
			 PES.CD_CPF_CNPJ AS CD_CNPJ,
			 PES.NO_FANTASIA_REDUZIDO,
			 EMP.CD_CNES,
			 PES.CD_PJ_IE,
			 PES.CD_PJ_IM, 
			 EMP.CD_CNAE,
			 PES.ID_OPT_ATIVO,
			 EMP.DS_PATH_REPOSITORIO_ARQUIVO,
			 PES.DS_PATH_IMAGEM,
			 EMP.NR_ATENDIMENTO_INTERVALO,
			 EMP.HR_ATENDIMENTO_INICIO,
			 EMP.HR_ATENDIMENTO_SAIDAREFEICAO,
			 EMP.HR_ATENDIMENTO_RETORNOREFEICAO,
			 EMP.HR_ATENDIMENTO_FIM,
			 EMP.IC_LISTARTODOS_PROCEDIMENTO,
			 EMP.IC_ORDEMSERVICO_LISTAGEMPRODUTOMANUTENCAO,
			 EMP.IC_ORDEMSERVICO_DESCRICAOPRODUTOMANUTENCAO,
			 EMP.IC_ORDEMSERVICO_DESCRICAOPRODUTOMANUTENCAO_1OPCAO,
			 EMP.NR_CASASDECIMAIS_VALORES,
			 EMP.NR_DIA_VALIDADEORCAMENTO,
			 EMP.NR_DIA_VALIDADEPEDIDO,
			 EMP.CADASTROTELEFONE_DDD_PADRAO,
			 EMP.CADASTROTELEFONE_MASCARA,
			 EMP.IC_NECESSITA_ANAMNESE_EVOLUCAO,
			 EMP.IC_QUITAR_PROVISIONADO,
			 EMP.IC_PROVISIONADO_POR_PADRAO,
			 EMP.IC_DIAUTIL_DOM,
			 EMP.IC_DIAUTIL_SEG,
			 EMP.IC_DIAUTIL_TER,
			 EMP.IC_DIAUTIL_QUA,
			 EMP.IC_DIAUTIL_QUI,
			 EMP.IC_DIAUTIL_SEX,
			 EMP.IC_DIAUTIL_SAB,
			 EMP.DS_MENSAGEM_IMPRESSAO_SENHA
 FROM TB_EMPRESA EMP
  INNER JOIN TB_PESSOA PES ON EMP.ID_EMPRESA = PES.SQ_PESSOA
  INNER JOIN TB_TIPO_PESSOA TPP ON PES.ID_TIPO_PESSOA = TPP.SQ_TIPO_PESSOA
   LEFT JOIN TB_TABELAPRECO TBP ON TBP.SQ_TABELAPRECO = EMP.ID_TABELAPRECO_PADRAO
   LEFT JOIN TB_NATUREZAOPERACAO NOV ON NOV.SQ_NATUREZAOPERACAO = EMP.ID_NATUREZAOPERACAO_VENDA
   LEFT JOIN TB_CANALNEGOCIO CNG ON CNG.SQ_CANALNEGOCIO = EMP.ID_CANALNEGOCIO_PADRAO_VENDA
   LEFT JOIN TB_MOEDA MDP ON MDP.SQ_MOEDA = EMP.ID_MOEDA_PADRAO
   LEFT JOIN TB_PESSOA RPS ON RPS.SQ_PESSOA = EMP.ID_PESSOA_RESPONSAVEL
   LEFT JOIN TB_OPCAO OPCAO_TPOCTC ON OPCAO_TPOCTC.SQ_OPCAO = EMP.ID_OPT_TIPOCONTROLECONTABIL
   LEFT JOIN TB_OPCAO OPCAO_MCLPC ON OPCAO_MCLPC.SQ_OPCAO = EMP.ID_OPT_METODOCALCULOPRECO
   LEFT JOIN TB_OPCAO OPCAO_CRTBT ON OPCAO_CRTBT.SQ_OPCAO = EMP.ID_OPT_CRT
   LEFT JOIN TB_TRANSACAOESTOQUE TPC ON TPC.SQ_TRANSACAOESTOQUE = EMP.ID_TRANSACAOESTOQUE_PADRAO_COMPRAS
   LEFT JOIN TB_PLANOCONTAS PPR ON PPR.SQ_PLANOCONTAS = EMP.ID_PLANOCONTAS_PADRAO_RECEBIMENTO
   LEFT JOIN VW_ENDERECO_PRIMEIRO EDR ON EDR.ID_PESSOA = EMP.ID_EMPRESA
									 AND EDR.ID_TIPO_ENDERECO = 2
GO
ALTER PROCEDURE [dbo].[SP_EMPRESA_CAD]
	@ID_EMPRESA INT,
	@ID_TABELAPRECO_PADRAO INT,
	@ID_TRANSACAOESTOQUE_PADRAO_COMPRAS INT,
	@ID_TRANSACAOESTOQUE_PADRAO_VENDAS INT,
	@ID_EMPRESA_MATRIZ INT,
	@ID_PLANOCONTAS_PADRAO_RECEBIMENTO INT,
	@ID_PLANOCONTAS_PADRAO_TAXA_COMPENSACAO INT,
	@ID_MODELODOCUMENTO_RECIBO_PADRAO INT,
	@ID_SEGMENTO_CRCP_PADRAO INT,
	@ID_CANALNEGOCIO_PADRAO_VENDA INT,
	@ID_CONDICAOPAGAMENTO_RECEBIMENTO_PADRAO INT,
	@ID_CONDICAOPAGAMENTO_VENDA_PADRAO INT,
	@ID_TIPO_DOCUMENTO_PADRAO_VENDA INT,
	@ID_CONTAFINANCEIRA_PADRAO_VENDA INT,
	@ID_CONTAFINANCEIRA_TESOURARIA INT,
	@ID_PESSOA_RESPONSAVEL INT,
	@ID_PESSOA_RESPONSAVELTECNICO INT,
	@ID_PESSOA_RESPONSAVELCONTABIL INT,
	@ID_CONVENIO_PADRAO INT,
	@DS_PATH_REPOSITORIO_ARQUIVO VARCHAR(255),
	@CADASTROTELEFONE_DDD_PADRAO VARCHAR(5),
	@NR_CASASDECIMAIS_VALORES INT,
	@NR_DIA_VALIDADEORCAMENTO INT,
	@NR_DIA_VALIDADEPEDIDO INT,
	@NR_DIA_PAGTO_PRESTADORSERVICOMEDICO INT,
	@IC_NOME_FANTASIA_RELATORIOS CHAR(1),
	@IC_QUITAR_PROVISIONADO CHAR(1),
	@IC_PROVISIONADO_POR_PADRAO CHAR(1),
	@IM_LOGOTIPO IMAGE,
	@IC_DIAUTIL_DOM CHAR(1),
	@IC_DIAUTIL_SEG CHAR(1),
	@IC_DIAUTIL_TER CHAR(1),
	@IC_DIAUTIL_QUA CHAR(1),
	@IC_DIAUTIL_QUI CHAR(1),
	@IC_DIAUTIL_SEX CHAR(1),
	@IC_DIAUTIL_SAB CHAR(1),
	@DS_RODAPE_RELATORIO NVARCHAR(500),
    @DS_MENSAGEM_IMPRESSAO_SENHA VARCHAR(200)
AS
BEGIN
  IF NOT EXISTS(SELECT * FROM TB_EMPRESA WHERE ID_EMPRESA = @ID_EMPRESA)
		INSERT INTO TB_EMPRESA
		(ID_EMPRESA, ID_TABELAPRECO_PADRAO, ID_EMPRESA_MATRIZ, ID_TRANSACAOESTOQUE_PADRAO_COMPRAS,
		 ID_TRANSACAOESTOQUE_PADRAO_VENDAS, ID_PLANOCONTAS_PADRAO_RECEBIMENTO, ID_PLANOCONTAS_PADRAO_TAXA_COMPENSACAO, ID_MODELODOCUMENTO_RECIBO_PADRAO,
		 ID_SEGMENTO_CRCP_PADRAO, ID_CANALNEGOCIO_PADRAO_VENDA, ID_CONDICAOPAGAMENTO_RECEBIMENTO_PADRAO, ID_CONVENIO_PADRAO,
		 ID_CONDICAOPAGAMENTO_VENDA_PADRAO, ID_TIPO_DOCUMENTO_PADRAO_VENDA, ID_CONTAFINANCEIRA_PADRAO_VENDA,
		 ID_CONTAFINANCEIRA_TESOURARIA, ID_PESSOA_RESPONSAVEL, ID_PESSOA_RESPONSAVELTECNICO, ID_PESSOA_RESPONSAVELCONTABIL,
		 DS_PATH_REPOSITORIO_ARQUIVO, CADASTROTELEFONE_DDD_PADRAO, NR_CASASDECIMAIS_VALORES, NR_DIA_VALIDADEORCAMENTO, IM_LOGOTIPO,
		 NR_DIA_VALIDADEPEDIDO, IC_NOME_FANTASIA_RELATORIOS, IC_QUITAR_PROVISIONADO, IC_PROVISIONADO_POR_PADRAO,
		 IC_DIAUTIL_DOM, IC_DIAUTIL_SEG, IC_DIAUTIL_TER, IC_DIAUTIL_QUA, IC_DIAUTIL_QUI, IC_DIAUTIL_SEX,
		 IC_DIAUTIL_SAB, DS_RODAPE_RELATORIO, NR_DIA_PAGTO_PRESTADORSERVICOMEDICO, DS_MENSAGEM_IMPRESSAO_SENHA)
		VALUES
		(@ID_EMPRESA, @ID_TABELAPRECO_PADRAO, @ID_EMPRESA_MATRIZ, @ID_TRANSACAOESTOQUE_PADRAO_COMPRAS,
		 @ID_TRANSACAOESTOQUE_PADRAO_VENDAS, @ID_PLANOCONTAS_PADRAO_RECEBIMENTO, @ID_PLANOCONTAS_PADRAO_TAXA_COMPENSACAO, @ID_MODELODOCUMENTO_RECIBO_PADRAO,
		 @ID_SEGMENTO_CRCP_PADRAO, @ID_CANALNEGOCIO_PADRAO_VENDA, @ID_CONDICAOPAGAMENTO_RECEBIMENTO_PADRAO, @ID_CONVENIO_PADRAO,
		 @ID_CONDICAOPAGAMENTO_VENDA_PADRAO, @ID_TIPO_DOCUMENTO_PADRAO_VENDA, @ID_CONTAFINANCEIRA_PADRAO_VENDA,
		 @ID_CONTAFINANCEIRA_TESOURARIA, @ID_PESSOA_RESPONSAVEL, @ID_PESSOA_RESPONSAVELTECNICO, @ID_PESSOA_RESPONSAVELCONTABIL,
		 @DS_PATH_REPOSITORIO_ARQUIVO,@CADASTROTELEFONE_DDD_PADRAO, @NR_CASASDECIMAIS_VALORES,	@NR_DIA_VALIDADEORCAMENTO, @IM_LOGOTIPO,
		 @NR_DIA_VALIDADEPEDIDO, @IC_NOME_FANTASIA_RELATORIOS, @IC_QUITAR_PROVISIONADO, @IC_PROVISIONADO_POR_PADRAO,
		 @IC_DIAUTIL_DOM, @IC_DIAUTIL_SEG, @IC_DIAUTIL_TER,	@IC_DIAUTIL_QUA, @IC_DIAUTIL_QUI, @IC_DIAUTIL_SEX,
		 @IC_DIAUTIL_SAB, @DS_RODAPE_RELATORIO, @NR_DIA_PAGTO_PRESTADORSERVICOMEDICO, @DS_MENSAGEM_IMPRESSAO_SENHA)
  ELSE 
		UPDATE TB_EMPRESA
		 SET ID_TABELAPRECO_PADRAO = @ID_TABELAPRECO_PADRAO,
		     ID_TRANSACAOESTOQUE_PADRAO_COMPRAS = @ID_TRANSACAOESTOQUE_PADRAO_COMPRAS,
			 ID_TRANSACAOESTOQUE_PADRAO_VENDAS = @ID_TRANSACAOESTOQUE_PADRAO_VENDAS,
			 ID_EMPRESA_MATRIZ = @ID_EMPRESA_MATRIZ,
			 ID_PLANOCONTAS_PADRAO_RECEBIMENTO = @ID_PLANOCONTAS_PADRAO_RECEBIMENTO,
			 ID_PLANOCONTAS_PADRAO_TAXA_COMPENSACAO = @ID_PLANOCONTAS_PADRAO_TAXA_COMPENSACAO,
			 ID_MODELODOCUMENTO_RECIBO_PADRAO = @ID_MODELODOCUMENTO_RECIBO_PADRAO,
			 ID_SEGMENTO_CRCP_PADRAO = @ID_SEGMENTO_CRCP_PADRAO,
			 ID_CANALNEGOCIO_PADRAO_VENDA = @ID_CANALNEGOCIO_PADRAO_VENDA,
			 ID_CONDICAOPAGAMENTO_RECEBIMENTO_PADRAO = @ID_CONDICAOPAGAMENTO_RECEBIMENTO_PADRAO,
			 ID_CONDICAOPAGAMENTO_VENDA_PADRAO = @ID_CONDICAOPAGAMENTO_VENDA_PADRAO,
		     ID_TIPO_DOCUMENTO_PADRAO_VENDA = @ID_TIPO_DOCUMENTO_PADRAO_VENDA,
			 ID_CONTAFINANCEIRA_PADRAO_VENDA = @ID_CONTAFINANCEIRA_PADRAO_VENDA,
			 ID_CONTAFINANCEIRA_TESOURARIA = @ID_CONTAFINANCEIRA_TESOURARIA,
			 ID_PESSOA_RESPONSAVEL = @ID_PESSOA_RESPONSAVEL,
			 ID_PESSOA_RESPONSAVELTECNICO = @ID_PESSOA_RESPONSAVELTECNICO,
			 ID_PESSOA_RESPONSAVELCONTABIL = @ID_PESSOA_RESPONSAVELCONTABIL,
			 ID_CONVENIO_PADRAO = @ID_CONVENIO_PADRAO,
			 DS_PATH_REPOSITORIO_ARQUIVO = @DS_PATH_REPOSITORIO_ARQUIVO,
			 CADASTROTELEFONE_DDD_PADRAO = @CADASTROTELEFONE_DDD_PADRAO,
			 NR_CASASDECIMAIS_VALORES = @NR_CASASDECIMAIS_VALORES,
			 NR_DIA_VALIDADEORCAMENTO = @NR_DIA_VALIDADEORCAMENTO,
			 NR_DIA_VALIDADEPEDIDO = @NR_DIA_VALIDADEPEDIDO,
			 NR_DIA_PAGTO_PRESTADORSERVICOMEDICO = @NR_DIA_PAGTO_PRESTADORSERVICOMEDICO,
			 IC_NOME_FANTASIA_RELATORIOS = @IC_NOME_FANTASIA_RELATORIOS,
			 IC_QUITAR_PROVISIONADO = @IC_QUITAR_PROVISIONADO,
			 IC_PROVISIONADO_POR_PADRAO = @IC_PROVISIONADO_POR_PADRAO,
			 IM_LOGOTIPO = ISNULL(@IM_LOGOTIPO, IM_LOGOTIPO),
			 IC_DIAUTIL_DOM = @IC_DIAUTIL_DOM,
			 IC_DIAUTIL_SEG = @IC_DIAUTIL_SEG,
			 IC_DIAUTIL_TER = @IC_DIAUTIL_TER,
			 IC_DIAUTIL_QUA = @IC_DIAUTIL_QUA,
			 IC_DIAUTIL_QUI = @IC_DIAUTIL_QUI,
			 IC_DIAUTIL_SEX = @IC_DIAUTIL_SEX,
			 IC_DIAUTIL_SAB = @IC_DIAUTIL_SAB,
			 DS_RODAPE_RELATORIO = @DS_RODAPE_RELATORIO,
			 DS_MENSAGEM_IMPRESSAO_SENHA = @DS_MENSAGEM_IMPRESSAO_SENHA
		 WHERE ID_EMPRESA = @ID_EMPRESA
END