INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (791, 120, 'Clínica\Consulta de Agendamento Disponibilidade', 'S')
GO
INSERT INTO TB_CONFIG_TELA (ID_TELA, DS_PATH_IMAGEM_FUNDO) VALUES (791, 'Formulários\Clínica\ConsultaAgendamentoDisponibilidade.jpg')
GO
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (792, 115, 'Revisões', 'S')
GO
CREATE FUNCTION dbo.FC_DATA_LISTARPERIODO
(
 @DATA_INICIAL DATE,
 @DATA_FINAL DATE
)
RETURNS @TB_RETORNO TABLE
(
 DATA DATE
)
AS
BEGIN
  DECLARE @CONT INT

	SELECT @CONT = 0

	WHILE @CONT <= DATEDIFF(DAY, @DATA_INICIAL, @DATA_FINAL)
		BEGIN
			INSERT INTO @TB_RETORNO (DATA) VALUES (DATEADD(DAY, @CONT, @DATA_INICIAL))

			SET @CONT = @CONT + 1
		END

	RETURN
END