CREATE TABLE dbo.TB_CONVENIO_PROCEDIMENTO
	(
	SQ_CONVENIO_PROCEDIMENTO int NOT NULL IDENTITY (1, 1),
	ID_PROCEDIMENTO INT NOT NULL,
	ID_PESSOA_PROFISSIONAL INT NOT NULL,
	VL_PROCEDIMENTO MONEY NOT NULL,
	VL_REPASSE MONEY,
	PC_REPASSE DECIMAL(18, 5),
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.TB_CONVENIO_PROCEDIMENTO
 ADD CONSTRAINT	PK_CONVENIO_PROCEDIMENTO PRIMARY KEY CLUSTERED 
	(
	 SQ_CONVENIO_PROCEDIMENTO
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.TB_CONVENIO_PROCEDIMENTO
 ADD CONSTRAINT	FK_TBPRC_PROCE FOREIGN KEY (ID_PROCEDIMENTO)
		 REFERENCES dbo.TB_PROCEDIMENTO (SQ_PROCEDIMENTO)
GO
ALTER TABLE dbo.TB_CONVENIO_PROCEDIMENTO
 ADD CONSTRAINT	FK_TBPRC_PESSO FOREIGN KEY (ID_PESSOA_PROFISSIONAL)
		 REFERENCES dbo.TB_PESSOA (SQ_PESSOA)
GO
ALTER TABLE TB_PROCEDIMENTO
 ADD ID_OPT_TIPOPROCEDIMENTO INT
GO
ALTER TABLE dbo.TB_PROCEDIMENTO
 ADD CONSTRAINT	FK_PROCE_OPCAO_TPPCD FOREIGN KEY (ID_OPT_TIPOPROCEDIMENTO)
		 REFERENCES dbo.TB_OPCAO (SQ_OPCAO)
GO
ALTER TABLE dbo.TB_CONVENIO_PROCEDIMENTO
 ADD CONSTRAINT	FK_TBPRC_PROCE FOREIGN KEY (ID_PROCEDIMENTO)
		 REFERENCES dbo.TB_PROCEDIMENTO (SQ_PROCEDIMENTO)
GO
ALTER TABLE TB_CONVENIO_PROCEDIMENTO
 ADD ID_CONVENIO INT NOT NULL
GO
ALTER TABLE dbo.TB_CONVENIO_PROCEDIMENTO
 ADD CONSTRAINT	FK_TBPRC_CONVE FOREIGN KEY (ID_CONVENIO)
		 REFERENCES dbo.TB_CONVENIO (SQ_CONVENIO)
GO
INSERT INTO TB_TIPO_OPCAO (SQ_TIPO_OPCAO, NO_TIPO_OPCAO) VALUES (115, 'Tipo de Procedimento')
GO
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (726, 115, 'Procedimento', 'S') 
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (727, 115, 'Exame', 'S')
GO
UPDATE TB_PROCEDIMENTO SET ID_OPT_TIPOPROCEDIMENTO = 726
GO
ALTER TABLE TB_PROCEDIMENTO
 ALTER COLUMN ID_OPT_TIPOPROCEDIMENTO INT NOT NULL
GO
ALTER PROCEDURE [dbo].[SP_PROCEDIMENTO_CAD]
(
 @SQ_PROCEDIMENTO INT OUTPUT,
 @ID_TABELAPROCEDIMENTO INT,
 @ID_OPT_TIPOPROCEDIMENTO INT,
 @CD_PROCEDIMENTO CHAR(11),
 @NO_PROCEDIMENTO VARCHAR(100),
 @IC_ATIVO CHAR(1)
)
AS
BEGIN
  IF ISNULL(@SQ_PROCEDIMENTO, 0) = 0
    BEGIN
      INSERT INTO TB_PROCEDIMENTO
			(ID_TABELAPROCEDIMENTO, ID_OPT_TIPOPROCEDIMENTO, CD_PROCEDIMENTO, NO_PROCEDIMENTO, IC_ATIVO)
			VALUES
			(@ID_TABELAPROCEDIMENTO, @ID_OPT_TIPOPROCEDIMENTO, @CD_PROCEDIMENTO, @NO_PROCEDIMENTO, @IC_ATIVO)
	  
			SELECT @SQ_PROCEDIMENTO = @@IDENTITY
		END
  ELSE
    UPDATE TB_PROCEDIMENTO
		 SET ID_TABELAPROCEDIMENTO = @ID_TABELAPROCEDIMENTO,
				 ID_OPT_TIPOPROCEDIMENTO = @ID_OPT_TIPOPROCEDIMENTO,
				 CD_PROCEDIMENTO = @CD_PROCEDIMENTO,
				 NO_PROCEDIMENTO = @NO_PROCEDIMENTO,
				 IC_ATIVO = @IC_ATIVO
		 WHERE SQ_PROCEDIMENTO = @SQ_PROCEDIMENTO

  RETURN
END
GO
ALTER TABLE TB_CONVENIO_PROCEDIMENTO
 ADD QT_DIAS_REPASSE INT NOT NULL,
		 CM_OBSERVACAO VARCHAR(500),
     IC_ATIVO CHAR(1) NOT NULL
GO
CREATE VIEW VW_PESSOA_PROFISSIONAL_FORNECEDOR_PROCEDIMENTO
AS
SELECT PSEMP.ID_EMPRESA,
			 PESSO.SQ_PESSOA,
			 PESSO.NO_PESSOA,
			 PSEMP.IC_PROFISSIONAL,
			 PSEMP.IC_FORNECEDOR
	FROM TB_PESSOA PESSO
	INNER JOIN TB_PESSOA_EMPRESA PSEMP ON PSEMP.ID_PESSOA = PESSO.SQ_PESSOA
		                                AND (( PSEMP.IC_PROFISSIONAL = 'S' AND PSEMP.IC_PROFISSIONAL_ATIVO = 'S' ) OR
																		     ( PSEMP.IC_FORNECEDOR = 'S' AND PSEMP.IC_FORNECEDOR_ATIVO = 'S' ))
GO
CREATE VIEW [dbo].[VW_PROCEDIMENTO_EMPRESA]
AS
SELECT EMPRE.ID_EMPRESA,
			 PROCE.SQ_PROCEDIMENTO,
			 PROCE.ID_TABELAPROCEDIMENTO,
			 PROCE.CD_PROCEDIMENTO,
			 PROCE.NO_PROCEDIMENTO
 FROM TB_PROCEDIMENTO PROCE
  INNER JOIN TB_EMPRESA EMPRE ON EMPRE.ID_TABELAPROCEDIMENTO_PADRAO = PROCE.ID_TABELAPROCEDIMENTO 
 WHERE PROCE.IC_ATIVO = 'S'
GO
ALTER FUNCTION [dbo].[FC_ESPECIALIDADE_PESSOA_HORARIO]
(
 @ID_EMPRESA INT,
 @ID_ESPECIALIDADE INT,
 @DT_HORARIO DATE
)
RETURNS @TB_RETORNO TABLE
(
 ID_PESSOA INT,
 ID_OPT_DIASEMANA INT,
 ID_PROCEDIMENTO INT,
 NO_PESSOA VARCHAR(500),
 DS_INFORMACAO VARCHAR(500),
 HR_INICIO CHAR(5),
 HR_FIM CHAR(5),
 QT_ATENDIMENTO INT
)
AS
BEGIN
  INSERT INTO @TB_RETORNO (ID_PESSOA, ID_OPT_DIASEMANA, ID_PROCEDIMENTO, NO_PESSOA, QT_ATENDIMENTO, HR_INICIO, HR_FIM)
	SELECT PSESP.ID_PESSOA, PSHRR.ID_OPT_DIA_SEMANA, PSHRR.ID_PROCEDIMENTO, PESSO.NO_PESSOA,  PSHRR.QT_ATENDIMENTO, PSHRR.HR_INICIO, PSHRR.HR_FIM
	 FROM TB_PESSOA_ESPECIALIDADE PSESP
	  INNER JOIN TB_PESSOA_HORARIO PSHRR ON PSHRR.ID_PESSOA = PSESP.ID_PESSOA
		                                  AND PSHRR.ID_EMPRESA = @ID_EMPRESA
																			AND PSHRR.ID_OPT_ATIVO = 715
		INNER JOIN TB_PESSOA PESSO ON PESSO.SQ_PESSOA = PSESP.ID_PESSOA
	 WHERE PSESP.ID_EMPRESA = @ID_EMPRESA
	   AND PSESP.ID_ESPECIALIDADE = @ID_ESPECIALIDADE
	   AND PSHRR.DT_ESPECIAL = @DT_HORARIO

  INSERT INTO @TB_RETORNO (ID_PESSOA, ID_OPT_DIASEMANA, ID_PROCEDIMENTO, NO_PESSOA, QT_ATENDIMENTO, HR_INICIO, HR_FIM)
	SELECT PSESP.ID_PESSOA, PSHRR.ID_OPT_DIA_SEMANA, PSHRR.ID_PROCEDIMENTO, PESSO.NO_PESSOA,  PSHRR.QT_ATENDIMENTO, PSHRR.HR_INICIO, PSHRR.HR_FIM
	 FROM TB_PESSOA_ESPECIALIDADE PSESP
	  INNER JOIN TB_PESSOA_HORARIO PSHRR ON PSHRR.ID_PESSOA = PSESP.ID_PESSOA
		                                  AND PSHRR.ID_EMPRESA = @ID_EMPRESA
		INNER JOIN TB_PESSOA PESSO ON PESSO.SQ_PESSOA = PSESP.ID_PESSOA
		INNER JOIN TB_OPCAO OPCAO ON OPCAO.SQ_OPCAO = PSHRR.ID_OPT_DIA_SEMANA
		 LEFT JOIN @TB_RETORNO RET ON RET.ID_PESSOA = PSESP.ID_PESSOA
		                          AND RET.ID_OPT_DIASEMANA = PSHRR.ID_OPT_DIA_SEMANA
	 WHERE PSESP.ID_EMPRESA = @ID_EMPRESA 
     AND PSESP.ID_ESPECIALIDADE = @ID_ESPECIALIDADE
	   AND PSHRR.DT_ESPECIAL IS NULL
		 AND PSHRR.ID_OPT_ATIVO = 715
		 AND OPCAO.CD_OPCAO = DATEPART(W, @DT_HORARIO)
		 AND RET.ID_PESSOA IS NULL

	UPDATE RET
	 SET DS_INFORMACAO = CONCAT(RET.NO_PESSOA, ' - ', ISNULL(PRC.NO_PROCEDIMENTO, '<Sem procedimento definido>'), ' [', CAST(RET.QT_ATENDIMENTO AS VARCHAR), '/', CAST(RET.QT_ATENDIMENTO - ISNULL(ISNULL(APQ.QT_AGENDAMENTO, AGQ.QT_AGENDAMENTO), 0) AS varchar)  , ']')
	 FROM @TB_RETORNO RET
	  LEFT JOIN TB_PROCEDIMENTO PRC ON PRC.SQ_PROCEDIMENTO = RET.ID_PROCEDIMENTO
		LEFT JOIN VW_AGENDAMENTO_QUANTIDADE AGQ ON AGQ.DT_AGENDAMENTO = @DT_HORARIO
		                                       AND AGQ.ID_PESSOA_PROFISSIONAL = RET.ID_PESSOA
		LEFT JOIN VW_AGENDAMENTO_PROCEDIMENTO_QUANTIDADE APQ ON APQ.DT_AGENDAMENTO = @DT_HORARIO
		                                                    AND APQ.ID_PESSOA_PROFISSIONAL = RET.ID_PESSOA
		                                                    AND APQ.ID_PROCEDIMENTO = RET.ID_PROCEDIMENTO 

  RETURN
END
GO
CREATE PROCEDURE SP_CONVENIO_PROCEDIMENTO_CAD
(
	@SQ_CONVENIO_PROCEDIMENTO INT,
	@ID_PROCEDIMENTO INT,
	@ID_CONVENIO INT,
	@ID_PESSOA_PROFISSIONAL INT,
	@VL_PROCEDIMENTO MONEY,
	@VL_REPASSE MONEY,
	@PC_REPASSE DECIMAL(18, 5),
	@QT_DIAS_REPASSE INT,
	@CM_OBSERVACAO VARCHAR(500),
	@IC_ATIVO CHAR(1)
)
AS
BEGIN
  IF ISNULL(@SQ_CONVENIO_PROCEDIMENTO, 0) = 0
	  INSERT INTO TB_CONVENIO_PROCEDIMENTO
		(ID_PROCEDIMENTO, ID_CONVENIO, ID_PESSOA_PROFISSIONAL, VL_PROCEDIMENTO, VL_REPASSE, PC_REPASSE, QT_DIAS_REPASSE, CM_OBSERVACAO, IC_ATIVO)
		VALUES
		(@ID_PROCEDIMENTO, @ID_CONVENIO, @ID_PESSOA_PROFISSIONAL, @VL_PROCEDIMENTO, @VL_REPASSE, @PC_REPASSE, @QT_DIAS_REPASSE, @CM_OBSERVACAO, @IC_ATIVO)
	ELSE
	  UPDATE TB_CONVENIO_PROCEDIMENTO
		 SET VL_PROCEDIMENTO = @VL_PROCEDIMENTO,
				 VL_REPASSE = @VL_REPASSE,
				 PC_REPASSE = @PC_REPASSE,
				 QT_DIAS_REPASSE = @QT_DIAS_REPASSE,
				 CM_OBSERVACAO = @CM_OBSERVACAO,
				 IC_ATIVO = @IC_ATIVO
		 WHERE SQ_CONVENIO_PROCEDIMENTO = @SQ_CONVENIO_PROCEDIMENTO
END
GO
ALTER TABLE TB_AGENDAMENTO
 ADD VL_PROCEDIMENTO MONEY,
     VL_REPASSE MONEY
GO
ALTER PROCEDURE [dbo].[SP_AGENDAMENTO_CAD]
(
	@SQ_AGENDAMENTO int OUTPUT,
	@CD_AGENDAMENTO VARCHAR(10) OUTPUT,
	@ID_EMPRESA int,
	@ID_TIPO_CONSULTA int,
	@ID_AGENDAMENTO_ORIGEM int,
	@ID_PESSOA int,
	@ID_PESSOA_PROFISSIONAL int,
	@ID_ESPECIALIDADE int,
	@ID_CONVENIO int,
	@ID_PROCEDIMENTO int,
	@ID_OPT_STATUS int,
	@DH_AGENDAMENTO datetime,
	@DH_CHEGADA datetime,
	@DH_SAIDA datetime,
	@NO_PESSOA varchar(100),
	@CD_TELEFONE varchar(20),
	@CD_CELULAR varchar(20),
	@DS_COMPLEMENTO varchar(MAX),
	@VL_PROCEDIMENTO MONEY,
  @VL_REPASSE MONEY
)
AS
BEGIN
   IF (@ID_OPT_STATUS = 38 /* Agendado */ OR @ID_OPT_STATUS =	581 /* Confirmado */) AND @DH_CHEGADA IS NOT NULL
     SET @ID_OPT_STATUS = 569 /* Aguardando */

  IF ISNULL(@SQ_AGENDAMENTO, 0) = 0
    BEGIN
			SELECT @CD_AGENDAMENTO = dbo.FC_EMPRESA_NOVO_CD_AGENDAMENTO(@ID_EMPRESA)

			UPDATE TB_EMPRESA SET CD_AGENDAMENTO = @CD_AGENDAMENTO WHERE ID_EMPRESA = @ID_EMPRESA

			INSERT INTO TB_AGENDAMENTO
			(ID_AGENDAMENTO_ORIGEM, ID_EMPRESA, ID_PESSOA, ID_PESSOA_PROFISSIONAL, ID_ESPECIALIDADE, ID_CONVENIO,
			 ID_PROCEDIMENTO, CD_AGENDAMENTO, DH_AGENDAMENTO, DH_CHEGADA, DH_SAIDA, NO_PESSOA, CD_TELEFONE,
			 CD_CELULAR, DS_COMPLEMENTO, ID_TIPO_CONSULTA, VL_PROCEDIMENTO, VL_REPASSE, ID_OPT_STATUS)
			VALUES
			(@ID_AGENDAMENTO_ORIGEM, @ID_EMPRESA, @ID_PESSOA, @ID_PESSOA_PROFISSIONAL, @ID_ESPECIALIDADE, @ID_CONVENIO,
			 @ID_PROCEDIMENTO, @CD_AGENDAMENTO, @DH_AGENDAMENTO, @DH_CHEGADA, @DH_SAIDA, @NO_PESSOA, @CD_TELEFONE,
			 @CD_CELULAR, @DS_COMPLEMENTO, @ID_TIPO_CONSULTA, @VL_PROCEDIMENTO, @VL_REPASSE, @ID_OPT_STATUS)

			SET @SQ_AGENDAMENTO = @@IDENTITY
		END
	ELSE
    UPDATE TB_AGENDAMENTO
		 SET ID_AGENDAMENTO_ORIGEM = @ID_AGENDAMENTO_ORIGEM,
				 ID_EMPRESA = @ID_EMPRESA,
				 ID_PESSOA = @ID_PESSOA,
				 ID_PESSOA_PROFISSIONAL = @ID_PESSOA_PROFISSIONAL,
				 ID_ESPECIALIDADE = @ID_ESPECIALIDADE,
				 ID_CONVENIO = @ID_CONVENIO,
				 ID_PROCEDIMENTO = @ID_PROCEDIMENTO,
				 DH_AGENDAMENTO = @DH_AGENDAMENTO,
			   DH_CHEGADA = @DH_CHEGADA,
				 DH_SAIDA = @DH_SAIDA,
				 NO_PESSOA = @NO_PESSOA,
				 CD_TELEFONE = @CD_TELEFONE,
				 CD_CELULAR = @CD_CELULAR,
				 DS_COMPLEMENTO = @DS_COMPLEMENTO,
				 ID_OPT_STATUS = @ID_OPT_STATUS,
				 ID_TIPO_CONSULTA = @ID_TIPO_CONSULTA,
				 VL_PROCEDIMENTO = @VL_PROCEDIMENTO,
				 VL_REPASSE = @VL_REPASSE
		 WHERE SQ_AGENDAMENTO = @SQ_AGENDAMENTO 

  RETURN
END
GO
ALTER VIEW [dbo].[VW_AGENDAMENTO]
AS
SELECT AGE.SQ_AGENDAMENTO,
       AGE.ID_EMPRESA,
       AGE.ID_TIPO_CONSULTA,
       AGE.ID_OPT_STATUS,
       AGE.ID_AGENDAMENTO_ORIGEM,
       AGE.ID_PESSOA,
       AGE.ID_PESSOA_PROFISSIONAL,
       AGE.ID_ESPECIALIDADE,
       AGE.ID_CONVENIO,
       AGE.ID_PROCEDIMENTO,
			 AGE.CD_AGENDAMENTO,
			 AGO.CD_AGENDAMENTO CD_AGENDAMENTO_ORIGEM,
			 TCS.NO_TIPO_CONSULTA,
			 STS.NO_OPCAO NO_OPT_STATUS,
			 ISNULL(CLI.NO_PESSOA, AGE.NO_PESSOA) NO_PESSOA,
			 PRF.NO_PESSOA NO_PESSOA_PROFISSIONAL,
			 CVN.NO_CONVENIO,
			 PCD.NO_PROCEDIMENTO,
			 AGE.DH_AGENDAMENTO,
			 AGE.DH_CHEGADA,
			 AGE.DH_SAIDA,
			 AGE.CD_TELEFONE,
			 AGE.CD_CELULAR,
			 AGE.DS_COMPLEMENTO,
			 CLI.NO_INDICACAO,
			 IIF(AGP.SQ_AGENDAMENTO IS NULL, 'N', 'S') IC_PRIMEIRA,
			 AGE.VL_PROCEDIMENTO
 FROM  TB_AGENDAMENTO AGE
  INNER JOIN TB_TIPO_CONSULTA TCS ON TCS.SQ_TIPO_CONSULTA = AGE.ID_TIPO_CONSULTA
   LEFT JOIN TB_AGENDAMENTO AGO ON AGO.SQ_AGENDAMENTO = AGE.ID_AGENDAMENTO_ORIGEM
   LEFT JOIN TB_OPCAO STS ON STS.SQ_OPCAO = AGE.ID_OPT_STATUS
   LEFT JOIN VW_PESSOA CLI ON CLI.SQ_PESSOA = AGE.ID_PESSOA
	                        AND CLI.ID_EMPRESA = AGE.ID_EMPRESA
   LEFT JOIN VW_PESSOA PRF ON PRF.SQ_PESSOA = AGE.ID_PESSOA_PROFISSIONAL
	                        AND PRF.ID_EMPRESA = AGE.ID_EMPRESA
   LEFT JOIN TB_CONVENIO CVN ON CVN.SQ_CONVENIO = AGE.ID_CONVENIO
   LEFT JOIN TB_PROCEDIMENTO PCD ON PCD.SQ_PROCEDIMENTO = AGE.ID_PROCEDIMENTO
   LEFT JOIN VW_AGENDAMENTO_PRIMEIRO AGP ON AGP.SQ_AGENDAMENTO = AGE.SQ_AGENDAMENTO