ALTER TABLE TB_PROCEDIMENTO
 ADD ID_OPT_TIPOEXAME INT
GO
ALTER TABLE [dbo].TB_PROCEDIMENTO  WITH CHECK ADD  CONSTRAINT FK_PROCE_OPCAO_TPEXM FOREIGN KEY(ID_OPT_TIPOEXAME)
 REFERENCES [dbo].TB_OPCAO (SQ_OPCAO)
GO
INSERT INTO TB_TIPO_OPCAO (SQ_TIPO_OPCAO, NO_TIPO_OPCAO) VALUES (116, 'Tipo de Exame')
GO
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (728, 116, 'Laboratorial', 'S')
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (729, 116, 'Complementar', 'S')
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (730, 116, 'Citológico', 'S')
INSERT INTO TB_OPCAO (SQ_OPCAO, ID_TIPO_OPCAO, NO_OPCAO, IC_ATIVO) VALUES (731, 116, 'Vacina', 'S')
GO
CREATE TABLE dbo.TB_PROCEDIMENTO_ESPECIALIDADE
(
	ID_PROCEDIMENTO INT NOT NULL,
	ID_ESPECIALIDADE INT NOT NULL
)
GO
ALTER TABLE dbo.TB_PROCEDIMENTO_ESPECIALIDADE
 ADD CONSTRAINT	PK_PROCEDIMENTO_ESPECIALIDADE
  PRIMARY KEY CLUSTERED 
	(
	ID_PROCEDIMENTO,
	ID_ESPECIALIDADE
	)
GO
ALTER TABLE [dbo].TB_PROCEDIMENTO_ESPECIALIDADE  WITH CHECK ADD  CONSTRAINT FK_PCESP_PROCE FOREIGN KEY(ID_PROCEDIMENTO)
 REFERENCES [dbo].TB_PROCEDIMENTO (SQ_PROCEDIMENTO)
GO
ALTER TABLE [dbo].TB_PROCEDIMENTO_ESPECIALIDADE  WITH CHECK ADD  CONSTRAINT FK_PCESP_ESPEC FOREIGN KEY(ID_ESPECIALIDADE)
 REFERENCES [dbo].TB_ESPECIALIDADE (SQ_ESPECIALIDADE)
GO
ALTER TABLE TB_CONVENIO
 ADD NR_DIA_CORTE INT,
     NR_DIA_PREVISAO_PAGAMENTO INT
GO
ALTER PROCEDURE [dbo].[SP_CONVENIO_CAD]
(
	@SQ_CONVENIO int OUT,
	@ID_EMPRESA int,
	@ID_ADMINISTRADORA int,
	@ID_OPT_TIPO int,
	@NO_CONVENIO varchar(50),
  @CD_CONTRATO varchar(20),
	@NR_DIA_CORTE INT,
	@NR_DIA_PREVISAO_PAGAMENTO INT,
	@IC_ATIVO char(1)
)
AS
BEGIN
  IF ISNULL(@SQ_CONVENIO, 0) = 0
	  BEGIN
			INSERT INTO TB_CONVENIO
			(ID_EMPRESA, ID_ADMINISTRADORA, ID_OPT_TIPO, NO_CONVENIO, CD_CONTRATO, NR_DIA_CORTE, NR_DIA_PREVISAO_PAGAMENTO, IC_ATIVO)
			VALUES
			(@ID_EMPRESA, @ID_ADMINISTRADORA, @ID_OPT_TIPO, @NO_CONVENIO, @NR_DIA_CORTE, @NR_DIA_PREVISAO_PAGAMENTO, @CD_CONTRATO, @IC_ATIVO)

			SET @SQ_CONVENIO = @@IDENTITY
		END
	ELSE
		UPDATE TB_CONVENIO
		 SET ID_EMPRESA = @ID_EMPRESA,
		     ID_ADMINISTRADORA = @ID_ADMINISTRADORA,
				 ID_OPT_TIPO = @ID_OPT_TIPO,
				 NO_CONVENIO = @NO_CONVENIO,
				 CD_CONTRATO = @CD_CONTRATO,
				 NR_DIA_CORTE = @NR_DIA_CORTE,
				 NR_DIA_PREVISAO_PAGAMENTO = @NR_DIA_PREVISAO_PAGAMENTO,
				 IC_ATIVO = @IC_ATIVO
		 WHERE SQ_CONVENIO = @SQ_CONVENIO

	RETURN
END
GO
ALTER PROCEDURE SP_PROCEDIMENTO_CAD
(
 @SQ_PROCEDIMENTO INT OUTPUT,
 @ID_TABELAPROCEDIMENTO INT,
 @ID_OPT_TIPOPROCEDIMENTO INT,
 @ID_OPT_TIPOEXAME INT,
 @CD_PROCEDIMENTO CHAR(11),
 @NO_PROCEDIMENTO VARCHAR(100),
 @IC_ATIVO CHAR(1)
)
AS
BEGIN
  IF ISNULL(@SQ_PROCEDIMENTO, 0) = 0
    BEGIN
      INSERT INTO TB_PROCEDIMENTO
			(ID_TABELAPROCEDIMENTO, ID_OPT_TIPOPROCEDIMENTO, ID_OPT_TIPOEXAME, CD_PROCEDIMENTO, NO_PROCEDIMENTO, IC_ATIVO)
			VALUES
			(@ID_TABELAPROCEDIMENTO, @ID_OPT_TIPOPROCEDIMENTO, @ID_OPT_TIPOEXAME, @CD_PROCEDIMENTO, @NO_PROCEDIMENTO, @IC_ATIVO)
	  
			SELECT @SQ_PROCEDIMENTO = @@IDENTITY
		END
  ELSE
    UPDATE TB_PROCEDIMENTO
		 SET ID_TABELAPROCEDIMENTO = @ID_TABELAPROCEDIMENTO,
				 ID_OPT_TIPOPROCEDIMENTO = @ID_OPT_TIPOPROCEDIMENTO,
				 ID_OPT_TIPOEXAME = @ID_OPT_TIPOEXAME,
				 CD_PROCEDIMENTO = @CD_PROCEDIMENTO,
				 NO_PROCEDIMENTO = @NO_PROCEDIMENTO,
				 IC_ATIVO = @IC_ATIVO
		 WHERE SQ_PROCEDIMENTO = @SQ_PROCEDIMENTO

  RETURN
END
GO
ALTER TABLE TB_PESSOA_EMPRESA
 ADD IC_FORNECEDOR_PRESTADORSERVICOMEDICO CHAR(1)
 GO
ALTER PROCEDURE [dbo].[SP_PESSOA_EMPRESA_CAD]
(
 @ID_PESSOA INT,
 @ID_EMPRESA INT,
 @IC_CLIENTE CHAR(1),
 @IC_FABRICANTE CHAR(1),
 @IC_FORNECEDOR CHAR(1),
 @IC_FUNCIONARIO CHAR(1),
 @IC_PACIENTE CHAR(1),
 @IC_PROFISSIONAL CHAR(1),
 @IC_TRANSPORTADORA CHAR(1),
 @IC_VENDEDOR CHAR(1),
 @ID_CLIENTE_TABELAPRECO_PADRAO INT,
 @IC_CLIENTE_BLOQUEAR_VENDA CHAR(1),
 @IC_CLIENTE_ATIVO CHAR(1),
 @DS_CLIENTE_COMENTARIO VARCHAR(MAX),
 @IC_FABRICANTE_ATIVO CHAR(1),
 @IC_FORNECEDOR_ATIVO CHAR(1),
 @IC_FORNECEDOR_PRESTADORSERVICOMEDICO CHAR(1),
 @CM_FORNECEDOR_OBSERVACAO VARCHAR(MAX),
 @ID_FUNCIONARIO_TIPO_CARGO INT,
 @DT_FUNCIONARIO_ADMISSAO DATE,
 @DT_FUNCIONARIO_DESLIGAMENTO DATE,
 @IC_FUNCIONARIO_ATIVO CHAR(1),
 @DS_PACIENTE_COMENTARIO VARCHAR(MAX),
 @DS_PACIENTE_PENDENCIAS VARCHAR(MAX),
 @ID_PACIENTE_TIPO_PACIENTE INT,
 @IC_PACIENTE_ATIVO CHAR(1),
 @ID_PROFISSIONAL_CONSELHOPROFISSIONAL INT,
 @NR_PROFISSIONAL_CONSELHOPROFISSIONAL VARCHAR(20),
 @IC_PROFISSIONAL_ATIVO CHAR(1),
 @IC_TRANSPORTADORA_ATIVO CHAR(1),
 @IC_VENDEDOR_ATIVO CHAR(1)
)
AS
BEGIN
  IF @IC_CLIENTE = 'N'
    BEGIN
      UPDATE TB_PESSOA_LIMITECREDITO
			 SET IC_BLOQUEADO = 'S'
       WHERE ID_PESSOA = @ID_PESSOA
         AND ID_EMPRESA = @ID_EMPRESA

			SET @IC_CLIENTE_BLOQUEAR_VENDA = 'S'
			SET @IC_CLIENTE_ATIVO = 'N'
    END

  IF @IC_FABRICANTE = 'N'
    SET @IC_FABRICANTE_ATIVO = 'N'

  IF @IC_FORNECEDOR = 'N'
    SET @IC_FORNECEDOR_ATIVO = 'N'

  IF @IC_FUNCIONARIO = 'N'
    BEGIN
			SET @IC_FUNCIONARIO_ATIVO = 'N'
		END

  IF @IC_PACIENTE = 'N'
    SET @IC_PACIENTE_ATIVO = 'N'

  IF @IC_PROFISSIONAL = 'N'
    SET @IC_PROFISSIONAL_ATIVO = 'N'

  IF @IC_TRANSPORTADORA = 'N'
    SET @IC_TRANSPORTADORA_ATIVO = 'N'

  IF @IC_VENDEDOR = 'N'
    SET @IC_VENDEDOR_ATIVO = 'N'
  
  UPDATE TB_PESSOA_EMPRESA
   SET IC_CLIENTE = @IC_CLIENTE,
			 IC_FABRICANTE = @IC_FABRICANTE,
			 IC_FORNECEDOR = @IC_FORNECEDOR,
			 IC_FUNCIONARIO = @IC_FUNCIONARIO,
			 IC_PACIENTE = @IC_PACIENTE,
			 IC_PROFISSIONAL = @IC_PROFISSIONAL,
			 IC_TRANSPORTADORA = @IC_TRANSPORTADORA,
			 IC_VENDEDOR = @IC_VENDEDOR,
			 ID_CLIENTE_TABELAPRECO_PADRAO = @ID_CLIENTE_TABELAPRECO_PADRAO,
			 IC_CLIENTE_BLOQUEAR_VENDA = @IC_CLIENTE_BLOQUEAR_VENDA,
			 IC_CLIENTE_ATIVO = @IC_CLIENTE_ATIVO,
			 DS_CLIENTE_COMENTARIO = @DS_CLIENTE_COMENTARIO,
			 IC_FABRICANTE_ATIVO = @IC_FABRICANTE_ATIVO,
			 IC_FORNECEDOR_ATIVO = @IC_FORNECEDOR_ATIVO,
			 IC_FORNECEDOR_PRESTADORSERVICOMEDICO = @IC_FORNECEDOR_PRESTADORSERVICOMEDICO,
			 CM_FORNECEDOR_OBSERVACAO = @CM_FORNECEDOR_OBSERVACAO,
			 ID_FUNCIONARIO_TIPO_CARGO = @ID_FUNCIONARIO_TIPO_CARGO,
			 DT_FUNCIONARIO_ADMISSAO = @DT_FUNCIONARIO_ADMISSAO,
			 DT_FUNCIONARIO_DESLIGAMENTO = @DT_FUNCIONARIO_DESLIGAMENTO,
			 IC_FUNCIONARIO_ATIVO = @IC_FUNCIONARIO_ATIVO,
			 DS_PACIENTE_COMENTARIO = @DS_PACIENTE_COMENTARIO,
			 DS_PACIENTE_PENDENCIAS = @DS_PACIENTE_PENDENCIAS,
			 ID_PACIENTE_TIPO_PACIENTE = @ID_PACIENTE_TIPO_PACIENTE,
			 IC_PACIENTE_ATIVO = @IC_PACIENTE_ATIVO,
			 ID_PROFISSIONAL_CONSELHOPROFISSIONAL = @ID_PROFISSIONAL_CONSELHOPROFISSIONAL,
			 NR_PROFISSIONAL_CONSELHOPROFISSIONAL = @NR_PROFISSIONAL_CONSELHOPROFISSIONAL,
			 IC_PROFISSIONAL_ATIVO = @IC_PROFISSIONAL_ATIVO,
			 IC_TRANSPORTADORA_ATIVO = @IC_TRANSPORTADORA_ATIVO,
			 IC_VENDEDOR_ATIVO = @IC_VENDEDOR_ATIVO
   WHERE ID_PESSOA = @ID_PESSOA
     AND ID_EMPRESA = @ID_EMPRESA
END
GO
ALTER VIEW [dbo].[VW_PESSOA_PROFISSIONAL_FORNECEDOR_PROCEDIMENTO]
AS
SELECT PSEMP.ID_EMPRESA,
			 PESSO.SQ_PESSOA,
			 PESSO.NO_PESSOA,
			 PSEMP.IC_PROFISSIONAL,
			 PSEMP.IC_FORNECEDOR
	FROM TB_PESSOA PESSO
	INNER JOIN TB_PESSOA_EMPRESA PSEMP ON PSEMP.ID_PESSOA = PESSO.SQ_PESSOA
		                                AND (( PSEMP.IC_PROFISSIONAL = 'S' AND PSEMP.IC_PROFISSIONAL_ATIVO = 'S' ) OR
																		     ( PSEMP.IC_FORNECEDOR = 'S' AND PSEMP.IC_FORNECEDOR_ATIVO = 'S' AND PSEMP.IC_FORNECEDOR_PRESTADORSERVICOMEDICO = 'S' ))