CREATE TABLE TB_ORCAMENTO_CLIENTE
(
 SQ_ORCAMENTO_CLIENTE INT NOT NULL IDENTITY(1, 1),
 ID_EMPRESA INT NOT NULL,
 ID_PESSOA INT NOT NULL,
 ID_CONVENIO INT NOT NULL,
 ID_FINANCIAMENTO INT,
 ID_AGENDAMENTO INT,
 CD_ORCAMENTO_CLIENTE VARCHAR(10) NOT NULL,
 DH_ORCAMENTO_CLIENTE DATETIME NOT NULL DEFAULT GETDATE(),
 DT_VALIDADE DATE NOT NULL
)
GO
ALTER TABLE dbo.TB_ORCAMENTO_CLIENTE ADD CONSTRAINT	PK_ORCAMENTO_CLIENTE
  PRIMARY KEY CLUSTERED  (SQ_ORCAMENTO_CLIENTE)
GO
ALTER TABLE dbo.TB_ORCAMENTO_CLIENTE  WITH CHECK ADD  CONSTRAINT FK_OCCLI_EMPRE FOREIGN KEY(ID_EMPRESA)
 REFERENCES dbo.tb_EMPRESA (ID_EMPRESA)
GO
ALTER TABLE dbo.TB_ORCAMENTO_CLIENTE  WITH CHECK ADD  CONSTRAINT FK_OCCLI_PESSO FOREIGN KEY(ID_PESSOA)
 REFERENCES dbo.TB_PESSOA (SQ_PESSOA)
GO
ALTER TABLE dbo.TB_ORCAMENTO_CLIENTE  WITH CHECK ADD  CONSTRAINT FK_OCCLI_FINAN FOREIGN KEY(ID_FINANCIAMENTO)
 REFERENCES dbo.TB_FINANCIAMENTO (SQ_FINANCIAMENTO)
GO
ALTER TABLE dbo.TB_ORCAMENTO_CLIENTE  WITH CHECK ADD  CONSTRAINT FK_OCCLI_AGEND FOREIGN KEY(ID_AGENDAMENTO)
 REFERENCES dbo.TB_AGENDAMENTO (SQ_AGENDAMENTO)
GO
ALTER TABLE dbo.TB_ORCAMENTO_CLIENTE  WITH CHECK ADD  CONSTRAINT FK_OCCLI_CONVE FOREIGN KEY(ID_CONVENIO)
 REFERENCES dbo.TB_CONVENIO (SQ_CONVENIO)
GO
CREATE TABLE TB_ORCAMENTO_CLIENTE_PROCEDIMENTO
(
 SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO INT NOT NULL IDENTITY(1, 1),
 ID_ORCAMENTO_CLIENTE INT NOT NULL,
 ID_PROCEDIMENTO INT NOT NULL,
 VL_ORCADO MONEY
)
GO
ALTER TABLE dbo.TB_ORCAMENTO_CLIENTE_PROCEDIMENTO ADD CONSTRAINT	PK_ORCAMENTO_CLIENTE_PROCEDIMENTO
  PRIMARY KEY CLUSTERED  (SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO)
GO
ALTER TABLE dbo.TB_ORCAMENTO_CLIENTE_PROCEDIMENTO  WITH CHECK ADD  CONSTRAINT FK_OCPRC_OCPRC FOREIGN KEY(ID_ORCAMENTO_CLIENTE)
 REFERENCES dbo.TB_ORCAMENTO_CLIENTE (SQ_ORCAMENTO_CLIENTE)
GO
ALTER TABLE dbo.TB_ORCAMENTO_CLIENTE_PROCEDIMENTO  WITH CHECK ADD  CONSTRAINT FK_OCPRC_PROCE FOREIGN KEY(ID_PROCEDIMENTO)
 REFERENCES dbo.TB_PROCEDIMENTO (SQ_PROCEDIMENTO)
GO
CREATE TABLE TB_CONFIG
(
 NR_IDOSO_IDADE INT
)
GO
ALTER PROCEDURE dbo.SP_EMPRESA_CLINICA_CONFIGURACAO_CAD
(
 @ID_EMPRESA INT,
 @ID_TABELAPROCEDIMENTO_PADRAO INT,
 @ID_MODELODOCUMENTO_RECEITA_PADRAO INT,
 @ID_MODELODOCUMENTO_ANAMNESE_PADRAO INT,
 @ID_MODELODOCUMENTO_EVOLUCAO_PADRAO INT,
 @ID_QUESTIONARIO_ANAMNESE_PADRAO INT,
 @ID_TIPO_CONSULTA_RETORNO INT,
 @NR_ATENDIMENTO_INTERVALO INT,
 @HR_ATENDIMENTO_INICIO CHAR(5),
 @HR_ATENDIMENTO_SAIDAREFEICAO CHAR(5),
 @HR_ATENDIMENTO_RETORNOREFEICAO CHAR(5),
 @HR_ATENDIMENTO_FIM CHAR(5),
 @IC_LISTARTODOS_PROCEDIMENTO CHAR(1),
 @IC_NECESSITA_ANAMNESE_EVOLUCAO CHAR(1),
 @NR_IDOSO_IDADE INT
)
AS
BEGIN
  UPDATE TB_EMPRESA
   SET ID_TABELAPROCEDIMENTO_PADRAO = @ID_TABELAPROCEDIMENTO_PADRAO,
	   ID_MODELODOCUMENTO_RECEITA_PADRAO = @ID_MODELODOCUMENTO_RECEITA_PADRAO,
	   ID_MODELODOCUMENTO_ANAMNESE_PADRAO = @ID_MODELODOCUMENTO_ANAMNESE_PADRAO,
	   ID_MODELODOCUMENTO_EVOLUCAO_PADRAO = @ID_MODELODOCUMENTO_EVOLUCAO_PADRAO,
	   ID_QUESTIONARIO_ANAMNESE_PADRAO = @ID_QUESTIONARIO_ANAMNESE_PADRAO,
	   ID_TIPO_CONSULTA_RETORNO = @ID_TIPO_CONSULTA_RETORNO,
	   NR_ATENDIMENTO_INTERVALO = @NR_ATENDIMENTO_INTERVALO,
	   HR_ATENDIMENTO_INICIO = @HR_ATENDIMENTO_INICIO,
	   HR_ATENDIMENTO_SAIDAREFEICAO = @HR_ATENDIMENTO_SAIDAREFEICAO,
	   HR_ATENDIMENTO_RETORNOREFEICAO = @HR_ATENDIMENTO_RETORNOREFEICAO,
	   HR_ATENDIMENTO_FIM = @HR_ATENDIMENTO_FIM,
	   IC_LISTARTODOS_PROCEDIMENTO = @IC_LISTARTODOS_PROCEDIMENTO,
		 IC_NECESSITA_ANAMNESE_EVOLUCAO = @IC_NECESSITA_ANAMNESE_EVOLUCAO
   WHERE ID_EMPRESA = @ID_EMPRESA

	IF EXISTS(SELECT * FROM TB_CONFIG)
		UPDATE TB_CONFIG SET NR_IDOSO_IDADE = @NR_IDOSO_IDADE
	ELSE
	  INSERT INTO TB_CONFIG (NR_IDOSO_IDADE) VALUES (@NR_IDOSO_IDADE)	 
END
GO
CREATE VIEW VW_CONVENIO_PROCEDIMENTO
AS
SELECT PESSO.NO_PESSOA, CONVE.NO_CONVENIO, PROCE.NO_PROCEDIMENTO, CVPCD.*
 FROM TB_CONVENIO_PROCEDIMENTO CVPCD
  INNER JOIN TB_PESSOA PESSO ON PESSO.SQ_PESSOA = CVPCD.ID_PESSOA_PROFISSIONAL
	INNER JOIN TB_CONVENIO CONVE ON CONVE.SQ_CONVENIO = CVPCD.ID_CONVENIO
	INNER JOIN TB_PROCEDIMENTO PROCE ON PROCE.SQ_PROCEDIMENTO = CVPCD.ID_PROCEDIMENTO
GO
ALTER TABLE TB_EMPRESA
 ADD CD_ORCAMENTOCLINICA VARCHAR(10)
GO
CREATE FUNCTION [dbo].FC_EMPRESA_NOVO_CD_ORCAMENTOCLINICA
(
 @ID_EMPRESA INT
)
RETURNS VARCHAR(10)
AS
BEGIN
  DECLARE @NOVO_CD_ORCAMENTOCLINICA VARCHAR(10)

  SELECT @NOVO_CD_ORCAMENTOCLINICA= 'OC' + REPLACE(RIGHT(SPACE(10) + CAST(SUBSTRING(MAX(ISNULL(CD_ORCAMENTOCLINICA, '00')), 3, 6) + 1 AS VARCHAR(10)), 6), ' ', '0')
   FROM TB_EMPRESA

  RETURN @NOVO_CD_ORCAMENTOCLINICA
END
GO
CREATE PROCEDURE SP_ORCAMENTO_CLIENTE_CAD
(
 @SQ_ORCAMENTO_CLIENTE INT OUT,
 @ID_EMPRESA INT,
 @ID_PESSOA INT,
 @ID_CONVENIO INT,
 @ID_FINANCIAMENTO INT,
 @ID_AGENDAMENTO INT,
 @CD_ORCAMENTO_CLIENTE VARCHAR(10) OUT,
 @DH_ORCAMENTO_CLIENTE DATETIME,
 @DT_VALIDADE DATE
)
AS
BEGIN
  IF ISNULL(@SQ_ORCAMENTO_CLIENTE, 0) = 0
		BEGIN
			SELECT @CD_ORCAMENTO_CLIENTE = dbo.FC_EMPRESA_NOVO_CD_ORCAMENTOCLINICA(@ID_EMPRESA)

			INSERT INTO TB_ORCAMENTO_CLIENTE
			(ID_EMPRESA,ID_PESSOA,ID_CONVENIO,ID_FINANCIAMENTO,ID_AGENDAMENTO,CD_ORCAMENTO_CLIENTE,DH_ORCAMENTO_CLIENTE,DT_VALIDADE)
			VALUES
			(@ID_EMPRESA,@ID_PESSOA,@ID_CONVENIO,@ID_FINANCIAMENTO,@ID_AGENDAMENTO,@CD_ORCAMENTO_CLIENTE,@DH_ORCAMENTO_CLIENTE,@DT_VALIDADE)
		END
	ELSE
	  UPDATE TB_ORCAMENTO_CLIENTE
		 SET ID_EMPRESA=@ID_EMPRESA,
				 ID_PESSOA=@ID_PESSOA,
				 ID_CONVENIO=@ID_CONVENIO,
				 ID_FINANCIAMENTO=@ID_FINANCIAMENTO,
				 ID_AGENDAMENTO=@ID_AGENDAMENTO,
				 CD_ORCAMENTO_CLIENTE=@CD_ORCAMENTO_CLIENTE,
				 DH_ORCAMENTO_CLIENTE=@DH_ORCAMENTO_CLIENTE,
				 DT_VALIDADE=@DT_VALIDADE
		 WHERE SQ_ORCAMENTO_CLIENTE = @SQ_ORCAMENTO_CLIENTE
END
GO
CREATE PROCEDURE SP_ORCAMENTO_CLIENTE_PROCEDIMENTO_CAD
(
 @SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO INT,
 @ID_ORCAMENTO_CLIENTE INT,
 @ID_PROCEDIMENTO INT,
 @VL_ORCADO MONEY
)
AS
BEGIN
  IF ISNULL(@SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO, 0) = 0
		INSERT INTO TB_ORCAMENTO_CLIENTE_PROCEDIMENTO
		(ID_ORCAMENTO_CLIENTE,ID_PROCEDIMENTO,VL_ORCADO)
     VALUES
		(@ID_ORCAMENTO_CLIENTE,@ID_PROCEDIMENTO,@VL_ORCADO)
	ELSE
	  UPDATE TB_ORCAMENTO_CLIENTE_PROCEDIMENTO
		 SET ID_ORCAMENTO_CLIENTE=@ID_ORCAMENTO_CLIENTE,
				 ID_PROCEDIMENTO=@ID_PROCEDIMENTO,
				 VL_ORCADO=@VL_ORCADO
		 WHERE SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO = @SQ_ORCAMENTO_CLIENTE_PROCEDIMENTO
END