SELECT CONCAT(PSHRR.HR_INICIO, '-', PSHRR.HR_FIM,  CHAR(13)+CHAR(10), PESSO.NO_PESSOA, ' (', PROCE.NO_PROCEDIMENTO, ')') DS_HORARIO, DT_ESPECIAL, ISNULL(OPCAO_DISMN.SQ_OPCAO, OPCAO_DISMN2.SQ_OPCAO) SQ_OPCAO FROM TB_PESSOA_HORARIO PSHRR INNER JOIN TB_PESSOA PESSO ON PESSO.SQ_PESSOA = PSHRR.ID_PESSOA INNER JOIN TB_PROCEDIMENTO PROCE ON PROCE.SQ_PROCEDIMENTO = PSHRR.ID_PROCEDIMENTO LEFT JOIN TB_OPCAO OPCAO_DISMN ON OPCAO_DISMN.SQ_OPCAO = PSHRR.ID_OPT_DIA_SEMANA LEFT JOIN TB_OPCAO OPCAO_DISMN2 ON OPCAO_DISMN2.CD_OPCAO = DATEPART(W, DT_ESPECIAL) AND OPCAO_DISMN2.ID_TIPO_OPCAO = 114 WHERE PSHRR.ID_EMPRESA = 2 AND (PSHRR.DT_ESPECIAL IS NULL OR (PSHRR.DT_ESPECIAL >= '01/05/2020' AND PSHRR.DT_ESPECIAL <= '31/05/2020')) ORDER BY CONCAT(PSHRR.HR_INICIO, '-', PSHRR.HR_FIM, ' ', PESSO.NO_PESSOA, ' (', PROCE.NO_PROCEDIMENTO, ')')

SELECT * FROM TB_OPCAO WHERE SQ_OPCAO = 719


08:00-18:00  Fabrício Souza Moreira (Consultas)