USE Cli28Julho
GO
ALTER TABLE TB_MOVFINANCEIRA 
 ADD ID_CLINICA_VENDA INT
GO
ALTER TABLE TB_MOVFINANCEIRA WITH CHECK ADD  CONSTRAINT FK_MVFNC_CLVND FOREIGN KEY(ID_CLINICA_VENDA)
 REFERENCES TB_CLINICA_VENDA (SQ_CLINICA_VENDA)
GO
ALTER PROCEDURE [dbo].[SP_MOVFINANCEIRA_CAD]
(
 @SQ_MOVFINANCEIRA INT OUT,
 @ID_EMPRESA INT ,
 @ID_OPT_TIPOMOVFINANCEIRA INT ,
 @ID_OPT_STATUS INT,
 @ID_OPT_PERIODOCALCULOFINANCEIRO_DESCONTO INT,
 @ID_OPT_PERIODOCALCULOFINANCEIRO_JUROS INT,
 @ID_PESSOA INT,
 @ID_CONTAFINANCEIRA_CREDITO INT ,
 @ID_CONTAFINANCEIRA_DEBITO INT ,
 @ID_DOCUMENTOFISCAL INT,
 @ID_PEDIDO INT,
 @ID_ORDEMSERVICO INT,
 @ID_SEGMENTO INT,
 @ID_CONDICAOPAGAMENTO INT,
 @ID_CLINICA_VENDA INT,
 @DS_MOVFINANCEIRA VARCHAR(200),
 @VL_MOVFINANCEIRA MONEY,
 @VL_ORIGINAL MONEY,
 @VL_DESCONTO MONEY,
 @DT_MOVIMENTACAO DATE ,
 @DT_1_VENCIMENTO DATE ,
 @PC_ENTRADA DECIMAL(18, 4) ,
 @PC_JUROS DECIMAL(18, 4) ,
 @PC_DESCONTO DECIMAL(18, 4) ,
 @VL_MULTA MONEY ,
 @PC_MULTA DECIMAL(18, 4) ,
 @CM_MOVFINANCEIRA VARCHAR(MAX) 
)
AS
BEGIN
  DECLARE @CD_MOVFINANCEIRA VARCHAR(10)

  IF ISNULL(@SQ_MOVFINANCEIRA, 0) = 0
		BEGIN
			SELECT @CD_MOVFINANCEIRA = dbo.FC_EMPRESA_NOVO_CD_MOVFINANCEIRA(@ID_EMPRESA, @ID_OPT_TIPOMOVFINANCEIRA)

			EXEC SP_EMPRESA_NOVO_CD_MOVFINANCEIRA @ID_EMPRESA, @ID_OPT_TIPOMOVFINANCEIRA, @CD_MOVFINANCEIRA

			INSERT INTO TB_MOVFINANCEIRA
			(ID_EMPRESA, ID_OPT_TIPOMOVFINANCEIRA, ID_OPT_STATUS, ID_OPT_PERIODOCALCULOFINANCEIRO_DESCONTO,
			 ID_OPT_PERIODOCALCULOFINANCEIRO_JUROS, ID_PESSOA, ID_CONTAFINANCEIRA_CREDITO, ID_CONTAFINANCEIRA_DEBITO,
			 ID_DOCUMENTOFISCAL,ID_PEDIDO,ID_ORDEMSERVICO, ID_SEGMENTO, ID_CONDICAOPAGAMENTO, ID_CLINICA_VENDA,
			 CD_MOVFINANCEIRA, DS_MOVFINANCEIRA,VL_MOVFINANCEIRA, VL_ORIGINAL, VL_DESCONTO, DT_MOVIMENTACAO,
			 DT_1_VENCIMENTO, PC_ENTRADA, PC_JUROS, PC_DESCONTO, VL_MULTA, PC_MULTA, CM_MOVFINANCEIRA)
			VALUES
			(@ID_EMPRESA, @ID_OPT_TIPOMOVFINANCEIRA, @ID_OPT_STATUS, @ID_OPT_PERIODOCALCULOFINANCEIRO_DESCONTO,
			 @ID_OPT_PERIODOCALCULOFINANCEIRO_JUROS, @ID_PESSOA, @ID_CONTAFINANCEIRA_CREDITO, @ID_CONTAFINANCEIRA_DEBITO,
			 @ID_DOCUMENTOFISCAL,@ID_PEDIDO,@ID_ORDEMSERVICO, @ID_SEGMENTO, @ID_CONDICAOPAGAMENTO, @ID_CLINICA_VENDA,
			 @CD_MOVFINANCEIRA, @DS_MOVFINANCEIRA, @VL_MOVFINANCEIRA, @VL_ORIGINAL, @VL_DESCONTO, @DT_MOVIMENTACAO,
			 @DT_1_VENCIMENTO, @PC_ENTRADA, @PC_JUROS, @PC_DESCONTO, @VL_MULTA, @PC_MULTA, @CM_MOVFINANCEIRA)

			SELECT @SQ_MOVFINANCEIRA = @@IDENTITY
    END
  ELSE
		UPDATE TB_MOVFINANCEIRA
  	 SET ID_EMPRESA = @ID_EMPRESA,
				 ID_OPT_TIPOMOVFINANCEIRA = @ID_OPT_TIPOMOVFINANCEIRA,
				 ID_OPT_STATUS = ISNULL(@ID_OPT_STATUS, ID_OPT_STATUS),
				 ID_OPT_PERIODOCALCULOFINANCEIRO_DESCONTO = @ID_OPT_PERIODOCALCULOFINANCEIRO_DESCONTO,
				 ID_OPT_PERIODOCALCULOFINANCEIRO_JUROS = @ID_OPT_PERIODOCALCULOFINANCEIRO_JUROS,
				 ID_PESSOA = @ID_PESSOA,
				 ID_CONTAFINANCEIRA_CREDITO = @ID_CONTAFINANCEIRA_CREDITO,
				 ID_CONTAFINANCEIRA_DEBITO = @ID_CONTAFINANCEIRA_DEBITO,
				 ID_DOCUMENTOFISCAL = ISNULL(@ID_DOCUMENTOFISCAL, ID_DOCUMENTOFISCAL),
				 ID_PEDIDO = ISNULL(@ID_PEDIDO, ID_PEDIDO),
				 ID_ORDEMSERVICO = ISNULL(@ID_ORDEMSERVICO, ID_ORDEMSERVICO),
				 ID_SEGMENTO = @ID_SEGMENTO,
				 ID_CONDICAOPAGAMENTO = @ID_CONDICAOPAGAMENTO,
				 ID_CLINICA_VENDA = @ID_CLINICA_VENDA,
				 DS_MOVFINANCEIRA = @DS_MOVFINANCEIRA,
				 VL_MOVFINANCEIRA = @VL_MOVFINANCEIRA,
				 VL_ORIGINAL = @VL_ORIGINAL,
				 VL_DESCONTO = @VL_DESCONTO,
				 DT_MOVIMENTACAO = ISNULL(@DT_MOVIMENTACAO, DT_MOVIMENTACAO),
				 DT_1_VENCIMENTO = @DT_1_VENCIMENTO,
				 PC_ENTRADA = @PC_ENTRADA,
				 PC_JUROS = @PC_JUROS,
				 PC_DESCONTO = @PC_DESCONTO,
				 VL_MULTA = @VL_MULTA,
				 PC_MULTA = @PC_MULTA,
				 CM_MOVFINANCEIRA = @CM_MOVFINANCEIRA
		WHERE SQ_MOVFINANCEIRA = @SQ_MOVFINANCEIRA

  RETURN
END