USE Cli28Julho_Novo
GO
DROP VIEW SIS_FOREIGNKEY
DROP VIEW SIS_OBJETO_TEXTO_1
DROP VIEW SIS_OBJETO_TEXTO_2
DROP TABLE _bairros
DROP TABLE _cidades
DROP TABLE _LOGRADOUROS
DROP TABLE _uf
DROP TABLE T_AGENDATELEFONICA
DROP TABLE T_FORNECEDORES
DROP TABLE T_INDICACOESTERAPEUTICAS
DROP TABLE T_LABORATORIOS
DROP TABLE T_MEDICAMENTOS
DROP TABLE T_MOTIVOSRETORNO
DROP TABLE T_PACIENTES
DROP TABLE T_PACIENTES_OLD_01
DROP TABLE T_PACIENTES_OLD_02
DROP TABLE T_PACIENTESEVOLUCOES
DROP TABLE T_PACIENTESIMAGENS
DROP TABLE T_PACIENTESRETORNOPROG
DROP TABLE T_PROFISSOES
DROP TABLE T_RECIBOS
DROP TABLE T_TAXASDIARIAS
DROP TABLE T_TISS_CBOS_V1
DROP TABLE T_TISS_CBOS_V2
DROP TABLE T_TISS_GLOSAS
DROP TABLE T_TISS_TUSS_V1_01
DROP TABLE T_TISS_TUSS_V1_01_DEPARA
DROP TABLE T_USUARIOS
DELETE FROM TB_AGENDA_TELEFONE
DELETE FROM TB_AGENDA
DELETE FROM TB_ANAMNESE
DELETE FROM TB_ANOTACOES
DELETE FROM TB_ATENDIMENTO_DIAGNOSTICO
DELETE FROM TB_ATENDIMENTO_MEDICAMENTO
DELETE FROM TB_ATENDIMENTO_PROCEDIMENTO
DELETE FROM TB_ATENDIMENTO
DELETE FROM TB_CAMPANHA
DELETE FROM TB_CENTROCUSTO
DELETE FROM TB_CLINICA_FISIOTERAPIA
DELETE FROM TB_CLINICA_RECEITUARIO
DELETE FROM TB_CLINICA_RELATORIO
DELETE FROM TB_CLINICA_VACINA
DELETE FROM TB_CLINICA_VENDA_PROCEDIMENTO
DELETE FROM TB_CLINICA_PROCEDIMENTO
DELETE FROM TB_CONTABILIZACAO_PLANOCONTAS_FPGTO
DELETE FROM TB_PEDIDO_SERVICO
DELETE FROM TB_PEDIDO_FINANCIAMENTO
DELETE FROM TB_ESTOQUE_LANCAMENTO
DELETE FROM TB_DOCUMENTOFISCAL_PRODUTO_NRSERIE
DELETE FROM TB_DOCUMENTOFISCAL_PRODUTO
DELETE FROM TB_DOCUMENTOFISCAL
DELETE FROM TB_PEDIDO_PRODUTO_NSERIE
DELETE FROM TB_PEDIDO_PRODUTO
DELETE FROM TB_PEDIDO_PAGAMENTO
DELETE FROM TB_PEDIDO
UPDATE TB_EMPRESA SET ID_CANALNEGOCIO_PADRAO_VENDA = NULL, ID_CONDICAOPAGAMENTO_RECEBIMENTO_PADRAO = NULL, ID_CONDICAOPAGAMENTO_VENDA_PADRAO = NULL, ID_EQUIPAMENTO_PROCESSAMENTO_FISCAL = NULL,
                      ID_CONTAFINANCEIRA_PADRAO_VENDA = NULL, ID_CONTAFINANCEIRA_TESOURARIA = NULL, ID_ORDEMSERVICO_TABELAPRECO_PADRAO = NULL, ID_ORDEMSERVICO_OPT_TIPO_ORDEMSERVICO_PADRAO = NULL,
					  ID_TABELAPRECO_PADRAO = NULL, ID_TABELAPROCEDIMENTO_PADRAO = NULL, ID_PESSOA_RESPONSAVEL = NULL, ID_PESSOA_RESPONSAVELCONTABIL = NULL, ID_PESSOA_RESPONSAVELTECNICO = NULL,
					  ID_SEGMENTO_CRCP_PADRAO = NULL, ID_TRANSACAOESTOQUE_PADRAO_COMPRAS = NULL, ID_TRANSACAOESTOQUE_PADRAO_VENDAS = NULL
DELETE FROM TB_CANALNEGOCIO
DELETE FROM TB_CONTABILIZACAO
DELETE FROM TB_CONDICAOPAGAMENTO
DELETE FROM TB_CONVENIO_PROCEDIMENTO
DELETE FROM TB_DOENCA_ESTAGIO
DELETE FROM TB_ORCAMENTO_CLIENTE_PROCEDIMENTO
DELETE FROM TB_EQUIPAMENTO
DELETE FROM TB_FORMAPAGAMENTO_EQUIPAMENTO
DELETE FROM TB_ESTOQUE_LANCAMENTO
DELETE FROM TB_ESTOQUE_LOCALIZACAO_NUMEROSERIE
DELETE FROM TB_ESTOQUE_PRODUTO
DELETE FROM TB_ESTOQUE_LOCALIZACAO
DELETE FROM TB_PAGAMENTOITEM_MOVFINANCEIRA
DELETE FROM TB_LANCAMENTOCREDITOFINANCEIRO
DELETE FROM TB_MOVFINANCEIRA_FLUXOCAIXA
DELETE FROM TB_MOVFINANCEIRA_PLANOCONTAS
DELETE FROM TB_MOVFINANCEIRAPAGTO
DELETE FROM TB_PAGAMENTOITEM
DELETE FROM TB_PAGAMENTO
DELETE FROM TB_MOVFINANCEIRAPARCELA
DELETE FROM TB_MOVFINANCEIRAPARCELA_CANCELAMENTO
DELETE FROM TB_MOVFINANCEIRA
DELETE FROM TB_MOVIMENTACAOESTOQUE
DELETE FROM TB_GRUPOTRIBUTARIO_UF
DELETE FROM TB_ORDEMSERVICO_PRODUTOSERVICO
DELETE FROM TB_ORDEMSERVICO_HISTORICO
DELETE FROM TB_ORDEMSERVICO_PRODUTO
DELETE FROM TB_ORDEMSERVICO
DELETE FROM TB_HISTORICO
DELETE FROM TB_QUESTIONARIO_VERSAO_ITEM_ELEMENTO
DELETE FROM TB_QUESTIONARIO_VERSAO_CONTAINER_ELEMENTO
DELETE FROM TB_QUESTIONARIO_VERSAO_CONTAINER
DELETE FROM TB_QUESTIONARIO_VERSAO_ITEM
DELETE FROM TB_QUESTIONARIO_VERSAO
DELETE FROM TB_QUESTIONARIO_RESPOSTA
DELETE FROM TB_QUESTIONARIO_RESPOSTA_ITEM
DELETE FROM TB_QUESTIONARIO
DELETE FROM TB_PROCEDIMENTO_ESPECIALIDADE
DELETE FROM TB_CLINICA_VENDA
DELETE FROM TB_PESSOA_ATESTADO
DELETE FROM TB_CLINICA_EXAME_CITOLOGICO
DELETE FROM TB_CLINICA_ATENDIMENTO
DELETE FROM TB_AGENDAMENTO
DELETE FROM TB_PESSOA_HORARIO
DELETE FROM TB_PROCEDIMENTO
DELETE FROM TB_ORCAMENTO_CLIENTE
DELETE FROM TB_PRODUTO_LINHA_CARACTERISTICA
DELETE FROM TB_PRODUTO_CARACTERISTICA
DELETE FROM TB_CARACTERISTICA_PRODUTO
DELETE FROM TB_CLINICA_VENDA_FECHAMENTO
DELETE FROM TB_CONSULTORIO
DELETE FROM TB_PESSOA_LIMITECREDITO
DELETE FROM TB_PESSOA_MIDIASOCIAL
DELETE FROM TB_PESSOA_PATOLOGIAPARENTE
DELETE FROM TB_PESSOA_PESSOAVINCULADA
DELETE FROM TB_PESSOA_PROFISSAO
DELETE FROM TB_PESSOA_REFERENCIA
DELETE FROM TB_PESSOA_TELEFONE
DELETE FROM TB_PESSOA_ESPECIALIDADE
DELETE FROM TB_PESSOA_CONVENIO
DELETE FROM TB_PESSOA_ANEXO
DELETE FROM TB_PESSOA_AGENDA_LIBERACAO
DELETE FROM TB_PESSOA_AGENDA
DELETE FROM TB_PESSOA_ANTECEDENTES
DELETE FROM TB_PESSOA_CONFIGURACAO
DELETE FROM TB_PESSOA_CONTATO
DELETE FROM TB_PESSOA_EMPRESA
DELETE FROM TB_ENDERECO WHERE ID_PESSOA > 2
DELETE FROM TB_PRODUTO_EMPRESA_NUMEROSERIE
DELETE FROM TB_PRODUTO_EMPRESA_RELECIONADO
UPDATE TB_PRODUTO_EMPRESA_FILIAL SET ID_PRODUTO_LINHA = NULL
DELETE FROM TB_TABELAPRECO_SERVICO
DELETE FROM TB_TABELAPRECO_PRODUTO_LINHA_HST
DELETE FROM TB_TABELAPRECO_PRODUTO_LINHA
DELETE FROM TB_TABELAPRECO_PRODUTO_HST
DELETE FROM TB_TABELAPRECO_PRODUTO
DELETE FROM TB_VACINA
DELETE FROM TB_PRODUTO_LINHA
DELETE FROM TB_PRODUTO_FORNECEDOR
DELETE FROM TB_PRODUTO_ESTRUTURA_ITEM
DELETE FROM TB_PRODUTO_ESTRUTURA
DELETE FROM TB_PRODUTO_EMPRESA_FILIAL
DELETE FROM TB_PRODUTO_EMPRESA
DELETE FROM TB_PRODUTO
DELETE FROM TB_REPOSITORIOARQUIVO
DELETE FROM TB_SEG_USUARIO_GRID_CONFIGURAR
DELETE FROM TB_SEG_GRUPOPERMISSAO_ACESSO
DELETE FROM TB_SEG_USUARIO_GRUPOPERMISSAO
DELETE FROM TB_SEG_GRUPOPERMISSAO
DELETE FROM TB_SEG_USUARIO_ACESSO
DELETE FROM TB_SEG_USUARIO_EMPRESA
DELETE FROM TB_SEG_USUARIO WHERE ID_USUARIO > 2
DELETE FROM TB_SEGMENTO
DELETE FROM TB_SERVICO
DELETE FROM TB_SISTEMA_ARQUIVOS
DELETE FROM TB_FINANCIAMENTO_TABELAPRECO
DELETE FROM TB_TABELAPRECO
DELETE FROM TB_FINANCIAMENTO
UPDATE TB_PESSOA SET ID_PESSOA_RESPONSAVEL = NULL
DELETE FROM TB_PESSOA
 WHERE SQ_PESSOA > 2
   AND SQ_PESSOA NOT IN (SELECT ID_LABORATORIO FROM TB_MEDICAMENTO)
DELETE FROM TB_CONVENIO
DELETE FROM TB_EMPRESA_ESTACAO
DELETE FROM TB_EMPRESA_OPCAO
DELETE FROM TB_ERRO
DELETE FROM TB_ESPECIALIDADE
DELETE FROM TB_TRANSACAOESTOQUE
DELETE FROM TB_TABELAPROCEDIMENTO
DELETE FROM TB_ESTOQUE
DELETE FROM TB_GRUPOTRIBUTARIO
DELETE FROM TB_GRUPOPRODUTO_CARACTERISTICA
DELETE FROM TB_GRUPOPRODUTO
DELETE FROM TB_INDICACAO
UPDATE TB_NATUREZAOPERACAO SET ID_PLANOCONTAS = NULL, ID_DOCUMENTOFISCAL_SERIE = NULL
DELETE FROM TB_PLANOCONTAS
DELETE FROM TB_PLANOCONTAS_GRUPO
DELETE FROM TB_PROFISSAO
DELETE FROM TB_DOCUMENTOFINANCEIRO
DELETE FROM TB_DOCUMENTOFISCAL_INUTILIZACAO
DELETE FROM TB_DOCUMENTOFISCAL_PRODUTO_NRSERIE
DELETE FROM TB_DOCUMENTOFISCAL_PRODUTO
DELETE FROM TB_DOCUMENTOFISCAL_REFERENCIA
DELETE FROM TB_FORMAPAGAMENTO
DELETE FROM TB_DOCUMENTOFISCAL
DELETE FROM TB_CONTAFINANCEIRA
DELETE FROM TB_DEPARTAMENTO


BEGIN
DECLARE @SQLString nvarchar(500);  
DECLARE @ParmDefinition nvarchar(500);  
DECLARE @max_title INT;  
DECLARE @TABELA VARCHAR(1000);
DECLARE @CAMPO VARCHAR(1000);

  DECLARE ProdutoCaracteristica CURSOR FOR  
  SELECT TABELA, CAMPO FROM SIS_TABELAVIEW_CAMPO WHERE CAMPO LIKE 'SQ_%' AND TABELA LIKE 'TB_%'

  OPEN ProdutoCaracteristica

  IF @@FETCH_STATUS <> 0
    FETCH NEXT FROM ProdutoCaracteristica INTO @TABELA, @CAMPO

  WHILE @@FETCH_STATUS = 0  
  BEGIN
SET @SQLString = N'SELECT @max_titleOUT = ISNULL(max(' + @CAMPO +'), 0)   FROM ' + @TABELA;  
SET @ParmDefinition = N'@max_titleOUT INT OUTPUT';  
  
EXECUTE sp_executesql @SQLString, @ParmDefinition, @max_titleOUT=@max_title OUTPUT;  

  DBCC CHECKIDENT(@TABELA, RESEED, @max_title)

    FETCH NEXT FROM ProdutoCaracteristica INTO @TABELA, @CAMPO
  END

  CLOSE ProdutoCaracteristica
  DEALLOCATE ProdutoCaracteristica


SELECT @max_title;  
END
GO
DROP VIEW SIS_TABELAVIEW_CAMPO